## debug Tranception with retrieval

In [2]:
from os.path import exists
from os import chdir
chdir("/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/")

directory = 'model_scores/zero_shot_substitutions/Tranception_L_retrieval/'
idx = -1
with open('EVCouplings/output/Beltran_Lehner_2025/temp_ref_file.csv') as f_in:
    for lines in f_in:
        dms_id = lines.split(',')[0]
        score_csv = directory + dms_id + '.csv'
        if not exists(score_csv):
            print(dms_id, idx)
        idx += 1

DMS_id -1

The length of MSA is smaller than MSA_end index

In [3]:
import pandas as pd
df = pd.read_csv('EVCouplings/output/Beltran_Lehner_2025/temp_ref_file.csv')
df

,DMS_id,MSA_bitscore,MSA_num_seqs,MSA_perc_cov,MSA_num_cov,MSA_N_eff,MSA_Neff_L,MSA_Neff_L_category,weight_file_name,MSA_filename,...,MSA_start,MSA_end,MSA_len,MSA_theta,taxon,source_organism,includes_multiple_mutants,DMS_wildtype_score,first_author,coarse_selection_type
0,A0A2R8Y422_HUMAN_Beltran_2025_PF00240_2,0.7,61559,0.971,68,5929.1,84.701140,medium,A0A2R8Y422_HUMAN_Beltran_2025_PF00240_2_theta_...,A0A2R8Y422_HUMAN_Beltran_2025_PF00240_2_theta_...,...,1,70,70,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance
1,FEZF1_HUMAN_Beltran_2025_PF00096_289,1.5,645870,0.955,21,1813.5,82.430408,medium,FEZF1_HUMAN_Beltran_2025_PF00096_289_theta_0.8...,FEZF1_HUMAN_Beltran_2025_PF00096_289_theta_0.8...,...,1,22,22,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance
2,SPD2B_HUMAN_Beltran_2025_PF00018_155,0.9,33216,0.945,52,721.9,13.125128,medium,SPD2B_HUMAN_Beltran_2025_PF00018_155_theta_0.8...,SPD2B_HUMAN_Beltran_2025_PF00018_155_theta_0.8...,...,1,55,55,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance
3,SPD2B_HUMAN_Beltran_2025_PF00018_222,0.9,45592,0.898,53,947.7,16.062838,medium,SPD2B_HUMAN_Beltran_2025_PF00018_222_theta_0.8...,SPD2B_HUMAN_Beltran_2025_PF00018_222_theta_0.8...,...,1,59,59,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance
4,A2RRE5_HUMAN_Beltran_2025_PF01846_267,0.7,4543,0.952,60,128.7,2.042930,medium,A2RRE5_HUMAN_Beltran_2025_PF01846_267_theta_0....,A2RRE5_HUMAN_Beltran_2025_PF01846_267_theta_0....,...,1,63,63,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,CD2AP_HUMAN_Beltran_2025_PF14604_1,1.1,91191,0.881,52,1947.7,33.012110,medium,CD2AP_HUMAN_Beltran_2025_PF14604_1_theta_0.8_b...,CD2AP_HUMAN_Beltran_2025_PF14604_1_theta_0.8_b...,...,1,59,59,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance
515,CD2AP_HUMAN_Beltran_2025_PF14604_109,1.1,101933,0.869,53,1764.6,28.927503,medium,CD2AP_HUMAN_Beltran_2025_PF14604_109_theta_0.8...,CD2AP_HUMAN_Beltran_2025_PF14604_109_theta_0.8...,...,1,61,61,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance
516,NCOR2_HUMAN_Beltran_2025_PF00249_613,0.7,57518,0.828,48,1467.9,25.307762,medium,NCOR2_HUMAN_Beltran_2025_PF00249_613_theta_0.8...,NCOR2_HUMAN_Beltran_2025_PF00249_613_theta_0.8...,...,1,58,58,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance
517,USH1C_HUMAN_Beltran_2025_PF00595_207,0.7,123337,0.831,74,1477.5,16.601235,medium,USH1C_HUMAN_Beltran_2025_PF00595_207_theta_0.8...,USH1C_HUMAN_Beltran_2025_PF00595_207_theta_0.8...,...,1,89,89,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance
518,PCLO_HUMAN_Beltran_2025_PF05715_1058,0.7,14023,0.982,56,107.5,1.885980,medium,PCLO_HUMAN_Beltran_2025_PF05715_1058_theta_0.8...,PCLO_HUMAN_Beltran_2025_PF05715_1058_theta_0.8...,...,1,57,57,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance

In [7]:
df[df['seq_len'] != df['MSA_end']][['DMS_id', 'MSA_end', 'seq_len']]

                                   DMS_id  MSA_end  seq_len
6     WWP2_HUMAN_Beltran_2025_PF00397_440       41       54
82     BAG3_HUMAN_Beltran_2025_PF00397_11       67       49
185   YAP1_HUMAN_Beltran_2025_PF00397_162       46       50
435  WWTR1_HUMAN_Beltran_2025_PF00397_116       56       47

Fix: Fix the bug when making the reference file and manually updated the MSA_end to be the same as seq_len

## Debug AIDO

CUX2_HUMAN_Beltran_2025_PF02376_1036

Issue: the a2m reader reads in sequences by line and cannot handle sequences that span more than 1 line

fixes are in `/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/scoring_scripts/test/pg_baselines/AIDO/compute_fitness.py`

## Debug PoET

In [8]:
from pathlib import Path

In [14]:
ref_series = pd.read_csv("EVCouplings/output/Beltran_Lehner_2025/temp_ref_file.csv").iloc[0]
msa_filename = ref_series["MSA_filename"].removesuffix(".a2m")
msa_filepath = Path("DMS_assays/processed_data/Beltran_Lehner_2025/cleaned").joinpath(msa_filename + ".a3m.zst")

In [15]:
msa_filepath

PosixPath('DMS_assays/processed_data/Beltran_Lehner_2025/cleaned/A0A2R8Y422_HUMAN_Beltran_2025_PF00240_2_theta_0.8_b0.7.a3m.zst')

In [11]:
msa_filename

'A0A2R8Y422_HUMAN_Beltran_2025_PF00240_2_theta_0.8_b0.7'

## debug EVE

reference sheet: 28027 sequences

In [2]:
import numpy as np
from evcouplings.align import Alignment, map_matrix
from collections import defaultdict
import pandas as pd
import sys

In [5]:
msa_location = "EVCouplings/output/Beltran_Lehner_2025/selected_alignments/ODPX_HUMAN_Beltran_2025_PF02817_181_theta_0.8_b1.05.a2m"

In [4]:
with open("EVCouplings/output/Beltran_Lehner_2025/selected_alignments/RBP2_HUMAN_Beltran_2025_PF00641_1414_theta_0.8_b0.9.a2m", "r") as infile:
    aln = Alignment.from_file(infile, format="fasta")
    print(aln.N)

28027

In [5]:
weights_file = 'EVCouplings/output/Beltran_Lehner_2025/weights/RBP2_HUMAN_Beltran_2025_PF00641_1414_theta_0.8_b0.9.npy'
weights = np.load(weights_file)
print(weights.shape[0])

28004

Is it because of the 50% gap fraction filter?

In [6]:
focus_seq_name = ""
seq_name_to_sequence = defaultdict(str)

with open(msa_location, "r") as msa_data:
    for i, line in enumerate(msa_data):
        line = line.rstrip()
        if line.startswith(">"):
            name = line
            if i == 0:
                focus_seq_name = name
        else:
            seq_name_to_sequence[name] += line
print("Number of sequences in MSA (before preprocessing):", len(seq_name_to_sequence))

Number of sequences in MSA (before preprocessing): 28027

In [7]:
msa_df = pd.DataFrame.from_dict(seq_name_to_sequence, orient='index', columns=['sequence'])

In [11]:
msa_df

                                                          sequence
>P49792_PF00641_1414/1-30           KKEGHWDCSICLVRNEPTVSRCIACQNTKS
>UniRef100_UPI0020B20602/1308-1335  KKEGEWECSVCCIRNSSTAMSCAACQNA--
>UniRef100_UPI0020B20602/1442-1469  KKPGQWDCGTCAVMNEATATSCIACQAP--
>UniRef100_UPI0020B20602/1500-1527  KKPGQWDCGTCAVMNEATATSCIACQAP--
>UniRef100_UPI0020B20602/1558-1585  KKPGQWDCGTCAVMNEATATSCIACQAP--
...                                                            ...
>UniRef100_A0A816F0L2/34-62         KNENQWQCLVCSMKNSASSRQCQTCDVPK-
>UniRef100_A0A817KEW8/416-443       KKENNWQCDECSGTNEPSTKRCVCCGTP--
>UniRef100_A0A7S3XIK0/106-132       --DGQWECSQCTLLNPSASASCGACRAAK-
>UniRef100_T0Q2R0/23-46             ----MWECPTCTLRNTLTAEACDACGTT--
>UniRef100_A0A818IU17/42-64         ---SQWECPICTYQNDNSRTRCEMCQ----

[28027 rows x 1 columns]

In [40]:
msa_df.sequence = msa_df.sequence.apply(lambda x: x.replace(".", "-")).apply(
    lambda x: ''.join([aa.upper() for aa in x]))
# Remove columns that would be gaps in the wild type
non_gap_wt_cols = [aa != '-' for aa in msa_df.sequence[focus_seq_name]]
msa_df['sequence'] = msa_df['sequence'].apply(
    lambda x: ''.join([aa for aa, non_gap_ind in zip(x, non_gap_wt_cols) if non_gap_ind]))

In [49]:
threshold_sequence_frac_gaps = 0.5

In [50]:
print("Calculating proportion of gaps")
msa_array = np.array([list(seq) for seq in msa_df.sequence])
gaps_array = np.array(list(map(lambda seq: [aa == '-' for aa in seq], msa_array)))
# Identify fragments with too many gaps
seq_gaps_frac = gaps_array.mean(axis=1)
seq_below_threshold = seq_gaps_frac <= threshold_sequence_frac_gaps
print("Proportion of sequences dropped due to fraction of gaps: " + str(
    round(float(1 - seq_below_threshold.sum() / seq_below_threshold.shape) * 100, 2)) + "%")

Calculating proportion of gaps
Proportion of sequences dropped due to fraction of gaps: 0.0%

/tmp/ipykernel_1016572/203036351.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  round(float(1 - seq_below_threshold.sum() / seq_below_threshold.shape) * 100, 2)) + "%")

In [22]:
msa_array

array([['K', 'K', 'E', ..., 'T', 'K', 'S'],
       ['K', 'K', 'E', ..., 'A', '-', '-'],
       ['K', 'K', 'P', ..., 'P', '-', '-'],
       ...,
       ['-', '-', 'D', ..., 'A', 'K', '-'],
       ['-', '-', '-', ..., 'T', '-', '-'],
       ['-', '-', '-', ..., '-', '-', '-']],
      shape=(28027, 30), dtype='<U1')

In [23]:
gaps_array

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False,  True,  True],
       [False, False, False, ..., False,  True,  True],
       ...,
       [ True,  True, False, ..., False, False,  True],
       [ True,  True,  True, ..., False,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]], shape=(28027, 30))

In [24]:
seq_gaps_frac

array([0.        , 0.06666667, 0.06666667, ..., 0.1       , 0.2       ,
       0.23333333], shape=(28027,))

all sequences have gap fraction < 50%

try filter by minimum column cov 70%

In [29]:
threshold_focus_cols_frac_gaps = 0.3

In [30]:
columns_gaps_frac = gaps_array[seq_below_threshold].mean(axis=0)
index_cols_below_threshold = columns_gaps_frac <= threshold_focus_cols_frac_gaps
print("Proportion of non-focus columns removed: " + str(
    round(float(1 - index_cols_below_threshold.sum() / index_cols_below_threshold.shape) * 100, 2)) + "%")

Proportion of non-focus columns removed: 13.33%

/tmp/ipykernel_1016572/430170202.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  round(float(1 - index_cols_below_threshold.sum() / index_cols_below_threshold.shape) * 100, 2)) + "%")

In [31]:
index_cols_below_threshold

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False])

In [34]:
def _lower_case_and_filter_fragments(seq):
    return ''.join([aa.lower() if aa_ix in index_cols_below_threshold else aa for aa_ix, aa in enumerate(seq)])
msa_df['sequence'] = msa_df['sequence'].apply(
    lambda seq: ''.join([aa.upper() if upper_case_ind else aa.lower() for aa, upper_case_ind in
     zip(seq, index_cols_below_threshold)]))
msa_df = msa_df[seq_below_threshold]
# Overwrite seq_name_to_sequence with clean version
seq_name_to_sequence = defaultdict(str)
# Create a dictionary from msa_df.index to msa_df.sequence
seq_name_to_sequence = dict(zip(msa_df.index, msa_df.sequence))

In [37]:
num_sequences_removed_due_to_indeterminate_AAs = 0
num_sequences_before_indeterminate_AA_drop = len(seq_name_to_sequence)
alphabet_set = set(list("ACDEFGHIKLMNPQRSTVWY"))
seq_names_to_remove = []
for seq_name, sequence in seq_name_to_sequence.items():
    for letter in sequence:
        if letter not in alphabet_set and letter != "-":
            seq_names_to_remove.append(seq_name)
            continue
seq_names_to_remove = list(set(seq_names_to_remove))
for seq_name in seq_names_to_remove:
    num_sequences_removed_due_to_indeterminate_AAs+=1
    del seq_name_to_sequence[seq_name]
print("Proportion of sequences dropped due to indeterminate AAs: {}%".format(round(float(num_sequences_removed_due_to_indeterminate_AAs/num_sequences_before_indeterminate_AA_drop*100),2)))

Proportion of sequences dropped due to indeterminate AAs: 88.43%

In [39]:
len(seq_name_to_sequence)

3242

this is problematic, it shouldn't filter out this many sequences

In [3]:
# sys.path.append("/n/groups/marks/users/elain/PG2/ProteinGym")
from proteingym.utils.msa_utils import MSA_processing

In [11]:
def get_aln_stats(protein, MSA_location, weights_location, skip_one_hot_encodings=True):
    '''
    modified from get_aln_stats on https://github.com/aaronkollasch/EVE/blob/master/scripts/get_alignment_stats.py
    remove all AWS commands
    '''
    # weights_fname = protein + '_theta_' + str(theta) + '.npy'

    msa = MSA_processing(
        MSA_location=MSA_location,
        weights_location=weights_location,
        threshold_focus_cols_frac_gaps=1,
        use_weights=True
    )

    #assert msa.focus_seq_name.lstrip(">")  == protein
    num_seqs = 0
    with open(MSA_location) as f:
        for line in f:
            if line.startswith(">"):
                num_seqs += 1

    result = {
        "protein": protein,
        "num_seqs": msa.num_sequences,
        "num_seqs_unfiltered": num_seqs,
        "perc_filtered": msa.num_sequences / num_seqs,
        "n_eff": msa.Neff,
        "n_eff_l": msa.Neff / len(msa.focus_seq),
        "seq_len": len(msa.focus_seq),
        "num_cov": msa.one_hot_encoding.shape[1],
        "perc_cov": msa.one_hot_encoding.shape[1] / len(msa.focus_seq),
    }

    print(protein)
    return result

In [12]:
get_aln_stats("RBP2_HUMAN_Beltran_2025_PF00641_1414", "EVCouplings/output/Beltran_Lehner_2025/selected_alignments/RBP2_HUMAN_Beltran_2025_PF00641_1414_theta_0.8_b0.9.a2m", "./test.npy")

Proportion of sequences dropped due to fraction of gaps: 0.0%
Proportion of non-focus columns removed: 0.0%
Encoding sequences
One-hot encoded sequences shape:(28004, 30, 20)
Loaded sequence weights from disk
Neff = 1535.9666987077107
Data Shape = (28004, 30, 20)
RBP2_HUMAN_Beltran_2025_PF00641_1414

{'protein': 'RBP2_HUMAN_Beltran_2025_PF00641_1414',
 'num_seqs': 28004,
 'num_seqs_unfiltered': 28027,
 'perc_filtered': 0.9991793627573411,
 'n_eff': 1535.9666987077107,
 'n_eff_l': 51.19888995692369,
 'seq_len': 30,
 'num_cov': 30,
 'perc_cov': 1.0}

In [10]:
wt = np.load('EVCouplings/output/Beltran_Lehner_2025/weights/ODPX_HUMAN_Beltran_2025_PF02817_181_theta_0.8_b1.05.npy')

In [11]:
wt.shape[0]

1448

In [20]:
get_aln_stats("ODPX_HUMAN_Beltran_2025_PF02817_181", "EVCouplings/output/Beltran_Lehner_2025/selected_alignments/ODPX_HUMAN_Beltran_2025_PF02817_181_theta_0.8_b1.05.a2m", "./test2.npy")

Proportion of sequences dropped due to fraction of gaps: 0.0%
Proportion of non-focus columns removed: 0.0%
Encoding sequences
One-hot encoded sequences shape:(1447, 47, 20)
Computing sequence weights
Neff = 39.13101962965613
Data Shape = (1447, 47, 20)
ODPX_HUMAN_Beltran_2025_PF02817_181

{'protein': 'ODPX_HUMAN_Beltran_2025_PF02817_181',
 'num_seqs': 1447,
 'num_seqs_unfiltered': 1448,
 'perc_filtered': 0.9993093922651933,
 'n_eff': 39.13101962965613,
 'n_eff_l': 0.8325748857373645,
 'seq_len': 47,
 'num_cov': 47,
 'perc_cov': 1.0}

In [21]:
wt = np.load('./test2.npy')
wt.shape[0]

1447

issues with weight calculation on AWS. check which sequences have this issue

In [3]:
def check_weights_dim(protein, MSA_location, weights_location, issues_list, threshold_focus_cols_frac_gaps=1, skip_one_hot_encodings=True):
    msa = MSA_processing(
        MSA_location=MSA_location,
        weights_location=weights_location,
        threshold_focus_cols_frac_gaps=threshold_focus_cols_frac_gaps,
        use_weights=True
    )

    num_seqs = len(msa.seq_name_to_sequence)

    weights = np.load(weights_location)

    if num_seqs != weights.shape[0]:
        issues_list.append(f"{protein} has {num_seqs} processed sequences but {weights.shape[0]} entries in weights")

In [4]:
df = pd.read_csv("EVCouplings/output/Beltran_Lehner_2025/temp_ref_file.csv")
df.head()

,DMS_id,MSA_bitscore,MSA_num_seqs,MSA_perc_cov,MSA_num_cov,MSA_N_eff,MSA_Neff_L,MSA_Neff_L_category,weight_file_name,MSA_filename,...,MSA_start,MSA_end,MSA_len,MSA_theta,taxon,source_organism,includes_multiple_mutants,DMS_wildtype_score,first_author,coarse_selection_type
0,A0A2R8Y422_HUMAN_Beltran_2025_PF00240_2,0.7,61559,0.971,68,5929.1,84.701140,medium,A0A2R8Y422_HUMAN_Beltran_2025_PF00240_2_theta_...,A0A2R8Y422_HUMAN_Beltran_2025_PF00240_2_theta_...,...,1,70,70,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance
1,FEZF1_HUMAN_Beltran_2025_PF00096_289,1.5,645870,0.955,21,1813.5,82.430408,medium,FEZF1_HUMAN_Beltran_2025_PF00096_289_theta_0.8...,FEZF1_HUMAN_Beltran_2025_PF00096_289_theta_0.8...,...,1,22,22,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance
2,SPD2B_HUMAN_Beltran_2025_PF00018_155,0.9,33216,0.945,52,721.9,13.125128,medium,SPD2B_HUMAN_Beltran_2025_PF00018_155_theta_0.8...,SPD2B_HUMAN_Beltran_2025_PF00018_155_theta_0.8...,...,1,55,55,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance
3,SPD2B_HUMAN_Beltran_2025_PF00018_222,0.9,45592,0.898,53,947.7,16.062838,medium,SPD2B_HUMAN_Beltran_2025_PF00018_222_theta_0.8...,SPD2B_HUMAN_Beltran_2025_PF00018_222_theta_0.8...,...,1,59,59,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance
4,A2RRE5_HUMAN_Beltran_2025_PF01846_267,0.7,4543,0.952,60,128.7,2.042930,medium,A2RRE5_HUMAN_Beltran_2025_PF01846_267_theta_0....,A2RRE5_HUMAN_Beltran_2025_PF01846_267_theta_0....,...,1,63,63,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance

From the old PG repo (/n/groups/marks/projects/indels_human/anon/proteingym)

In [5]:
issues_list = []
row = df.iloc[6]
check_weights_dim(row['DMS_id'], "EVCouplings/output/Beltran_Lehner_2025/selected_alignments/"+row['MSA_filename'], 'EVCouplings/output/Beltran_Lehner_2025/weights/' + row['weight_file_name'], issues_list, 1)

NameError: name 'MSA_processing' is not defined

From the updated PG repo (/n/groups/marks/users/elain/PG2/ProteinGym/proteingym/)

In [6]:
import inspect
sys.path.insert(0, "/n/groups/marks/users/elain/PG2/ProteinGym/proteingym")
from utils.msa_utils import MSA_processing

print(f"Path to the module containing '{MSA_processing.__name__}': {inspect.getfile(MSA_processing)}")

issues_list = []
row = df.iloc[7]
check_weights_dim(row['DMS_id'], "EVCouplings/output/Beltran_Lehner_2025/selected_alignments/"+row['MSA_filename'], 'EVCouplings/output/Beltran_Lehner_2025/weights/' + row['weight_file_name'], issues_list, 1)

Path to the module containing 'MSA_processing': /n/groups/marks/users/elain/PG2/ProteinGym/proteingym/utils/msa_utils.py
Number of sequences in MSA (before preprocessing): 1448
Calculating proportion of gaps
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
>UniRef100_A0A0D3L3P4/96-142
Number of sequences dropped due to indeterminate AAs: 1
Number of sequences after preprocessing: 1447
Data Shape = (1447, 47, 20)

In [7]:
check_weights_dim(row['DMS_id'], "EVCouplings/output/Beltran_Lehner_2025/selected_alignments/"+row['MSA_filename'], 'EVCouplings/output/Beltran_Lehner_2025/weights/' + row['weight_file_name'], issues_list, 0.3)

Number of sequences in MSA (before preprocessing): 1448
Calculating proportion of gaps
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [4]
Number of sequences dropped due to indeterminate AAs: 0
Number of sequences after preprocessing: 1448
Data Shape = (1448, 43, 20)

In [6]:
from proteingym.utils.msa_utils import MSA_processing
issues_list = []
for index, row in df.iterrows():
    check_weights_dim(row['DMS_id'], "EVCouplings/output/Beltran_Lehner_2025/selected_alignments/"+row['MSA_filename'], 'EVCouplings/output/Beltran_Lehner_2025/weights/' + row['weight_file_name'], issues_list)

Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]

/n/groups/marks/projects/indels_human/anon/proteingym/utils/msa_utils.py:102: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  self.seq_name_to_sequence[msa_df.index[seq_idx]] = msa_df.sequence[seq_idx]

Number of sequences dropped due to indeterminate AAs: 420
Encoding sequences
One-hot encoded sequences shape:(61139, 70, 20)
Loaded sequence weights from disk
Neff = 5929.079783031528
Data Shape = (61139, 70, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 609
Encoding sequences
One-hot encoded sequences shape:(645261, 22, 20)
Loaded sequence weights from disk
Neff = 1813.46897642701
Data Shape = (645261, 22, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 31
Encoding sequences
One-hot encoded sequences shape:(33185, 55, 20)
Loaded sequence weights from disk
Neff = 721.8820344013982
Data Shape = (33185, 55, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 35
Encoding sequences
One-hot encoded sequences shape:(45557, 59, 20)
Loaded sequence weights from disk
Neff = 947.7074667297903
Data Shape = (45557, 59, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 16
Encoding sequences
One-hot encoded sequences shape:(4527, 63, 20)
Loaded sequence weights from disk
Neff = 128.70457733011548
Data Shape = (4527, 63, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 40
Encoding sequences
One-hot encoded sequences shape:(29706, 41, 20)
Loaded sequence weights from disk
Neff = 2172.1220543589475
Data Shape = (29706, 41, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 34
Encoding sequences
One-hot encoded sequences shape:(59924, 54, 20)
Loaded sequence weights from disk
Neff = 3660.8540178801677
Data Shape = (59924, 54, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 1
Encoding sequences
One-hot encoded sequences shape:(1447, 47, 20)
Loaded sequence weights from disk
Neff = 38.83908106213912
Data Shape = (1447, 47, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 30
Encoding sequences
One-hot encoded sequences shape:(24578, 89, 20)
Loaded sequence weights from disk
Neff = 178.42690132623378
Data Shape = (24578, 89, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 26
Encoding sequences
One-hot encoded sequences shape:(24743, 69, 20)
Loaded sequence weights from disk
Neff = 180.30143688769027
Data Shape = (24743, 69, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 466
Encoding sequences
One-hot encoded sequences shape:(592050, 93, 20)
Loaded sequence weights from disk
Neff = 7029.846916048968
Data Shape = (592050, 93, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 13
Encoding sequences
One-hot encoded sequences shape:(13349, 78, 20)
Loaded sequence weights from disk
Neff = 262.50750934597113
Data Shape = (13349, 78, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 8
Encoding sequences
One-hot encoded sequences shape:(11990, 69, 20)
Loaded sequence weights from disk
Neff = 237.6061361490171
Data Shape = (11990, 69, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 13
Encoding sequences
One-hot encoded sequences shape:(18919, 50, 20)
Loaded sequence weights from disk
Neff = 674.3660416170007
Data Shape = (18919, 50, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 12
Encoding sequences
One-hot encoded sequences shape:(18638, 62, 20)
Loaded sequence weights from disk
Neff = 792.7946588540103
Data Shape = (18638, 62, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 4
Encoding sequences
One-hot encoded sequences shape:(4870, 59, 20)
Loaded sequence weights from disk
Neff = 264.01468323374274
Data Shape = (4870, 59, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 3
Encoding sequences
One-hot encoded sequences shape:(4579, 56, 20)
Loaded sequence weights from disk
Neff = 288.02978316835055
Data Shape = (4579, 56, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 566
Encoding sequences
One-hot encoded sequences shape:(235574, 56, 20)
Loaded sequence weights from disk
Neff = 4465.102953564692
Data Shape = (235574, 56, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 46
Encoding sequences
One-hot encoded sequences shape:(100762, 24, 20)
Loaded sequence weights from disk
Neff = 1645.2165504401505
Data Shape = (100762, 24, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 33
Encoding sequences
One-hot encoded sequences shape:(28945, 82, 20)
Loaded sequence weights from disk
Neff = 354.778906219169
Data Shape = (28945, 82, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 3
Encoding sequences
One-hot encoded sequences shape:(3746, 31, 20)
Loaded sequence weights from disk
Neff = 97.27926999446056
Data Shape = (3746, 31, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 103
Encoding sequences
One-hot encoded sequences shape:(166704, 60, 20)
Loaded sequence weights from disk
Neff = 5318.991756302339
Data Shape = (166704, 60, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 6
Encoding sequences
One-hot encoded sequences shape:(8135, 61, 20)
Loaded sequence weights from disk
Neff = 253.0594975243328
Data Shape = (8135, 61, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 571
Encoding sequences
One-hot encoded sequences shape:(236283, 56, 20)
Loaded sequence weights from disk
Neff = 4481.988309798053
Data Shape = (236283, 56, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 57
Encoding sequences
One-hot encoded sequences shape:(47718, 43, 20)
Loaded sequence weights from disk
Neff = 1366.6719757641367
Data Shape = (47718, 43, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 37
Encoding sequences
One-hot encoded sequences shape:(60301, 63, 20)
Loaded sequence weights from disk
Neff = 1534.3769755637732
Data Shape = (60301, 63, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 267
Encoding sequences
One-hot encoded sequences shape:(120642, 68, 20)
Loaded sequence weights from disk
Neff = 6424.573757200678
Data Shape = (120642, 68, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 5
Encoding sequences
One-hot encoded sequences shape:(13927, 25, 20)
Loaded sequence weights from disk
Neff = 758.7179122448485
Data Shape = (13927, 25, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 0
Encoding sequences
One-hot encoded sequences shape:(6009, 22, 20)
Loaded sequence weights from disk
Neff = 317.6594043425179
Data Shape = (6009, 22, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 39
Encoding sequences
One-hot encoded sequences shape:(151296, 22, 20)
Loaded sequence weights from disk
Neff = 1815.0221835513214
Data Shape = (151296, 22, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 569
Encoding sequences
One-hot encoded sequences shape:(236107, 56, 20)
Loaded sequence weights from disk
Neff = 4455.575593954889
Data Shape = (236107, 56, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 5
Encoding sequences
One-hot encoded sequences shape:(11179, 58, 20)
Loaded sequence weights from disk
Neff = 98.9207480562346
Data Shape = (11179, 58, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 69
Encoding sequences
One-hot encoded sequences shape:(15279, 81, 20)
Loaded sequence weights from disk
Neff = 1613.8722995956725
Data Shape = (15279, 81, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 17
Encoding sequences
One-hot encoded sequences shape:(21988, 28, 20)
Loaded sequence weights from disk
Neff = 649.1902041495625
Data Shape = (21988, 28, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 0
Encoding sequences
One-hot encoded sequences shape:(1510, 68, 20)
Loaded sequence weights from disk
Neff = 115.13617274591752
Data Shape = (1510, 68, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 84
Encoding sequences
One-hot encoded sequences shape:(152676, 56, 20)
Loaded sequence weights from disk
Neff = 2993.8840212847686
Data Shape = (152676, 56, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 0
Encoding sequences
One-hot encoded sequences shape:(2007, 24, 20)
Loaded sequence weights from disk
Neff = 99.85969698056593
Data Shape = (2007, 24, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 3
Encoding sequences
One-hot encoded sequences shape:(7984, 19, 20)
Loaded sequence weights from disk
Neff = 571.155549711921
Data Shape = (7984, 19, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 3
Encoding sequences
One-hot encoded sequences shape:(2826, 79, 20)
Loaded sequence weights from disk
Neff = 129.75363661671182
Data Shape = (2826, 79, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 5
Encoding sequences
One-hot encoded sequences shape:(20345, 22, 20)
Loaded sequence weights from disk
Neff = 239.42628813602693
Data Shape = (20345, 22, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 18
Encoding sequences
One-hot encoded sequences shape:(15537, 67, 20)
Loaded sequence weights from disk
Neff = 606.5289750149013
Data Shape = (15537, 67, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 62
Encoding sequences
One-hot encoded sequences shape:(58044, 83, 20)
Loaded sequence weights from disk
Neff = 1026.1862181098793
Data Shape = (58044, 83, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 574
Encoding sequences
One-hot encoded sequences shape:(238426, 56, 20)
Loaded sequence weights from disk
Neff = 4619.418199802334
Data Shape = (238426, 56, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 17
Encoding sequences
One-hot encoded sequences shape:(39734, 35, 20)
Loaded sequence weights from disk
Neff = 1167.1567641937108
Data Shape = (39734, 35, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 240
Encoding sequences
One-hot encoded sequences shape:(175146, 90, 20)
Loaded sequence weights from disk
Neff = 2545.5832166410364
Data Shape = (175146, 90, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 33
Encoding sequences
One-hot encoded sequences shape:(43342, 78, 20)
Loaded sequence weights from disk
Neff = 552.3743210037896
Data Shape = (43342, 78, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 19
Encoding sequences
One-hot encoded sequences shape:(28793, 90, 20)
Loaded sequence weights from disk
Neff = 372.44566574527835
Data Shape = (28793, 90, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 17
Encoding sequences
One-hot encoded sequences shape:(16343, 44, 20)
Loaded sequence weights from disk
Neff = 928.3170754527971
Data Shape = (16343, 44, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 23
Encoding sequences
One-hot encoded sequences shape:(23744, 51, 20)
Loaded sequence weights from disk
Neff = 1056.3529884018176
Data Shape = (23744, 51, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 10
Encoding sequences
One-hot encoded sequences shape:(23052, 50, 20)
Loaded sequence weights from disk
Neff = 917.39118082531
Data Shape = (23052, 50, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 4
Encoding sequences
One-hot encoded sequences shape:(7400, 54, 20)
Loaded sequence weights from disk
Neff = 267.44971504515775
Data Shape = (7400, 54, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 5
Encoding sequences
One-hot encoded sequences shape:(6148, 55, 20)
Loaded sequence weights from disk
Neff = 158.5235642609871
Data Shape = (6148, 55, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 5
Encoding sequences
One-hot encoded sequences shape:(7054, 60, 20)
Loaded sequence weights from disk
Neff = 330.90687463286685
Data Shape = (7054, 60, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 5
Encoding sequences
One-hot encoded sequences shape:(5671, 66, 20)
Loaded sequence weights from disk
Neff = 650.473751249174
Data Shape = (5671, 66, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 36
Encoding sequences
One-hot encoded sequences shape:(21342, 71, 20)
Loaded sequence weights from disk
Neff = 961.251464542705
Data Shape = (21342, 71, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 75
Encoding sequences
One-hot encoded sequences shape:(43673, 69, 20)
Loaded sequence weights from disk
Neff = 3008.617738561872
Data Shape = (43673, 69, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 29
Encoding sequences
One-hot encoded sequences shape:(18567, 72, 20)
Loaded sequence weights from disk
Neff = 497.411248689632
Data Shape = (18567, 72, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 5
Encoding sequences
One-hot encoded sequences shape:(9433, 36, 20)
Loaded sequence weights from disk
Neff = 512.6919546945787
Data Shape = (9433, 36, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 3
Encoding sequences
One-hot encoded sequences shape:(20589, 27, 20)
Loaded sequence weights from disk
Neff = 1444.4359554307275
Data Shape = (20589, 27, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 163
Encoding sequences
One-hot encoded sequences shape:(80339, 62, 20)
Loaded sequence weights from disk
Neff = 4132.372677013834
Data Shape = (80339, 62, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 3
Encoding sequences
One-hot encoded sequences shape:(6672, 88, 20)
Loaded sequence weights from disk
Neff = 125.2873874300623
Data Shape = (6672, 88, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 250
Encoding sequences
One-hot encoded sequences shape:(362037, 85, 20)
Loaded sequence weights from disk
Neff = 3450.9007127208597
Data Shape = (362037, 85, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 195
Encoding sequences
One-hot encoded sequences shape:(307539, 92, 20)
Loaded sequence weights from disk
Neff = 2784.2896989230135
Data Shape = (307539, 92, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 58
Encoding sequences
One-hot encoded sequences shape:(88576, 96, 20)
Loaded sequence weights from disk
Neff = 609.6358973598165
Data Shape = (88576, 96, 20)
Number of sequences dropped due to fraction of gaps: [0]
Number of non-focus columns removed: [0]
Number of sequences dropped due to indeterminate AAs: 21
Encoding sequences
One-hot encoded sequences shape:(33903, 59, 20)

KeyboardInterrupt:

In [ ]:
issues_list

['WWP2_HUMAN_Beltran_2025_PF00397_440 has 59924 processed sequences but 59926 entries in weights',
 'ODPX_HUMAN_Beltran_2025_PF02817_181 has 1447 processed sequences but 1448 entries in weights',
 'DVL1_HUMAN_Beltran_2025_PF00595_246 has 592050 processed sequences but 592066 entries in weights',
 'TCRG1_HUMAN_Beltran_2025_PF01846_645 has 11990 processed sequences but 11991 entries in weights',
 'NPHP1_HUMAN_Beltran_2025_PF00018_152 has 166704 processed sequences but 166708 entries in weights',
 'TRI18_HUMAN_Beltran_2025_PF00643_172 has 47718 processed sequences but 47719 entries in weights',
 'P73_HUMAN_Beltran_2025_PF07647_487 has 60301 processed sequences but 60304 entries in weights',
 'LDB3_HUMAN_Beltran_2025_PF00595_1 has 58044 processed sequences but 58045 entries in weights',
 'FLNB_HUMAN_Beltran_2025_PF00630_1423 has 175146 processed sequences but 175147 entries in weights',
 'FLNB_HUMAN_Beltran_2025_PF00630_2109 has 43342 processed sequences but 43344 entries in weights',
 'FLNB_HUMAN_Beltran_2025_PF00630_2289 has 28793 processed sequences but 28794 entries in weights',
 'CSDE1_HUMAN_Beltran_2025_PF00313_184 has 21342 processed sequences but 21345 entries in weights',
 'CSDE1_HUMAN_Beltran_2025_PF00313_23 has 43673 processed sequences but 43676 entries in weights',
 'MPDZ_HUMAN_Beltran_2025_PF00595_1860 has 362037 processed sequences but 362039 entries in weights',
 'MPDZ_HUMAN_Beltran_2025_PF00595_372 has 307539 processed sequences but 307540 entries in weights',
 'SASH1_HUMAN_Beltran_2025_PF00536_630 has 36922 processed sequences but 36924 entries in weights',
 'ABLM3_HUMAN_Beltran_2025_PF00412_149 has 162593 processed sequences but 162594 entries in weights',
 'ABLM3_HUMAN_Beltran_2025_PF00412_210 has 56921 processed sequences but 56922 entries in weights',
 'ZRAB2_HUMAN_Beltran_2025_PF00641_9 has 39911 processed sequences but 39912 entries in weights',
 'HERC2_HUMAN_Beltran_2025_PF11515_2555 has 5708 processed sequences but 5712 entries in weights',
 'STAU1_HUMAN_Beltran_2025_PF00035_183 has 13049 processed sequences but 13051 entries in weights',
 'ABL1_HUMAN_Beltran_2025_PF00018_64 has 36167 processed sequences but 36168 entries in weights',
 'SPTA1_HUMAN_Beltran_2025_PF00018_979 has 119539 processed sequences but 119540 entries in weights',
 'TNNC2_HUMAN_Beltran_2025_PF13499_1 has 61155 processed sequences but 61175 entries in weights',
 'VILI_CHICK_Beltran_2025_PF02209_762 has 39304 processed sequences but 39305 entries in weights',
 'LCK_HUMAN_Beltran_2025_PF00018_63 has 109303 processed sequences but 109304 entries in weights',
 'CRGC_HUMAN_Beltran_2025_PF00030_91 has 50025 processed sequences but 50028 entries in weights',
 'CRGB_HUMAN_Beltran_2025_PF00030_87 has 49247 processed sequences but 49252 entries in weights',
 'CRGD_HUMAN_Beltran_2025_PF00030_90 has 50250 processed sequences but 50252 entries in weights',
 'SPTN1_CHICK_Beltran_2025_PF00018_968 has 190722 processed sequences but 190727 entries in weights',
 'HCK_HUMAN_Beltran_2025_PF00018_80 has 95263 processed sequences but 95265 entries in weights',
 'CSPA_ECOLI_Beltran_2025_PF00313_3 has 80766 processed sequences but 80772 entries in weights',
 'TR49C_HUMAN_Beltran_2025_PF00643_87 has 74681 processed sequences but 74688 entries in weights',
 'RARB_HUMAN_Beltran_2025_PF00105_85 has 103542 processed sequences but 103544 entries in weights',
 'CRGA_HUMAN_Beltran_2025_PF00030_85 has 48833 processed sequences but 48836 entries in weights',
 'SRC_HUMAN_Beltran_2025_PF00018_87 has 115218 processed sequences but 115219 entries in weights',
 'XRCC6_HUMAN_Beltran_2025_PF02037_558 has 4048 processed sequences but 4059 entries in weights',
 'NCF1_HUMAN_Beltran_2025_PF00018_157 has 23443 processed sequences but 23444 entries in weights',
 'VAV_HUMAN_Beltran_2025_PF00018_782 has 241990 processed sequences but 241991 entries in weights',
 'YBOX3_HUMAN_Beltran_2025_PF00313_84 has 82268 processed sequences but 82297 entries in weights',
 'UBF1_HUMAN_Beltran_2025_PF00505_408 has 94267 processed sequences but 94274 entries in weights',
 'RXRA_HUMAN_Beltran_2025_PF00105_132 has 103589 processed sequences but 103592 entries in weights',
 'ITH5_CUCMA_Beltran_2025_PF00280_1 has 3346 processed sequences but 3347 entries in weights',
 'NEBU_HUMAN_Beltran_2025_PF14604_6609 has 248682 processed sequences but 248690 entries in weights',
 'RASA1_HUMAN_Beltran_2025_PF00018_281 has 185107 processed sequences but 185109 entries in weights',
 'CRYGS_HUMAN_Beltran_2025_PF00030_96 has 50078 processed sequences but 50081 entries in weights',
 'CSPB_BACSU_Beltran_2025_PF00313_1 has 81760 processed sequences but 81762 entries in weights',
 'RSP5_YEAST_Beltran_2025_PF00397_324 has 178660 processed sequences but 178661 entries in weights',
 'CSPB_BACCL_Beltran_2025_PF00313_1 has 83186 processed sequences but 83188 entries in weights',
 'KDM5C_HUMAN_Beltran_2025_PF00628_319 has 150530 processed sequences but 150533 entries in weights',
 'RL35_HUMAN_Beltran_2025_PF00831_9 has 26668 processed sequences but 26669 entries in weights',
 'CRBB2_HUMAN_Beltran_2025_PF00030_106 has 49615 processed sequences but 49617 entries in weights',
 'NR4A2_HUMAN_Beltran_2025_PF00105_260 has 103533 processed sequences but 103535 entries in weights',
 'YAP1_HUMAN_Beltran_2025_PF00397_226 has 150602 processed sequences but 150603 entries in weights',
 'RBP2_HUMAN_Beltran_2025_PF00641_1478 has 27469 processed sequences but 27471 entries in weights',
 'BLK_HUMAN_Beltran_2025_PF00018_59 has 72915 processed sequences but 72917 entries in weights',
 'MECP2_HUMAN_Beltran_2025_PF01429_91 has 12520 processed sequences but 12521 entries in weights',
 'PMS1_HUMAN_Beltran_2025_PF00505_572 has 120073 processed sequences but 120075 entries in weights',
 'UBE2K_HUMAN_Beltran_2025_PF00627_158 has 34480 processed sequences but 34481 entries in weights',
 'YBOX1_HUMAN_Beltran_2025_PF00313_52 has 52288 processed sequences but 52313 entries in weights',
 'DLG4_HUMAN_Beltran_2025_PF00595_157 has 317509 processed sequences but 317511 entries in weights',
 'DLG4_HUMAN_Beltran_2025_PF00595_60 has 287220 processed sequences but 287222 entries in weights',
 'SARNP_HUMAN_Beltran_2025_PF02037_3 has 39408 processed sequences but 39409 entries in weights',
 'HNRPU_HUMAN_Beltran_2025_PF02037_6 has 38080 processed sequences but 38083 entries in weights',
 'PO4F1_HUMAN_Beltran_2025_PF00157_266 has 23032 processed sequences but 23033 entries in weights',
 'BTK_HUMAN_Beltran_2025_PF00018_215 has 85437 processed sequences but 85438 entries in weights',
 'ITK_HUMAN_Beltran_2025_PF00018_172 has 107704 processed sequences but 107705 entries in weights',
 'PO4F2_HUMAN_Beltran_2025_PF00157_256 has 23158 processed sequences but 23159 entries in weights',
 'CHD3_HUMAN_Beltran_2025_PF00628_374 has 153233 processed sequences but 153236 entries in weights',
 'TRI26_HUMAN_Beltran_2025_PF00643_97 has 81813 processed sequences but 81818 entries in weights',
 'FADD_HUMAN_Beltran_2025_PF01335_1 has 6390 processed sequences but 6391 entries in weights',
 'TIF1B_HUMAN_Beltran_2025_PF00628_620 has 155282 processed sequences but 155283 entries in weights',
 'MPP3_HUMAN_Beltran_2025_PF00595_132 has 28867 processed sequences but 28870 entries in weights',
 'SNTA1_HUMAN_Beltran_2025_PF00595_79 has 226436 processed sequences but 226442 entries in weights',
 'SQSTM_HUMAN_Beltran_2025_PF00569_120 has 50801 processed sequences but 50802 entries in weights',
 'PIN1_HUMAN_Beltran_2025_PF00397_1 has 173855 processed sequences but 173858 entries in weights',
 'SPTN1_HUMAN_Beltran_2025_PF13499_2327 has 15251 processed sequences but 15252 entries in weights',
 'SAFB2_HUMAN_Beltran_2025_PF02037_27 has 39900 processed sequences but 39902 entries in weights',
 'SCRIB_HUMAN_Beltran_2025_PF00595_857 has 266539 processed sequences but 266545 entries in weights',
 'FHL2_HUMAN_Beltran_2025_PF00412_38 has 225354 processed sequences but 225362 entries in weights',
 'CHD4_HUMAN_Beltran_2025_PF00628_365 has 154123 processed sequences but 154126 entries in weights',
 'CHD4_HUMAN_Beltran_2025_PF00628_444 has 151286 processed sequences but 151289 entries in weights',
 'PO4F3_HUMAN_Beltran_2025_PF00157_185 has 23152 processed sequences but 23153 entries in weights',
 'SAFB1_HUMAN_Beltran_2025_PF02037_26 has 17104 processed sequences but 17106 entries in weights',
 'ITSN1_HUMAN_Beltran_2025_PF00018_909 has 193976 processed sequences but 193984 entries in weights',
 'PKN1_HUMAN_Beltran_2025_PF02185_129 has 16930 processed sequences but 16931 entries in weights',
 'HNRL2_HUMAN_Beltran_2025_PF02037_1 has 39111 processed sequences but 39114 entries in weights',
 'MEX3C_HUMAN_Beltran_2025_PF00013_325 has 151453 processed sequences but 151454 entries in weights',
 'TCRGL_HUMAN_Beltran_2025_PF01846_448 has 18775 processed sequences but 18776 entries in weights',
 'SNTA1_MOUSE_Beltran_2025_PF00595_80 has 374534 processed sequences but 374538 entries in weights',
 'DNMBP_HUMAN_Beltran_2025_PF00018_146 has 236882 processed sequences but 236885 entries in weights',
 'DNMBP_HUMAN_Beltran_2025_PF00018_242 has 257149 processed sequences but 257154 entries in weights',
 'DNJB7_HUMAN_Beltran_2025_PF00226_3 has 80746 processed sequences but 80747 entries in weights',
 'MAGI2_HUMAN_Beltran_2025_PF00595_774 has 389556 processed sequences but 389557 entries in weights',
 'FCSD1_HUMAN_Beltran_2025_PF14604_467 has 20637 processed sequences but 20639 entries in weights',
 'CCAR1_HUMAN_Beltran_2025_PF02037_625 has 26780 processed sequences but 26781 entries in weights',
 'MYCD_HUMAN_Beltran_2025_PF02037_363 has 37526 processed sequences but 37529 entries in weights',
 'NEIL3_HUMAN_Beltran_2025_PF00641_316 has 12369 processed sequences but 12370 entries in weights',
 'SP7_HUMAN_Beltran_2025_PF00096_325 has 112835 processed sequences but 112837 entries in weights',
 'CHD5_HUMAN_Beltran_2025_PF00628_338 has 152112 processed sequences but 152115 entries in weights',
 'CHD5_HUMAN_Beltran_2025_PF00628_411 has 148532 processed sequences but 148535 entries in weights',
 'PARD3_HUMAN_Beltran_2025_PF00595_457 has 299053 processed sequences but 299059 entries in weights',
 'PAR3L_HUMAN_Beltran_2025_PF00595_380 has 336025 processed sequences but 336032 entries in weights',
 'CNKR2_HUMAN_Beltran_2025_PF00536_9 has 34216 processed sequences but 34217 entries in weights',
 'DLG3_HUMAN_Beltran_2025_PF00595_222 has 311423 processed sequences but 311427 entries in weights',
 'MRTFA_HUMAN_Beltran_2025_PF02037_341 has 41084 processed sequences but 41086 entries in weights',
 'TRI44_HUMAN_Beltran_2025_PF00643_174 has 78816 processed sequences but 78828 entries in weights',
 'CALL4_HUMAN_Beltran_2025_PF13499_123 has 75025 processed sequences but 75028 entries in weights',
 'CALL4_HUMAN_Beltran_2025_PF13499_48 has 53992 processed sequences but 53999 entries in weights',
 'FUBP3_HUMAN_Beltran_2025_PF00013_75 has 103954 processed sequences but 103956 entries in weights',
 'ITCH_HUMAN_Beltran_2025_PF00397_428 has 115306 processed sequences but 115307 entries in weights',
 'ITCH_HUMAN_Beltran_2025_PF00397_474 has 86328 processed sequences but 86334 entries in weights',
 'NED4L_HUMAN_Beltran_2025_PF00397_184 has 121984 processed sequences but 121985 entries in weights',
 'NED4L_HUMAN_Beltran_2025_PF00397_381 has 181503 processed sequences but 181506 entries in weights',
 'MAGI1_HUMAN_Beltran_2025_PF00397_294 has 153629 processed sequences but 153630 entries in weights',
 'MAGI1_HUMAN_Beltran_2025_PF00397_352 has 120289 processed sequences but 120290 entries in weights',
 'ERBIN_HUMAN_Beltran_2025_PF00595_1321 has 183487 processed sequences but 183488 entries in weights',
 'GA2L1_HUMAN_Beltran_2025_PF02187_209 has 29647 processed sequences but 29648 entries in weights',
 'HNRL1_HUMAN_Beltran_2025_PF02037_1 has 41160 processed sequences but 41164 entries in weights',
 'PACN1_HUMAN_Beltran_2025_PF14604_387 has 15071 processed sequences but 15072 entries in weights',
 'SETD2_HUMAN_Beltran_2025_PF00397_2382 has 102008 processed sequences but 102010 entries in weights',
 'TRIM6_HUMAN_Beltran_2025_PF00643_93 has 79397 processed sequences but 79403 entries in weights',
 'WWTR1_HUMAN_Beltran_2025_PF00397_116 has 121198 processed sequences but 121199 entries in weights',
 'RNF32_HUMAN_Beltran_2025_PF00612_189 has 33880 processed sequences but 33883 entries in weights',
 'P63_HUMAN_Beltran_2025_PF07647_545 has 130259 processed sequences but 130263 entries in weights',
 'TDRD3_HUMAN_Beltran_2025_PF00567_554 has 41835 processed sequences but 41836 entries in weights',
 'KANL2_HUMAN_Beltran_2025_PF13891_28 has 3347 processed sequences but 3348 entries in weights',
 'HM20A_HUMAN_Beltran_2025_PF00505_104 has 117836 processed sequences but 117839 entries in weights',
 'TRI36_HUMAN_Beltran_2025_PF00643_208 has 46294 processed sequences but 46296 entries in weights',
 'SLTM_HUMAN_Beltran_2025_PF02037_19 has 27220 processed sequences but 27223 entries in weights',
 'HECW2_HUMAN_Beltran_2025_PF00397_800 has 167840 processed sequences but 167841 entries in weights',
 'RERE_HUMAN_Beltran_2025_PF00320_502 has 63576 processed sequences but 63579 entries in weights',
 'ZO2_HUMAN_Beltran_2025_PF00595_26 has 115990 processed sequences but 115991 entries in weights',
 'MKRN1_HUMAN_Beltran_2025_PF00642_89 has 33029 processed sequences but 33030 entries in weights',
 'BAZ2B_HUMAN_Beltran_2025_PF00628_1927 has 142479 processed sequences but 142482 entries in weights',
 'RCOR1_HUMAN_Beltran_2025_PF00249_383 has 30152 processed sequences but 30154 entries in weights',
 'SHRM4_HUMAN_Beltran_2025_PF00595_7 has 38426 processed sequences but 38428 entries in weights',
 'PACN2_HUMAN_Beltran_2025_PF00018_428 has 223388 processed sequences but 223391 entries in weights',
 'PZRN3_HUMAN_Beltran_2025_PF00595_244 has 207132 processed sequences but 207136 entries in weights',
 'YBOX2_HUMAN_Beltran_2025_PF00313_86 has 35203 processed sequences but 35232 entries in weights',
 'GRIP1_HUMAN_Beltran_2025_PF00595_666 has 237717 processed sequences but 237718 entries in weights',
 'CD2AP_HUMAN_Beltran_2025_PF00018_271 has 246721 processed sequences but 246727 entries in weights',
 'CD2AP_HUMAN_Beltran_2025_PF14604_109 has 101879 processed sequences but 101884 entries in weights',
 'NCOR2_HUMAN_Beltran_2025_PF00249_613 has 57495 processed sequences but 57496 entries in weights',
 'USH1C_HUMAN_Beltran_2025_PF00595_207 has 123237 processed sequences but 123241 entries in weights']

In [8]:
protein_list = [a.split()[0] for a in issues_list]
print(protein_list)

['WWP2_HUMAN_Beltran_2025_PF00397_440', 'ODPX_HUMAN_Beltran_2025_PF02817_181', 'DVL1_HUMAN_Beltran_2025_PF00595_246', 'TCRG1_HUMAN_Beltran_2025_PF01846_645', 'NPHP1_HUMAN_Beltran_2025_PF00018_152', 'TRI18_HUMAN_Beltran_2025_PF00643_172', 'P73_HUMAN_Beltran_2025_PF07647_487', 'LDB3_HUMAN_Beltran_2025_PF00595_1', 'FLNB_HUMAN_Beltran_2025_PF00630_1423', 'FLNB_HUMAN_Beltran_2025_PF00630_2109', 'FLNB_HUMAN_Beltran_2025_PF00630_2289', 'CSDE1_HUMAN_Beltran_2025_PF00313_184', 'CSDE1_HUMAN_Beltran_2025_PF00313_23', 'MPDZ_HUMAN_Beltran_2025_PF00595_1860', 'MPDZ_HUMAN_Beltran_2025_PF00595_372', 'SASH1_HUMAN_Beltran_2025_PF00536_630', 'ABLM3_HUMAN_Beltran_2025_PF00412_149', 'ABLM3_HUMAN_Beltran_2025_PF00412_210', 'ZRAB2_HUMAN_Beltran_2025_PF00641_9', 'HERC2_HUMAN_Beltran_2025_PF11515_2555', 'STAU1_HUMAN_Beltran_2025_PF00035_183', 'ABL1_HUMAN_Beltran_2025_PF00018_64', 'SPTA1_HUMAN_Beltran_2025_PF00018_979', 'TNNC2_HUMAN_Beltran_2025_PF13499_1', 'VILI_CHICK_Beltran_2025_PF02209_762', 'LCK_HUMAN_Beltran_2025_PF00018_63', 'CRGC_HUMAN_Beltran_2025_PF00030_91', 'CRGB_HUMAN_Beltran_2025_PF00030_87', 'CRGD_HUMAN_Beltran_2025_PF00030_90', 'SPTN1_CHICK_Beltran_2025_PF00018_968', 'HCK_HUMAN_Beltran_2025_PF00018_80', 'CSPA_ECOLI_Beltran_2025_PF00313_3', 'TR49C_HUMAN_Beltran_2025_PF00643_87', 'RARB_HUMAN_Beltran_2025_PF00105_85', 'CRGA_HUMAN_Beltran_2025_PF00030_85', 'SRC_HUMAN_Beltran_2025_PF00018_87', 'XRCC6_HUMAN_Beltran_2025_PF02037_558', 'NCF1_HUMAN_Beltran_2025_PF00018_157', 'VAV_HUMAN_Beltran_2025_PF00018_782', 'YBOX3_HUMAN_Beltran_2025_PF00313_84', 'UBF1_HUMAN_Beltran_2025_PF00505_408', 'RXRA_HUMAN_Beltran_2025_PF00105_132', 'ITH5_CUCMA_Beltran_2025_PF00280_1', 'NEBU_HUMAN_Beltran_2025_PF14604_6609', 'RASA1_HUMAN_Beltran_2025_PF00018_281', 'CRYGS_HUMAN_Beltran_2025_PF00030_96', 'CSPB_BACSU_Beltran_2025_PF00313_1', 'RSP5_YEAST_Beltran_2025_PF00397_324', 'CSPB_BACCL_Beltran_2025_PF00313_1', 'KDM5C_HUMAN_Beltran_2025_PF00628_319', 'RL35_HUMAN_Beltran_2025_PF00831_9', 'CRBB2_HUMAN_Beltran_2025_PF00030_106', 'NR4A2_HUMAN_Beltran_2025_PF00105_260', 'YAP1_HUMAN_Beltran_2025_PF00397_226', 'RBP2_HUMAN_Beltran_2025_PF00641_1478', 'BLK_HUMAN_Beltran_2025_PF00018_59', 'MECP2_HUMAN_Beltran_2025_PF01429_91', 'PMS1_HUMAN_Beltran_2025_PF00505_572', 'UBE2K_HUMAN_Beltran_2025_PF00627_158', 'YBOX1_HUMAN_Beltran_2025_PF00313_52', 'DLG4_HUMAN_Beltran_2025_PF00595_157', 'DLG4_HUMAN_Beltran_2025_PF00595_60', 'SARNP_HUMAN_Beltran_2025_PF02037_3', 'HNRPU_HUMAN_Beltran_2025_PF02037_6', 'PO4F1_HUMAN_Beltran_2025_PF00157_266', 'BTK_HUMAN_Beltran_2025_PF00018_215', 'ITK_HUMAN_Beltran_2025_PF00018_172', 'PO4F2_HUMAN_Beltran_2025_PF00157_256', 'CHD3_HUMAN_Beltran_2025_PF00628_374', 'TRI26_HUMAN_Beltran_2025_PF00643_97', 'FADD_HUMAN_Beltran_2025_PF01335_1', 'TIF1B_HUMAN_Beltran_2025_PF00628_620', 'MPP3_HUMAN_Beltran_2025_PF00595_132', 'SNTA1_HUMAN_Beltran_2025_PF00595_79', 'SQSTM_HUMAN_Beltran_2025_PF00569_120', 'PIN1_HUMAN_Beltran_2025_PF00397_1', 'SPTN1_HUMAN_Beltran_2025_PF13499_2327', 'SAFB2_HUMAN_Beltran_2025_PF02037_27', 'SCRIB_HUMAN_Beltran_2025_PF00595_857', 'FHL2_HUMAN_Beltran_2025_PF00412_38', 'CHD4_HUMAN_Beltran_2025_PF00628_365', 'CHD4_HUMAN_Beltran_2025_PF00628_444', 'PO4F3_HUMAN_Beltran_2025_PF00157_185', 'SAFB1_HUMAN_Beltran_2025_PF02037_26', 'ITSN1_HUMAN_Beltran_2025_PF00018_909', 'PKN1_HUMAN_Beltran_2025_PF02185_129', 'HNRL2_HUMAN_Beltran_2025_PF02037_1', 'MEX3C_HUMAN_Beltran_2025_PF00013_325', 'TCRGL_HUMAN_Beltran_2025_PF01846_448', 'SNTA1_MOUSE_Beltran_2025_PF00595_80', 'DNMBP_HUMAN_Beltran_2025_PF00018_146', 'DNMBP_HUMAN_Beltran_2025_PF00018_242', 'DNJB7_HUMAN_Beltran_2025_PF00226_3', 'MAGI2_HUMAN_Beltran_2025_PF00595_774', 'FCSD1_HUMAN_Beltran_2025_PF14604_467', 'CCAR1_HUMAN_Beltran_2025_PF02037_625', 'MYCD_HUMAN_Beltran_2025_PF02037_363', 'NEIL3_HUMAN_Beltran_2025_PF00641_316', 'SP7_HUMAN_Beltran_2025_PF00096_325', 'CHD5_HUMAN_Beltran_2025_PF00628_338', 'CHD5_HUMAN_Beltran_2025_PF00628_411', 'PARD3_HUMAN_Beltran_2025_PF00595_457', 'PAR3L_HUMAN_Beltran_2025_PF00595_380', 'CNKR2_HUMAN_Beltran_2025_PF00536_9', 'DLG3_HUMAN_Beltran_2025_PF00595_222', 'MRTFA_HUMAN_Beltran_2025_PF02037_341', 'TRI44_HUMAN_Beltran_2025_PF00643_174', 'CALL4_HUMAN_Beltran_2025_PF13499_123', 'CALL4_HUMAN_Beltran_2025_PF13499_48', 'FUBP3_HUMAN_Beltran_2025_PF00013_75', 'ITCH_HUMAN_Beltran_2025_PF00397_428', 'ITCH_HUMAN_Beltran_2025_PF00397_474', 'NED4L_HUMAN_Beltran_2025_PF00397_184', 'NED4L_HUMAN_Beltran_2025_PF00397_381', 'MAGI1_HUMAN_Beltran_2025_PF00397_294', 'MAGI1_HUMAN_Beltran_2025_PF00397_352', 'ERBIN_HUMAN_Beltran_2025_PF00595_1321', 'GA2L1_HUMAN_Beltran_2025_PF02187_209', 'HNRL1_HUMAN_Beltran_2025_PF02037_1', 'PACN1_HUMAN_Beltran_2025_PF14604_387', 'SETD2_HUMAN_Beltran_2025_PF00397_2382', 'TRIM6_HUMAN_Beltran_2025_PF00643_93', 'WWTR1_HUMAN_Beltran_2025_PF00397_116', 'RNF32_HUMAN_Beltran_2025_PF00612_189', 'P63_HUMAN_Beltran_2025_PF07647_545', 'TDRD3_HUMAN_Beltran_2025_PF00567_554', 'KANL2_HUMAN_Beltran_2025_PF13891_28', 'HM20A_HUMAN_Beltran_2025_PF00505_104', 'TRI36_HUMAN_Beltran_2025_PF00643_208', 'SLTM_HUMAN_Beltran_2025_PF02037_19', 'HECW2_HUMAN_Beltran_2025_PF00397_800', 'RERE_HUMAN_Beltran_2025_PF00320_502', 'ZO2_HUMAN_Beltran_2025_PF00595_26', 'MKRN1_HUMAN_Beltran_2025_PF00642_89', 'BAZ2B_HUMAN_Beltran_2025_PF00628_1927', 'RCOR1_HUMAN_Beltran_2025_PF00249_383', 'SHRM4_HUMAN_Beltran_2025_PF00595_7', 'PACN2_HUMAN_Beltran_2025_PF00018_428', 'PZRN3_HUMAN_Beltran_2025_PF00595_244', 'YBOX2_HUMAN_Beltran_2025_PF00313_86', 'GRIP1_HUMAN_Beltran_2025_PF00595_666', 'CD2AP_HUMAN_Beltran_2025_PF00018_271', 'CD2AP_HUMAN_Beltran_2025_PF14604_109', 'NCOR2_HUMAN_Beltran_2025_PF00249_613', 'USH1C_HUMAN_Beltran_2025_PF00595_207']

In [9]:
len(protein_list)

145

In [15]:
wt = np.load('EVCouplings/output/Beltran_Lehner_2025/weights/ODPX_HUMAN_Beltran_2025_PF02817_181_theta_0.8_b1.05.npy')
wt.shape[0]

1448

In [14]:
",".join(str(c) for c in df.index[df['DMS_id'].isin(protein_list)])

'6,7,10,12,21,24,25,41,44,45,46,54,55,61,62,65,66,67,72,77,81,84,87,88,90,96,99,101,102,103,107,110,111,119,122,125,126,129,135,138,139,140,141,149,150,153,161,174,177,179,180,181,182,187,192,194,198,203,217,221,222,224,228,231,238,247,251,255,256,257,264,266,267,268,271,273,276,277,278,279,285,286,291,293,299,305,306,314,317,318,323,325,337,343,348,356,358,375,376,377,378,380,381,384,387,393,397,399,400,402,403,404,411,412,415,416,417,419,427,429,431,433,435,437,442,446,448,455,458,465,473,474,479,482,484,491,497,500,501,508,509,513,515,516,517'

Should rerun the Tranception with retrieval for all 145 protein sequences, because it also used the weights

TO-DO: can do a PR to the Tranception github repo, add an assertion line of the weights dimension and the processed MSA dimension