# Process all data from the paper
1. Basic checks: directionality
2. Preprocess and subset the data into separate csv files, one for each protein
3. Prep the data for MSA (colabfold and EVCouplings)
4. Visualize the data distribution and find the DMS binarization threshold
5. Map the Uniprot ID to SwissProt ID and save each protein as `DMS_ID.csv`
6. Fill out the [DMS_substitution_internal](https://docs.google.com/spreadsheets/d/1M1dKN0wpvE2sKDt4hwrIsTBS1r1HbBObUxjO4LNOQ64/edit?gid=560024392#gid=560024392) sheet for all domains

In [1]:
import pandas as pd
import csv
import subprocess
import sys

## Load the dataset
\* means stop codon

In [2]:
domainome = pd.read_csv('/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/DMS_assays/raw_data/Beltran_Lehner_2025/SupplementaryTable2.txt', 
                        sep='\t')

In [3]:
domainome.head(10)

,domain_ID,uniprot_ID,aa_seq,wt_aa,position,mut_aa,STOP,input_count_rep1,input_count_rep2,input_count_rep3,output_count_rep1,output_count_rep2,output_count_rep3,mean_input_count,fitness,fitness_sigma,normalized_fitness,normalized_fitness_sigma,quality_rank
0,A0A2R8Y422_PF00240_2,A0A2R8Y422,*IFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,*,True,118.0,113.0,62.0,10.0,29.0,2.0,97.66667,0.030945,0.014885,-0.819050,0.208478,339
1,A0A2R8Y422_PF00240_2,A0A2R8Y422,AIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,A,False,219.0,277.0,217.0,86.0,225.0,137.0,237.66670,0.069376,0.006673,-0.280790,0.093461,339
2,A0A2R8Y422_PF00240_2,A0A2R8Y422,CIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,C,False,706.0,726.0,459.0,768.0,507.0,616.0,630.33330,0.082052,0.004141,-0.103250,0.057995,339
3,A0A2R8Y422_PF00240_2,A0A2R8Y422,DIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,D,False,407.0,431.0,323.0,508.0,159.0,111.0,387.00000,0.071003,0.005162,-0.258003,0.072296,339
4,A0A2R8Y422_PF00240_2,A0A2R8Y422,EIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,E,False,37.0,56.0,37.0,201.0,102.0,95.0,43.33333,0.116326,0.012085,0.376783,0.169263,339
5,A0A2R8Y422_PF00240_2,A0A2R8Y422,FIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,F,False,264.0,228.0,142.0,334.0,564.0,472.0,211.33330,0.100066,0.006000,0.149047,0.084030,339
6,A0A2R8Y422_PF00240_2,A0A2R8Y422,GIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,G,False,1006.0,1062.0,867.0,852.0,690.0,773.0,978.33330,0.076036,0.003682,-0.187512,0.051568,339
7,A0A2R8Y422_PF00240_2,A0A2R8Y422,HIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,H,False,612.0,695.0,510.0,922.0,326.0,517.0,605.66670,0.081447,0.004220,-0.111728,0.059101,339
8,A0A2R8Y422_PF00240_2,A0A2R8Y422,IIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,I,False,351.0,378.0,228.0,916.0,755.0,883.0,319.00000,0.109426,0.004950,0.280147,0.069333,339
9,A0A2R8Y422_PF00240_2,A0A2R8Y422,KIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2.0,K,False,84.0,85.0,47.0,175.0,236.0,38.0,72.00000,0.102229,0.009503,0.179340,0.133105,339

In [3]:
domainome[domainome['wt_aa'] == domainome['mut_aa']]['normalized_fitness'].value_counts()

Series([], Name: normalized_fitness, dtype: int64)

No synonymous variants

## Check on the directionality of the `normalized_fitness` column:
1. check the value: if negative, then -1 is less fit, though the numbers aren't normalized to 1. The mean/median is higher when it's not a stop codon. So the directionality is correct
2. check the experiments
- Fig 1a and b, `variants that cause unfolding/degradation of the target domain result in a decrease in concentration in the cell, leading to impaired cell growth`
- the data table (above), for those with a stop codon, the input values (read counts usually) are higher than the output values
- Fig 2, there is a heatmap bar for normalized fitness

In [4]:
domainome[domainome['mut_aa'] == "*"]['normalized_fitness'].describe()

count    26848.000000
mean        -1.082122
std          0.439326
min         -5.297542
25%         -1.221094
50%         -1.007839
75%         -0.847451
max          1.475415
Name: normalized_fitness, dtype: float64

In [5]:
domainome[domainome['mut_aa'] != "*"]['normalized_fitness'].describe()

count    536686.000000
mean         -0.280223
std           0.340482
min          -4.122925
25%          -0.507694
50%          -0.187892
75%          -0.032637
max           2.052570
Name: normalized_fitness, dtype: float64

## Data preprocessing:
1. remove rows where the `position` is NA or where the `normalized_fitness` is NA
2. cast `position`, input/output counts as `int`
3. remove all the stop codons
4. subset the dataframe based on unique domain_IDs because multiple domains can map to the same Uniprot ID

In [7]:
domainome.dtypes

domain_ID                    object
uniprot_ID                   object
aa_seq                       object
wt_aa                        object
position                    float64
mut_aa                       object
STOP                         object
input_count_rep1            float64
input_count_rep2            float64
input_count_rep3            float64
output_count_rep1           float64
output_count_rep2           float64
output_count_rep3           float64
mean_input_count            float64
fitness                     float64
fitness_sigma               float64
normalized_fitness          float64
normalized_fitness_sigma    float64
quality_rank                  int64
dtype: object

In [3]:
domainome = domainome[(domainome['position'].notnull()) & (domainome['normalized_fitness'].notnull())]
dtype={'position': int, 
       'input_count_rep1': int, 
       'input_count_rep2': int, 
       'input_count_rep3': int, 
       'output_count_rep1': int,
       'output_count_rep2': int,
       'output_count_rep3': int}
domainome = domainome.astype(dtype)

In [5]:
domainome['domain_ID'].nunique()

522

In [6]:
domainome['uniprot_ID'].nunique()

434

In [4]:
domain_id_list = list(domainome['domain_ID'].drop_duplicates())
idmapping_csv = '/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/DMS_assays/processed_data/Beltran_Lehner_2025/idmapping_2025_06_10.csv'
with open(idmapping_csv, mode='r') as f_in:
    reader = csv.reader(f_in)
    idmapping_dict = {rows[0]:rows[1] for rows in reader}

In [5]:
def make_dms_id(domain_id):
    protein, domain, idx = domain_id.split('_')
    if protein in idmapping_dict:
        dms_id = "_".join([idmapping_dict[protein], "Beltran_2025", domain, idx])
    else:
        dms_id = "_".join([domain_id, "Beltran_2025"])
    return dms_id

In [7]:
for domain_id in domain_id_list:
    df = domainome[(domainome["domain_ID"] == domain_id) & (domainome['mut_aa'] != "*")]
    dms_id = make_dms_id(domain_id)
    df.to_csv(f"/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/DMS_assays/processed_data/Beltran_Lehner_2025/{dms_id}.csv", index=False)

### TO-DO
- ~rename the csv files based on the id mapping below~
- clean up the .tmp files

For PRIMO project inclusion
- Double check how many mutations for each domain? Looks like singles only? Read the paper to check
- Are there indels? **No**
- Figure out how they calculate all the scores
- **Is normalized fitness direction correct? 1 being more fit, -1 being less fit**
- **Do we want to filter out the stop codon mutants?**
  Leaning toward yes, because stop codons can lead to indel mutants (or large deletions), these are removed in PG1.
  Otherwise, we have to research how to better represent the stop codons for different models

**TO DO** fill in the data description here (copied from the PG2 meeting blog)

Next step:

- Compute MSAs and PDBs (AF2 predictions of the structure) for 500+ domains - look at domain-specific assay
- Use ColabFold alignments - for EVE, can miss chunks in PTEN and the number of sequences is a lot lower (<1 day)
- Or if use EVCouplings (short sequences with low bitscores will go OOM), it may take longer
- Some papers are reporting better (GEM, PoET) performance with ColabFold MSAs (no need to filter out distant sequences, Aaron added a column of coverage filter) than EVCouplings MSAs (need to filter out distant sequences) - JackHammer tends to retain these distant sequences, only helpful for alignment-based models
- Hard to standardize MSAs for different models
- Need to decide which MSA we want going forward
- AF2 will be based on the same MSA (AF2 predictions give structures and MSAs)

## MSA data prep (colabfold and EVCouplings)
1. To run MSA using colabfold: Generate the wild-type domain sequence and compare with [the original sequence generated by Aaron](/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/ColabFold/Beltran_Lehner_2025/beltran_domains.fa)

In [9]:
with open('/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/ColabFold/Beltran_Lehner_2025/beltran_domains_filtered.fa', 'w') as f_out:
    for domain_id in domain_id_list:
        df = domainome[domainome["domain_ID"] == domain_id]
        fasta_id = domain_id
        offset = int(domain_id.split("_")[-1])
        aa_seq_list = list(df['aa_seq'].iloc[0])
        # print(len(aa_seq_list))
        position = df['position'].iloc[0] - offset
        # print(position)
        wt_aa = df['wt_aa'].iloc[0]
        aa_seq_list[position] = wt_aa
        aa_seq = "".join(aa_seq_list)
        f_out.write(f">{fasta_id}\n{aa_seq}\n")
        continue

To score AIDO (one of the baselines), generate a customized fasta file

In [6]:
out_dir = '/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/DMS_assays/processed_data/Beltran_Lehner_2025/AIDO_fasta/'
for domain_id in domain_id_list:
    df = domainome[domainome["domain_ID"] == domain_id]
    seq_len = len(df['aa_seq'].iloc[0])
    dms_id = make_dms_id(domain_id)

    offset = int(domain_id.split("_")[-1])
    aa_seq_list = list(df['aa_seq'].iloc[0])
    # print(len(aa_seq_list))
    position = df['position'].iloc[0] - offset
    # print(position)
    wt_aa = df['wt_aa'].iloc[0]
    aa_seq_list[position] = wt_aa
    aa_seq = "".join(aa_seq_list)
    
    with open(out_dir + dms_id + '.fasta', 'w') as f_out:
        f_out.write(f">{dms_id} 1-{seq_len}\n{aa_seq}\n")
    continue

In [13]:
df = pd.read_csv('/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/EVCouplings/output/Beltran_Lehner_2025/temp_ref_file.csv')
df.columns
# list(df['DMS_id'])

Index(['DMS_id', 'MSA_bitscore', 'MSA_num_seqs', 'MSA_perc_cov', 'MSA_num_cov',
       'MSA_N_eff', 'MSA_Neff_L', 'MSA_Neff_L_category', 'weight_file_name',
       'MSA_filename', 'EVCouplings_model_filename', 'target_aa_seq',
       'DMS_filename', 'offset', 'seq_len', 'pdb_file', 'UniProt_ID',
       'MSA_start', 'MSA_end', 'MSA_len', 'MSA_theta', 'taxon',
       'source_organism', 'includes_multiple_mutants', 'DMS_wildtype_score',
       'first_author', 'coarse_selection_type'],
      dtype='object')

In [10]:
!diff /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/ColabFold/Beltran_Lehner_2025/beltran_domains_filtered.fa /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/ColabFold/Beltran_Lehner_2025/beltran_domains.fa

1044a1045
>

Get the target sequence into a .csv for model scoring

In [9]:
with open('/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/EVCouplings/output/Beltran_Lehner_2025/target_seq.csv', 'w') as f_out:
    f_out.write("DMS_id,target_seq\n")
    for domain_id in domain_id_list:
        df = domainome[domainome["domain_ID"] == domain_id]
        dms_id = make_dms_id(domain_id)
        offset = int(domain_id.split("_")[-1])
        aa_seq_list = list(df['aa_seq'].iloc[0])
        position = df['position'].iloc[0] - offset
        wt_aa = df['wt_aa'].iloc[0]
        aa_seq_list[position] = wt_aa
        aa_seq = "".join(aa_seq_list)
        f_out.write(f"{dms_id},{aa_seq}\n")
        continue

#### Summary of colabfold data prep: 
Check the sequences with Aaron's [on AWS](/home/ubuntu/beltran_domains) - **the sequences are the same**

2. Generate the file to examine number of unique domains, as requested by Debbie on March 31

Column names: UniProt ID, PFID, AA sequence, length, the number of sequences

In [8]:
domainome.head(10)

,domain_ID,uniprot_ID,aa_seq,wt_aa,position,mut_aa,STOP,input_count_rep1,input_count_rep2,input_count_rep3,output_count_rep1,output_count_rep2,output_count_rep3,mean_input_count,fitness,fitness_sigma,normalized_fitness,normalized_fitness_sigma,quality_rank
0,A0A2R8Y422_PF00240_2,A0A2R8Y422,*IFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2,*,True,118,113,62,10,29,2,97.66667,0.030945,0.014885,-0.819050,0.208478,339
1,A0A2R8Y422_PF00240_2,A0A2R8Y422,AIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2,A,False,219,277,217,86,225,137,237.66670,0.069376,0.006673,-0.280790,0.093461,339
2,A0A2R8Y422_PF00240_2,A0A2R8Y422,CIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2,C,False,706,726,459,768,507,616,630.33330,0.082052,0.004141,-0.103250,0.057995,339
3,A0A2R8Y422_PF00240_2,A0A2R8Y422,DIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2,D,False,407,431,323,508,159,111,387.00000,0.071003,0.005162,-0.258003,0.072296,339
4,A0A2R8Y422_PF00240_2,A0A2R8Y422,EIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2,E,False,37,56,37,201,102,95,43.33333,0.116326,0.012085,0.376783,0.169263,339
5,A0A2R8Y422_PF00240_2,A0A2R8Y422,FIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2,F,False,264,228,142,334,564,472,211.33330,0.100066,0.006000,0.149047,0.084030,339
6,A0A2R8Y422_PF00240_2,A0A2R8Y422,GIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2,G,False,1006,1062,867,852,690,773,978.33330,0.076036,0.003682,-0.187512,0.051568,339
7,A0A2R8Y422_PF00240_2,A0A2R8Y422,HIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2,H,False,612,695,510,922,326,517,605.66670,0.081447,0.004220,-0.111728,0.059101,339
8,A0A2R8Y422_PF00240_2,A0A2R8Y422,IIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2,I,False,351,378,228,916,755,883,319.00000,0.109427,0.004950,0.280147,0.069333,339
9,A0A2R8Y422_PF00240_2,A0A2R8Y422,KIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2,K,False,84,85,47,175,236,38,72.00000,0.102229,0.009503,0.179340,0.133105,339

Parse uniprot_ID and PFID and wild type AA sequence

In [5]:
with open('/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/DMS_assays/processed_data/Beltran_Lehner_2025/summary.tmp', 'w') as f_out:
    for domain_id in domain_id_list:
        df = domainome[domainome["domain_ID"] == domain_id]
        uniprot_id, pfid, _ = domain_id.split('_')
        offset = int(domain_id.split("_")[-1])
        aa_seq_list = list(df['aa_seq'].iloc[0])
        position = df['position'].iloc[0] - offset
        wt_aa = df['wt_aa'].iloc[0]
        aa_seq_list[position] = wt_aa
        aa_seq = "".join(aa_seq_list)
        aa_len = len(aa_seq)
        start_idx = offset
        end_idx = offset + aa_len - 1
        domain_list = f'({pfid}, {start_idx}, {end_idx})'
        f_out.write("\t".join([uniprot_id, aa_seq, domain_list])+'\n')
        continue

Count the number of sequences under a domain (usually in different uniprot ID)

In [32]:
df = pd.read_csv('/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/DMS_assays/processed_data/Beltran_Lehner_2025/summary.tmp', 
                 sep="\t", names=['uniprot_ID', 'wt_aa_seq', 'domain_list'])
df = df.sort_values('PFID')
df.to_csv('/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/DMS_assays/processed_data/Beltran_Lehner_2025/summary.tsv')
# clean_df = df.groupby(["PFID", 'uniprot_ID']).count()
# clean_df.to_csv('/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/DMS_assays/processed_data/Beltran_Lehner_2025/summary.tmp.sorted', sep='\t')
# clean_df.drop_duplicates(['wt_aa_seq', 'wt_aa_seq_len']).to_csv('/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/DMS_assays/processed_data/Beltran_Lehner_2025/summary.tmp.sorted', sep='\t')
# df.groupby(["PFID", 'wt_aa_seq']).count()

                                                             uniprot_ID  \
PFID     wt_aa_seq
PF00010  RSTHNEMEKNRRAHLRLCLEKLKGLVPLGPESSRHTTLSLLTKAKLH...           1
         STHNELEKNRRAHLRLCLERLKVLIPLGPDCTRHTTLGLLNKAKAHI...           1
PF00013  GNAVQEIMIPASKAGLVIGKGGETIKQLQERAGVKMVMIQDGPQNTG...           1
         GPIITTQVTIPKDLAGSIIGKGGQRIKQIRHESGASIKIDEPLEGSE...           1
         GQTTVQVRVPYRVVGLVVGPKGATIKRIQQQTHTYIVTPSRDKEPVF...           1
...                                                                 ...
PF18410  GCWSIEHVEQYLGTDELPKNDLITYLQKNADAAFLRHWKLTGTNKSI...           1
PF18694  IRVTEDENDEPIEIPSEDDGTVLLSTVTAQFPGACGLRYRNPVSQCM...           1
rockdoms QETIEVEDEEEARRVAKELRKKGYEVKIERRGNKWHVHRT                     1
         RKWEEIAERLREEFNINPEEAREAVEKAGGNEEEARRIVKKRL                  1
         TTIKVNGQEYTVPLSPEQAAKAAKKRWPDYEVQIHGNTVKVTR                  1

                                                             wt_aa_seq_len
PFID     wt_aa_seq
PF00010  RSTHNEMEKNRRAHLRLCLEKLKGLVPLGPESSRHTTLSLLTKAKLH...              1
         STHNELEKNRRAHLRLCLERLKVLIPLGPDCTRHTTLGLLNKAKAHI...              1
PF00013  GNAVQEIMIPASKAGLVIGKGGETIKQLQERAGVKMVMIQDGPQNTG...              1
         GPIITTQVTIPKDLAGSIIGKGGQRIKQIRHESGASIKIDEPLEGSE...              1
         GQTTVQVRVPYRVVGLVVGPKGATIKRIQQQTHTYIVTPSRDKEPVF...              1
...                                                                    ...
PF18410  GCWSIEHVEQYLGTDELPKNDLITYLQKNADAAFLRHWKLTGTNKSI...              1
PF18694  IRVTEDENDEPIEIPSEDDGTVLLSTVTAQFPGACGLRYRNPVSQCM...              1
rockdoms QETIEVEDEEEARRVAKELRKKGYEVKIERRGNKWHVHRT                        1
         RKWEEIAERLREEFNINPEEAREAVEKAGGNEEEARRIVKKRL                     1
         TTIKVNGQEYTVPLSPEQAAKAAKKRWPDYEVQIHGNTVKVTR                     1

[522 rows x 2 columns]

In [31]:
df['PFID'].nunique()

127

Next steps: get the list of domains and start/stop indices for each target protein

3. Generate the .csv file required for EVCouplings run

In [5]:
with open('/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/EVCouplings/input/Beltran_Lehner_2025/sequences.csv', 'w') as f_out:
    f_out.write(",".join(['UniProt_ID','target_seq','MSA_region','MSA_theta']) + '\n')
    for domain_id in domain_id_list:
        df = domainome[domainome["domain_ID"] == domain_id]
        fasta_id = domain_id
        offset = int(domain_id.split("_")[-1])
        aa_seq_list = list(df['aa_seq'].iloc[0])
        # print(len(aa_seq_list))
        position = df['position'].iloc[0] - offset
        # print(position)
        wt_aa = df['wt_aa'].iloc[0]
        aa_seq_list[position] = wt_aa
        aa_seq = "".join(aa_seq_list)
        f_out.write(f"{fasta_id},{aa_seq},,0.2\n")
        continue

## Visualize the data and find the DMS_binarization_threshold

In [ ]:
import requests
import json
def get_pfam_domains_for_proteins(protein_sequences):
 """Searches for Pfam domains in a dictionary of protein sequences."""
 pfam_domains = {}
 for protein_id, sequence in protein_sequences.items():
     try:
         # Construct the API request URL
         url = f"https://www.ebi.ac.uk/interpro/api/entry/pfam/PF02171/protein/UniProt/{protein_id}"  # Replace PF02171 with the Pfam entry you want to search for
         response = requests.get(url)
         response.raise_for_status()
         data = response.json()
         # Extract the relevant information from the JSON response
         pfam_domains[protein_id] = data
     except requests.exceptions.RequestException as e:
         print(f"Error searching for Pfam domains for {protein_id}: {e}")
 return pfam_domains

## Map the Uniprot ID to SwissProt ID and save each protein as `DMS_ID.csv` (move this to the very front)

Use [this](uniprot.org/id-mapping) mapping website

Write the Uniprot ID to a csv for submission

In [10]:
pd.Series(domainome['uniprot_ID'].unique()).to_csv('/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/DMS_assays/raw_data/Beltran_Lehner_2025/uniprot_id.csv', index=False, header=False)

Load the mapping result (total 434 proteins)
- 3 rocklin domain proteins have no Swiss-Prot (expected)
- 3 others have entries deleted, manually input the most recent Swiss-Prot ID or available TrEMBL ID

In [2]:
mapping_df = pd.read_csv('/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/DMS_assays/raw_data/Beltran_Lehner_2025/idmapping_2025_06_10.tsv', sep="\t")
mapping_df

,From,Entry,Entry Name,Protein names,Organism,Length,Reviewed
0,A0PJY2,A0PJY2,FEZF1_HUMAN,Fez family zinc finger protein 1 (Zinc finger ...,Homo sapiens (Human),475,reviewed
1,A1X283,A1X283,SPD2B_HUMAN,SH3 and PX domain-containing protein 2B (Adapt...,Homo sapiens (Human),911,reviewed
2,A6NK59,A6NK59,ASB14_HUMAN,Ankyrin repeat and SOCS box protein 14 (ASB-14),Homo sapiens (Human),587,reviewed
3,O00308,O00308,WWP2_HUMAN,NEDD4-like E3 ubiquitin-protein ligase WWP2 (E...,Homo sapiens (Human),870,reviewed
4,O00330,O00330,ODPX_HUMAN,"Pyruvate dehydrogenase protein X component, mi...",Homo sapiens (Human),501,reviewed
...,...,...,...,...,...,...,...
423,Q9Y4J8,Q9Y4J8,DTNA_HUMAN,Dystrobrevin alpha (DTN-A) (Alpha-dystrobrevin...,Homo sapiens (Human),743,reviewed
424,Q9Y5K6,Q9Y5K6,CD2AP_HUMAN,CD2-associated protein (Adapter protein CMS) (...,Homo sapiens (Human),639,reviewed
425,Q9Y618,Q9Y618,NCOR2_HUMAN,Nuclear receptor corepressor 2 (N-CoR2) (CTG r...,Homo sapiens (Human),2514,reviewed
426,Q9Y6N9,Q9Y6N9,USH1C_HUMAN,Harmonin (Antigen NY-CO-38/NY-CO-37) (Autoimmu...,Homo sapiens (Human),552,reviewed
427,Q9Y6V0,Q9Y6V0,PCLO_HUMAN,Protein piccolo (Aczonin),Homo sapiens (Human),5142,reviewed

In [3]:
idmapping_dict = mapping_df.set_index('Entry')['Entry Name'].to_dict()

{'A0PJY2': 'FEZF1_HUMAN',
 'A1X283': 'SPD2B_HUMAN',
 'A6NK59': 'ASB14_HUMAN',
 'O00308': 'WWP2_HUMAN',
 'O00330': 'ODPX_HUMAN',
 'O14529': 'CUX2_HUMAN',
 'O14640': 'DVL1_HUMAN',
 'O14776': 'TCRG1_HUMAN',
 'O14813': 'PHX2A_HUMAN',
 'O14901': 'KLF11_HUMAN',
 'O14936': 'CSKP_HUMAN',
 'O15151': 'MDM4_HUMAN',
 'O15259': 'NPHP1_HUMAN',
 'O15265': 'ATX7_HUMAN',
 'O15266': 'SHOX_HUMAN',
 'O15344': 'TRI18_HUMAN',
 'O15350': 'P73_HUMAN',
 'O15405': 'TOX3_HUMAN',
 'O15541': 'R113A_HUMAN',
 'O43167': 'ZBT24_HUMAN',
 'O43186': 'CRX_HUMAN',
 'O43295': 'SRGP3_HUMAN',
 'O43353': 'RIPK2_HUMAN',
 'O43374': 'RASL2_HUMAN',
 'O43395': 'PRPF3_HUMAN',
 'O43586': 'PPIP1_HUMAN',
 'O60281': 'ZN292_HUMAN',
 'O60293': 'ZC3H1_HUMAN',
 'O60341': 'KDM1A_HUMAN',
 'O60481': 'ZIC3_HUMAN',
 'O60885': 'BRD4_HUMAN',
 'O75112': 'LDB3_HUMAN',
 'O75360': 'PROP1_HUMAN',
 'O75366': 'AVIL_HUMAN',
 'O75369': 'FLNB_HUMAN',
 'O75382': 'TRIM3_HUMAN',
 'O75400': 'PR40A_HUMAN',
 'O75478': 'TAD2A_HUMAN',
 'O75534': 'CSDE1_HUMAN',
 'O75554': 'WBP4_HUMAN',
 'O75808': 'CAN15_HUMAN',
 'O75953': 'DNJB5_HUMAN',
 'O75970': 'MPDZ_HUMAN',
 'O94830': 'DDHD2_HUMAN',
 'O94885': 'SASH1_HUMAN',
 'O94929': 'ABLM3_HUMAN',
 'O94993': 'SOX30_HUMAN',
 'O95076': 'ALX3_HUMAN',
 'O95155': 'UBE4B_HUMAN',
 'O95218': 'ZRAB2_HUMAN',
 'O95267': 'GRP1_HUMAN',
 'O95343': 'SIX3_HUMAN',
 'O95409': 'ZIC2_HUMAN',
 'O95475': 'SIX6_HUMAN',
 'O95714': 'HERC2_HUMAN',
 'O95718': 'ERR2_HUMAN',
 'O95789': 'ZMYM6_HUMAN',
 'O95793': 'STAU1_HUMAN',
 'O95817': 'BAG3_HUMAN',
 'O95835': 'LATS1_HUMAN',
 'P00519': 'ABL1_HUMAN',
 'P01053': 'ICI2_HORVU',
 'P02417': 'RL9_GEOSE',
 'P02549': 'SPTA1_HUMAN',
 'P02585': 'TNNC2_HUMAN',
 'P02633': 'S100G_BOVIN',
 'P02640': 'VILI_CHICK',
 'P03034': 'RPC1_LAMBD',
 'P04049': 'RAF1_HUMAN',
 'P04150': 'GCR_HUMAN',
 'P05813': 'CRBA1_HUMAN',
 'P06239': 'LCK_HUMAN',
 'P06241': 'FYN_HUMAN',
 'P07315': 'CRGC_HUMAN',
 'P07316': 'CRGB_HUMAN',
 'P07320': 'CRGD_HUMAN',
 'P07751': 'SPTN1_CHICK',
 'P07814': 'SYEP_HUMAN',
 'P08151': 'GLI1_HUMAN',
 'P08235': 'MCR_HUMAN',
 'P08631': 'HCK_HUMAN',
 'P09086': 'PO2F2_HUMAN',
 'P09327': 'VILI_HUMAN',
 'P0A9X9': 'CSPA_ECOLI',
 'P0CI26': 'TR49C_HUMAN',
 'P10070': 'GLI2_HUMAN',
 'P10071': 'GLI3_HUMAN',
 'P10242': 'MYB_HUMAN',
 'P10275': 'ANDR_HUMAN',
 'P10398': 'ARAF_HUMAN',
 'P10589': 'COT1_HUMAN',
 'P10826': 'RARB_HUMAN',
 'P11182': 'ODB2_HUMAN',
 'P11308': 'ERG_HUMAN',
 'P11844': 'CRGA_HUMAN',
 'P11961': 'ODP2_GEOSE',
 'P12081': 'HARS1_HUMAN',
 'P12931': 'SRC_HUMAN',
 'P12956': 'XRCC6_HUMAN',
 'P13796': 'PLSL_HUMAN',
 'P13984': 'T2FB_HUMAN',
 'P14598': 'NCF1_HUMAN',
 'P14653': 'HXB1_HUMAN',
 'P14859': 'PO2F1_HUMAN',
 'P14921': 'ETS1_HUMAN',
 'P15056': 'BRAF_HUMAN',
 'P15498': 'VAV_HUMAN',
 'P16157': 'ANK1_HUMAN',
 'P16885': 'PLCG2_HUMAN',
 'P16989': 'YBOX3_HUMAN',
 'P17480': 'UBF1_HUMAN',
 'P19793': 'RXRA_HUMAN',
 'P19873': 'ITH5_CUCMA',
 'P19878': 'NCF2_HUMAN',
 'P20264': 'PO3F3_HUMAN',
 'P20265': 'PO3F2_HUMAN',
 'P20929': 'NEBU_HUMAN',
 'P20936': 'RASA1_HUMAN',
 'P22492': 'H1T_HUMAN',
 'P22681': 'CBL_HUMAN',
 'P22914': 'CRYGS_HUMAN',
 'P23759': 'PAX7_HUMAN',
 'P25490': 'TYY1_HUMAN',
 'P25685': 'DNJB1_HUMAN',
 'P26367': 'PAX6_HUMAN',
 'P26651': 'TTP_HUMAN',
 'P28069': 'PIT1_HUMAN',
 'P28360': 'MSX1_HUMAN',
 'P32081': 'CSPB_BACSU',
 'P32243': 'OTX2_HUMAN',
 'P35251': 'RFC1_HUMAN',
 'P35548': 'MSX2_HUMAN',
 'P35711': 'SOX5_HUMAN',
 'P35712': 'SOX6_HUMAN',
 'P35713': 'SOX18_HUMAN',
 'P35716': 'SOX11_HUMAN',
 'P36075': 'CUE2_YEAST',
 'P37275': 'ZEB1_HUMAN',
 'P39880': 'CUX1_HUMAN',
 'P39940': 'RSP5_YEAST',
 'P40040': 'THO1_YEAST',
 'P41002': 'CCNF_HUMAN',
 'P41016': 'CSPB_BACCL',
 'P41225': 'SOX3_HUMAN',
 'P41229': 'KDM5C_HUMAN',
 'P42766': 'RL35_HUMAN',
 'P43320': 'CRBB2_HUMAN',
 'P43354': 'NR4A2_HUMAN',
 'P45973': 'CBX5_HUMAN',
 'P46934': 'NEDD4_HUMAN',
 'P46937': 'YAP1_HUMAN',
 'P47974': 'TISD_HUMAN',
 'P48431': 'SOX2_HUMAN',
 'P49335': 'PO3F4_HUMAN',
 'P49792': 'RBP2_HUMAN',
 'P50539': 'MXI1_HUMAN',
 'P51451': 'BLK_HUMAN',
 'P51508': 'ZNF81_HUMAN',
 'P51532': 'SMCA4_HUMAN',
 'P51608': 'MECP2_HUMAN',
 'P51687': 'SUOX_HUMAN',
 'P53673': 'CRBA4_HUMAN',
 'P53674': 'CRBB1_HUMAN',
 'P53804': 'TTC3_HUMAN',
 'P54277': 'PMS1_HUMAN',
 'P54727': 'RD23B_HUMAN',
 'P54821': 'PRRX1_HUMAN',
 'P55072': 'TERA_HUMAN',
 'P55265': 'DSRAD_HUMAN',
 'P55895': 'RAG2_HUMAN',
 'P56915': 'GSC_HUMAN',
 'P57071': 'PRD15_HUMAN',
 'P57073': 'SOX8_HUMAN',
 'P60002': 'ELOF1_HUMAN',
 'P60321': 'NANO2_HUMAN',
 'P61024': 'CKS1_HUMAN',
 'P61086': 'UBE2K_HUMAN',
 'P61960': 'UFM1_HUMAN',
 'P61978': 'HNRPK_HUMAN',
 'P62993': 'GRB2_HUMAN',
 'P67809': 'YBOX1_HUMAN',
 'P78352': 'DLG4_HUMAN',
 'P78424': 'PO6F2_HUMAN',
 'P78545': 'ELF3_HUMAN',
 'P78563': 'RED1_HUMAN',
 'P82979': 'SARNP_HUMAN',
 'P98175': 'RBM10_HUMAN',
 'Q00839': 'HNRPU_HUMAN',
 'Q00987': 'MDM2_HUMAN',
 'Q01484': 'ANK2_HUMAN',
 'Q01543': 'FLI1_HUMAN',
 'Q01826': 'SATB1_HUMAN',
 'Q01851': 'PO4F1_HUMAN',
 'Q01860': 'PO5F1_HUMAN',
 'Q03052': 'PO3F1_HUMAN',
 'Q03164': 'KMT2A_HUMAN',
 'Q03181': 'PPARD_HUMAN',
 'Q05066': 'SRY_HUMAN',
 'Q05086': 'UBE3A_HUMAN',
 'Q05195': 'MAD1_HUMAN',
 'Q05655': 'KPCD_HUMAN',
 'Q06187': 'BTK_HUMAN',
 'Q06546': 'GABPA_HUMAN',
 'Q06787': 'FMR1_HUMAN',
 'Q06945': 'SOX4_HUMAN',
 'Q08881': 'ITK_HUMAN',
 'Q09472': 'EP300_HUMAN',
 'Q12824': 'SNF5_HUMAN',
 'Q12830': 'BPTF_HUMAN',
 'Q12837': 'PO4F2_HUMAN',
 'Q12873': 'CHD3_HUMAN',
 'Q12899': 'TRI26_HUMAN',
 'Q12929': 'EPS8_HUMAN',
 'Q12955': 'ANK3_HUMAN',
 'Q12965': 'MYO1E_HUMAN',
 'Q13009': 'TIAM1_HUMAN',
 'Q13148': 'TADBP_HUMAN',
 'Q13158': 'FADD_HUMAN',
 'Q13163': 'MP2K5_HUMAN',
 'Q13263': 'TIF1B_HUMAN',
 'Q13368': 'MPP3_HUMAN',
 'Q13424': 'SNTA1_HUMAN',
 'Q13472': 'TOP3A_HUMAN',
 'Q13501': 'SQSTM_HUMAN',
 'Q13526': 'PIN1_HUMAN',
 'Q13642': 'FHL1_HUMAN',
 'Q13813': 'SPTN1_HUMAN',
 'Q14151': 'SAFB2_HUMAN',
 'Q14160': 'SCRIB_HUMAN',
 'Q14192': 'FHL2_HUMAN',
 'Q14202': 'ZMYM3_HUMAN',
 'Q14839': 'CHD4_HUMAN',
 'Q14863': 'PO6F1_HUMAN',
 'Q14995': 'NR1D2_HUMAN',
 'Q14CM0': 'FRPD4_HUMAN',
 'Q14CS0': 'UBX2B_HUMAN',
 'Q15319': 'PO4F3_HUMAN',
 'Q15365': 'PCBP1_HUMAN',
 'Q15424': 'SAFB1_HUMAN',
 'Q15475': 'SIX1_HUMAN',
 'Q15554': 'TERF2_HUMAN',
 'Q15699': 'ALX1_HUMAN',
 'Q15811': 'ITSN1_HUMAN',
 'Q15911': 'ZFHX3_HUMAN',
 'Q15942': 'ZYX_HUMAN',
 'Q16512': 'PKN1_HUMAN',
 'Q1KMD3': 'HNRL2_HUMAN',
 'Q2Q1W2': 'LIN41_HUMAN',
 'Q5F1R6': 'DJC21_HUMAN',
 'Q5HYK7': 'SH319_HUMAN',
 'Q5K651': 'SAMD9_HUMAN',
 'Q5SQQ9': 'VAX1_HUMAN',
 'Q5TCQ9': 'MAGI3_HUMAN',
 'Q5U5Q3': 'MEX3C_HUMAN',
 'Q5VTD9': 'GFI1B_HUMAN',
 'Q5VVJ2': 'MYSM1_HUMAN',
 'Q5VWI1': 'TCRGL_HUMAN',
 'Q61234': 'SNTA1_MOUSE',
 'Q68CP9': 'ARID2_HUMAN',
 'Q68DC2': 'ANKS6_HUMAN',
 'Q6NWY9': 'PR40B_HUMAN',
 'Q6P0N0': 'M18BP_HUMAN',
 'Q6XZF7': 'DNMBP_HUMAN',
 'Q6ZN01': 'MASTR_HUMAN',
 'Q6ZSG1': 'ARK2C_HUMAN',
 'Q6ZVD7': 'STOX1_HUMAN',
 'Q6ZWJ1': 'STXB4_HUMAN',
 'Q7L590': 'MCM10_HUMAN',
 'Q7Z3T8': 'ZFY16_HUMAN',
 'Q7Z4I7': 'LIMS2_HUMAN',
 'Q7Z5Q1': 'CPEB2_HUMAN',
 'Q7Z6B7': 'SRGP1_HUMAN',
 'Q7Z6G8': 'ANS1B_HUMAN',
 'Q7Z6W7': 'DNJB7_HUMAN',
 'Q7Z6Z7': 'HUWE1_HUMAN',
 'Q86U86': 'PB1_HUMAN',
 'Q86UL8': 'MAGI2_HUMAN',
 'Q86UP3': 'ZFHX4_HUMAN',
 'Q86VP1': 'TAXB1_HUMAN',
 'Q86WN1': 'FCSD1_HUMAN',
 'Q86XK2': 'FBX11_HUMAN',
 'Q86XN8': 'MEX3D_HUMAN',
 'Q86YT6': 'MIB1_HUMAN',
 'Q8IV48': 'ERI1_HUMAN',
 'Q8IWR0': 'Z3H7A_HUMAN',
 'Q8IWT3': 'CUL9_HUMAN',
 'Q8IX12': 'CCAR1_HUMAN',
 'Q8IYH5': 'ZZZ3_HUMAN',
 'Q8IZQ8': 'MYCD_HUMAN',
 'Q8IZT6': 'ASPM_HUMAN',
 'Q8N157': 'AHI1_HUMAN',
 'Q8N1P7': 'CRBG2_HUMAN',
 'Q8N1W1': 'ARG28_HUMAN',
 'Q8N3X1': 'FNBP4_HUMAN',
 'Q8N5C8': 'TAB3_HUMAN',
 'Q8N8B7': 'TEANC_HUMAN',
 'Q8NB78': 'KDM1B_HUMAN',
 'Q8ND56': 'LS14A_HUMAN',
 'Q8NEA6': 'GLIS3_HUMAN',
 'Q8NEZ5': 'FBX22_HUMAN',
 'Q8NFW5': 'DMBX1_HUMAN',
 'Q8NHM5': 'KDM2B_HUMAN',
 'Q8TAQ2': 'SMRC2_HUMAN',
 'Q8TAT5': 'NEIL3_HUMAN',
 'Q8TDD2': 'SP7_HUMAN',
 'Q8TDI0': 'CHD5_HUMAN',
 'Q8TEW0': 'PARD3_HUMAN',
 'Q8TEW8': 'PAR3L_HUMAN',
 'Q8WU90': 'ZC3HF_HUMAN',
 'Q8WWH4': 'ASZ1_HUMAN',
 'Q8WXI2': 'CNKR2_HUMAN',
 'Q8WXI9': 'P66B_HUMAN',
 'Q92734': 'TFG_HUMAN',
 'Q92796': 'DLG3_HUMAN',
 'Q92922': 'SMRC1_HUMAN',
 'Q92945': 'FUBP2_HUMAN',
 'Q92997': 'DVL3_HUMAN',
 'Q969G3': 'SMCE1_HUMAN',
 'Q969V6': 'MRTFA_HUMAN',
 'Q96AE4': 'FUBP1_HUMAN',
 'Q96CB8': 'INT12_HUMAN',
 'Q96DX7': 'TRI44_HUMAN',
 'Q96FX2': 'DPH3_HUMAN',
 'Q96GE6': 'CALL4_HUMAN',
 'Q96GM8': 'TOE1_HUMAN',
 'Q96I24': 'FUBP3_HUMAN',
 'Q96J02': 'ITCH_HUMAN',
 'Q96JN0': 'LCOR_HUMAN',
 'Q96JY0': 'MAEL_HUMAN',
 'Q96JY6': 'PDLI2_HUMAN',
 'Q96K80': 'ZC3HA_HUMAN',
 'Q96KC8': 'DNJC1_HUMAN',
 'Q96L93': 'KI16B_HUMAN',
 'Q96PU5': 'NED4L_HUMAN',
 'Q96QS3': 'ARX_HUMAN',
 'Q96QZ7': 'MAGI1_HUMAN',
 'Q96RT1': 'ERBIN_HUMAN',
 'Q96T51': 'RUFY1_HUMAN',
 'Q99501': 'GA2L1_HUMAN',
 'Q99543': 'DNJC2_HUMAN',
 'Q99615': 'DNJC7_HUMAN',
 'Q99684': 'GFI1_HUMAN',
 'Q9BRP0': 'OVOL2_HUMAN',
 'Q9BTC0': 'DIDO1_HUMAN',
 'Q9BTC8': 'MTA3_HUMAN',
 'Q9BUJ2': 'HNRL1_HUMAN',
 'Q9BV68': 'RN126_HUMAN',
 'Q9BY11': 'PACN1_HUMAN',
 'Q9BYM8': 'HOIL1_HUMAN',
 'Q9BYW2': 'SETD2_HUMAN',
 'Q9BZM3': 'GSX2_HUMAN',
 'Q9C030': 'TRIM6_HUMAN',
 'Q9C0A1': 'ZFHX2_HUMAN',
 'Q9GZV5': 'WWTR1_HUMAN',
 'Q9H000': 'MKRN2_HUMAN',
 'Q9H0A6': 'RNF32_HUMAN',
 'Q9H0M0': 'WWP1_HUMAN',
 'Q9H161': 'ALX4_HUMAN',
 'Q9H2P0': 'ADNP_HUMAN',
 'Q9H347': 'UBQL3_HUMAN',
 'Q9H3D4': 'P63_HUMAN',
 'Q9H3Z4': 'DNJC5_HUMAN',
 'Q9H4A3': 'WNK1_HUMAN',
 'Q9H6I2': 'SOX17_HUMAN',
 'Q9H7E2': 'TDRD3_HUMAN',
 'Q9H9D4': 'ZN408_HUMAN',
 'Q9H9L4': 'KANL2_HUMAN',
 'Q9HA38': 'ZMAT3_HUMAN',
 'Q9HAU4': 'SMUF2_HUMAN',
 'Q9HAZ2': 'PRD16_HUMAN',
 'Q9HC78': 'ZBT20_HUMAN',
 'Q9NP66': 'HM20A_HUMAN',
 'Q9NPB3': 'CABP2_HUMAN',
 'Q9NPC8': 'SIX2_HUMAN',
 'Q9NQ86': 'TRI36_HUMAN',
 'Q9NQV8': 'PRDM8_HUMAN',
 'Q9NQX1': 'PRDM5_HUMAN',
 'Q9NSC2': 'SALL1_HUMAN',
 'Q9NU63': 'ZFP57_HUMAN',
 'Q9NUP7': 'TRM13_HUMAN',
 'Q9NW38': 'FANCL_HUMAN',
 'Q9NWH9': 'SLTM_HUMAN',
 'Q9NYL2': 'M3K20_HUMAN',
 'Q9NYS7': 'WSB2_HUMAN',
 'Q9NZM3': 'ITSN2_HUMAN',
 'Q9P0J7': 'KCMF1_HUMAN',
 'Q9P2D1': 'CHD7_HUMAN',
 'Q9P2F5': 'STOX2_HUMAN',
 'Q9P2K3': 'RCOR3_HUMAN',
 'Q9P2P5': 'HECW2_HUMAN',
 'Q9P2R6': 'RERE_HUMAN',
 'Q9UBF6': 'RBX2_HUMAN',
 'Q9UBS4': 'DJB11_HUMAN',
 'Q9UBW7': 'ZMYM2_HUMAN',
 'Q9UBX0': 'HESX1_HUMAN',
 'Q9UDY2': 'ZO2_HUMAN',
 'Q9UHA3': 'RLP24_HUMAN',
 'Q9UHC7': 'MKRN1_HUMAN',
 'Q9UHD4': 'CIDEB_HUMAN',
 'Q9UIF8': 'BAZ2B_HUMAN',
 'Q9UJ78': 'ZMYM5_HUMAN',
 'Q9UJQ4': 'SALL4_HUMAN',
 'Q9UJV3': 'TRIM1_HUMAN',
 'Q9UKI9': 'PO2F3_HUMAN',
 'Q9UKL0': 'RCOR1_HUMAN',
 'Q9UKS6': 'PACN3_HUMAN',
 'Q9UKW6': 'ELF5_HUMAN',
 'Q9UKY1': 'ZHX1_HUMAN',
 'Q9UL15': 'BAG5_HUMAN',
 'Q9ULJ8': 'NEB1_HUMAN',
 'Q9ULL8': 'SHRM4_HUMAN',
 'Q9ULT8': 'HECD1_HUMAN',
 'Q9ULZ3': 'ASC_HUMAN',
 'Q9UNF0': 'PACN2_HUMAN',
 'Q9UPQ7': 'PZRN3_HUMAN',
 'Q9UPW6': 'SATB2_HUMAN',
 'Q9UQR1': 'ZN148_HUMAN',
 'Q9Y222': 'DMTF1_HUMAN',
 'Q9Y2G7': 'ZFP30_HUMAN',
 'Q9Y2T7': 'YBOX2_HUMAN',
 'Q9Y3R0': 'GRIP1_HUMAN',
 'Q9Y462': 'ZN711_HUMAN',
 'Q9Y4I5': 'MTL5_HUMAN',
 'Q9Y4J8': 'DTNA_HUMAN',
 'Q9Y5K6': 'CD2AP_HUMAN',
 'Q9Y618': 'NCOR2_HUMAN',
 'Q9Y6N9': 'USH1C_HUMAN',
 'Q9Y6V0': 'PCLO_HUMAN'}

In [4]:
idmapping_dict.update({
    'Q3SY89':'ELB3B_HUMAN',
    'A2RRE5':'A2RRE5_HUMAN',
    'A0A2R8Y422': 'A0A2R8Y422_HUMAN'
})

In [5]:
with open('/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/DMS_assays/processed_data/Beltran_Lehner_2025/idmapping_2025_06_10.csv', 'w') as f_out:
    for key, value in idmapping_dict.items():
        f_out.write(f"{key},{value}\n")

## Fill out the [DMS_substitution_internal](https://docs.google.com/spreadsheets/d/1M1dKN0wpvE2sKDt4hwrIsTBS1r1HbBObUxjO4LNOQ64/edit?gid=560024392#gid=560024392) sheet for all domains
- Add a column of the full sequence of the protein and check [DMS_fields](https://docs.google.com/spreadsheets/d/1M1dKN0wpvE2sKDt4hwrIsTBS1r1HbBObUxjO4LNOQ64/edit?gid=560024392#gid=560024392)
- Get the sequence of each domain and add the commas between neighboring domains

Other info
- taxon: Eukaryote
- source_organism: Homo sapiens
- assay_organism: Saccharomyces cerevisiae
- target_aa: parsed below
- target_nt_seq: **need to check**
- full_aa_seq: leave blank
- full_nt_seq: **need to generate from online sources**
- domain_list_target_sequence: **need to convert the current to SwissProt**
- domain_list_full_sequence: **need to generate from online sources**
- include_multiple_mutants: FALSE
- DMS_total_number_mutants: **do we include synonymous for glms?**
- DMS_number_single_mutants: same as above
- DMS_number_multiple_mutants: 0
- DMS_binarization_cutoff: see below
- DMS_wildtype_score: 0
- publication info: omitted, available
- region_mutated: can parse from domain id
- molecule name: **need to generate from online sources**
- selection_assay: Growth
- selection_type: Stability
- library_construction: **?**
- replicates: 3 biological, **need to fill in r^2**
- has_codon_level: FALSE
- MSA_filename: `DMS-ID_b-bitscore.a2m`
- other MSA info: done
- raw_DMS_file_name: SupplementaryTable2.txt
- raw_DMS_phenotype_name: normalized_fitness
- raw_DMS_directionality: 1
- raw_DMS_mutant_column: mut_aa
- raw_DMS_replicate_columns: **no fitness score replicates available, only the counts from 3 replicates**
- weight_file_name: `DMS-ID_theta0.2_b-bitscore.npy`
- pdb_file: `DMS-ID.pdb`
- ProteinGym_version: 1.4
- raw_mut_offset: N/A
- coarse_selection_type: Abundance
- coarse_selection_reason:

In [7]:
def cp_file(from_path, to_path, silent=False):
    try:
        return subprocess.run(
            ["cp", from_path, to_path],
            check=True,
            stdout=subprocess.DEVNULL if silent else None,
            stderr=subprocess.DEVNULL if silent else None,
        )
    except subprocess.CalledProcessError as e:
        raise e

## Create the DMS data from each csv file

In [14]:
sys.path.append("/n/groups/marks/users/elain/PG2/ProteinGym/proteingym")

In [16]:
from utils import data_utils

In [19]:
target_seq_df = pd.read_csv('/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/EVCouplings/output/Beltran_Lehner_2025/target_seq.csv')
target_seq_dict = target_seq_df.set_index('DMS_id')['target_seq'].to_dict()

cleaned_DMS_directory = '/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/DMS_assays/processed_data/Beltran_Lehner_2025/cleaned'

In [23]:
domainome.head()

,domain_ID,uniprot_ID,aa_seq,wt_aa,position,mut_aa,STOP,input_count_rep1,input_count_rep2,input_count_rep3,output_count_rep1,output_count_rep2,output_count_rep3,mean_input_count,fitness,fitness_sigma,normalized_fitness,normalized_fitness_sigma,quality_rank
0,A0A2R8Y422_PF00240_2,A0A2R8Y422,*IFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2,*,True,118,113,62,10,29,2,97.66667,0.030945,0.014885,-0.819050,0.208478,339
1,A0A2R8Y422_PF00240_2,A0A2R8Y422,AIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2,A,False,219,277,217,86,225,137,237.66670,0.069376,0.006673,-0.280790,0.093461,339
2,A0A2R8Y422_PF00240_2,A0A2R8Y422,CIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2,C,False,706,726,459,768,507,616,630.33330,0.082052,0.004141,-0.103250,0.057995,339
3,A0A2R8Y422_PF00240_2,A0A2R8Y422,DIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2,D,False,407,431,323,508,159,111,387.00000,0.071003,0.005162,-0.258003,0.072296,339
4,A0A2R8Y422_PF00240_2,A0A2R8Y422,EIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,Q,2,E,False,37,56,37,201,102,95,43.33333,0.116326,0.012085,0.376783,0.169263,339

In [28]:
for domain_id in domain_id_list:
    dms_id = make_dms_id(domain_id)
    _, _, idx = domain_id.split('_')
    idx = int(idx)
    raw_dms_df = pd.read_csv(f"/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/DMS_assays/processed_data/Beltran_Lehner_2025/{dms_id}.csv")
    raw_dms_df['mutant'] = raw_dms_df.apply(lambda row: row.wt_aa + str(int(row.position) - idx + 1) + row.mut_aa, axis=1)
    raw_dms_df.rename(columns={'aa_seq': 'mutated_sequence', 'normalized_fitness': 'score'}, inplace=True)
    raw_dms_df = raw_dms_df[['mutant', 'mutated_sequence', 'score']]
    raw_dms_df.to_csv(cleaned_DMS_directory + '/' + dms_id + '.tmp', index=False)
    target_seq = target_seq_dict[dms_id]
    cleaned_df = data_utils.DMS_file_cleanup(cleaned_DMS_directory + '/' + dms_id + '.tmp', target_seq)
    cleaned_df.to_csv(cleaned_DMS_directory + '/' + dms_id + '.csv', index=False)

## Move all the pdb files to one directory

In [8]:
destination_directory = '/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/pdbs'
from_directory = '/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/DMS_AF2/Beltran_Lehner_2025/output'

for domain_id in domain_id_list:
    from_pdb_file = from_directory + '/' + domain_id + '/ranked_0.pdb'
    dms_id = make_dms_id(domain_id)
    to_pdb_file = destination_directory + '/' + dms_id + '.pdb'
    cp_file(from_pdb_file, to_pdb_file)

## Add pdb_range to the reference file

In [2]:
df = pd.read_csv('/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/EVCouplings/output/Beltran_Lehner_2025/temp_ref_file.csv')
df.head()

,DMS_id,MSA_bitscore,MSA_num_seqs,MSA_perc_cov,MSA_num_cov,MSA_N_eff,MSA_Neff_L,MSA_Neff_L_category,weight_file_name,MSA_filename,...,MSA_start,MSA_end,MSA_len,MSA_theta,taxon,source_organism,includes_multiple_mutants,DMS_wildtype_score,first_author,coarse_selection_type
0,A0A2R8Y422_HUMAN_Beltran_2025_PF00240_2,0.7,61559,0.971,68,5929.1,84.701140,medium,A0A2R8Y422_HUMAN_Beltran_2025_PF00240_2_theta_...,A0A2R8Y422_HUMAN_Beltran_2025_PF00240_2_theta_...,...,1,70,70,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance
1,FEZF1_HUMAN_Beltran_2025_PF00096_289,1.5,645870,0.955,21,1813.5,82.430408,medium,FEZF1_HUMAN_Beltran_2025_PF00096_289_theta_0.8...,FEZF1_HUMAN_Beltran_2025_PF00096_289_theta_0.8...,...,1,22,22,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance
2,SPD2B_HUMAN_Beltran_2025_PF00018_155,0.9,33216,0.945,52,721.9,13.125128,medium,SPD2B_HUMAN_Beltran_2025_PF00018_155_theta_0.8...,SPD2B_HUMAN_Beltran_2025_PF00018_155_theta_0.8...,...,1,55,55,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance
3,SPD2B_HUMAN_Beltran_2025_PF00018_222,0.9,45592,0.898,53,947.7,16.062838,medium,SPD2B_HUMAN_Beltran_2025_PF00018_222_theta_0.8...,SPD2B_HUMAN_Beltran_2025_PF00018_222_theta_0.8...,...,1,59,59,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance
4,A2RRE5_HUMAN_Beltran_2025_PF01846_267,0.7,4543,0.952,60,128.7,2.042930,medium,A2RRE5_HUMAN_Beltran_2025_PF01846_267_theta_0....,A2RRE5_HUMAN_Beltran_2025_PF01846_267_theta_0....,...,1,63,63,0.2,Human,Saccharomyces cerevisiae,False,0,Beltran,Abundance

In [3]:
df['pdb_range'] = df['MSA_start'].astype(str) + '-' + df['MSA_end'].astype(str)
df.to_csv('/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym2/EVCouplings/output/Beltran_Lehner_2025/temp_ref_file_pdb_range.csv', index=False)