Processing DMS files from preprocessed_substitutions

In [1]:
import os
import shutil
import sys

import numpy as np
import pandas as pd
from tqdm.auto import tqdm

pd.set_option("display.max_rows", 20, "display.max_columns", None)

sys.path.append("../scripts/")
from dms_preprocessing_utils import check_wt, hgvs_to_1aa, mut_pos_regex, count_missense_non_na

In [2]:
# Inputs:
reference_file = "/n/groups/marks/projects/indels_human/anon/reference_files/DMS_substitutions.csv"
# reference_file = "/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/reference_files/DMS_substitutions_WIP_2023_10_18.csv"
dms_preprocessed_folder = "/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/preprocessed_substitutions/"
# dms_preprocessed_folder_nathan = "/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed/"

# Output:
dms_processed_folder_out = "/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/substitutions"

In [3]:
ref_df = pd.read_csv(reference_file)
# When using the reference file with "excluded" version, we need to use strings for ProteinGym_version
keep_versions = [0.1, 1]
ref_df = ref_df[ref_df["ProteinGym_version"].isin(keep_versions)]
ref_df["ProteinGym_version"] = ref_df["ProteinGym_version"].astype(float)
assert len(ref_df) > 0

In [4]:
# Quick check: missing files
dms_folder = "/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/substitutions"
dms_files = os.listdir(dms_folder)
ref_df[~ref_df["DMS_filename"].isin(dms_files)]

Empty DataFrame
Columns: [DMS_id, DMS_filename, UniProt_ID, taxon, source_organism, target_seq, seq_len, includes_multiple_mutants, DMS_total_number_mutants, DMS_number_single_mutants, DMS_number_multiple_mutants, DMS_binarization_cutoff, DMS_binarization_method, first_author, title, year, jo, region_mutated, molecule_name, selection_assay, selection_type, library_construction, replicates, MSA_filename, MSA_start, MSA_end, MSA_len, MSA_bitscore, MSA_theta, MSA_num_seqs, MSA_perc_cov, MSA_num_cov, MSA_N_eff, MSA_Neff_L, MSA_Neff_L_category, MSA_num_significant, MSA_num_significant_L, raw_DMS_filename, raw_DMS_phenotype_name, raw_DMS_directionality, raw_DMS_mutant_column, weight_file_name, reviewed_by, Comments, Old_DMS_ID, Old_UniProt_ID, Old_target_seq, MSA_comments, ProteinGym_version, Reason excluded, raw_mut_offset]
Index: []

In [14]:
# TODO import proteingym.DMS_processing_utils (copy from tranception repo?)
# Run on each of the DMS files
AA_vocab = "ACDEFGHIKLMNPQRSTVWY"

def get_mutated_sequence(focus_seq, mutant, start_idx=1, AA_vocab=AA_vocab):
    """
    Helper function that mutates an input sequence (focus_seq) via an input mutation triplet (substitutions only).
    Mutation triplet are typically based on 1-indexing: start_idx is used for switching to 0-indexing.
    """
    mutated_seq = list(focus_seq)
    for mutation in mutant.split(":"):
        try:
            from_AA, position, to_AA = mutation[0], int(mutation[1:-1]), mutation[-1]
        except:
            print("Issue with mutant: "+str(mutation))
        relative_position = position - start_idx
        assert (from_AA==focus_seq[relative_position]), "Invalid from_AA or mutant position: "+str(mutation)+" from_AA: "+str(from_AA) + " relative pos: "+str(relative_position) + " focus_seq: "+str(focus_seq)
        assert (to_AA in AA_vocab) , "Mutant to_AA is invalid: "+str(mutation)
        mutated_seq[relative_position] = to_AA
    return "".join(mutated_seq)

def DMS_file_cleanup(DMS_filename, target_seq, DMS_binarization_threshold, start_idx=1, end_idx=None, DMS_mutant_column='mutant', DMS_phenotype_name='score', DMS_directionality=1, AA_vocab = "ACDEFGHIKLMNPQRSTVWY", debug=False, strict_wt_check=False):
    """
    Function to process the raw substitution DMS assay data (eg., removing invalid mutants, aggregate silent mutations).
    """
    DMS_data = pd.read_csv(DMS_filename, low_memory=False)
    assert DMS_phenotype_name in DMS_data.columns, f"Phenotype column not found: {DMS_phenotype_name}; columns: {DMS_data.columns}"
    end_idx = start_idx + len(target_seq) - 1 if end_idx is None else end_idx
    DMS_data['mutant'] = DMS_data[DMS_mutant_column]
    
    DMS_data=DMS_data[DMS_data['mutant'].notnull()].copy()
    DMS_data = DMS_data[~(DMS_data['mutant'] == "WT")]
    len_before = len(DMS_data)
    
    # Checking the following conditions but making a column for each:
    # DMS_data=DMS_data[DMS_data['mutant'].apply(lambda x: all([len(y)>=3 for y in x.split(":")]))].copy() # Mutant triplets should have at least 3 or more characters
    # DMS_data=DMS_data[DMS_data['mutant'].apply(lambda x: all([y[0]==target_seq[int(y[1:-1])-start_idx] for y in x.split(":")]))].copy()  # Checking all WT amino acids match target sequence
    # DMS_data=DMS_data[DMS_data['mutant'].apply(lambda x: all([(y[0] in AA_vocab) and (y[1:-1].isnumeric()) and (y[-1] in AA_vocab) for y in x.split(":")]))].copy()
    # DMS_data=DMS_data[DMS_data['mutant'].apply(lambda x: all([int(y[1:-1])-start_idx >=0 and int(y[1:-1]) <= end_idx for y in x.split(":")]))].copy()
    DMS_data["mutant_format"] = DMS_data['mutant'].apply(lambda x: all([len(y)>=3 for y in x.split(":")])) # Mutant triplets should have at least 3 or more characters
    DMS_data["mutant_valid_aa"] = DMS_data['mutant'].apply(lambda x: all([(y[0] in AA_vocab) and (y[1:-1].isnumeric()) and (y[-1] in AA_vocab) for y in x.split(":")]))
    DMS_data["match_wt"] = False
    
    DMS_data.loc[DMS_data["mutant_format"] & DMS_data["mutant_valid_aa"], "pos_max"] = DMS_data.loc[DMS_data["mutant_format"] & DMS_data["mutant_valid_aa"], "mutant"].apply(lambda x: max([int(y[1:-1]) for y in x.split(":")]))
    # assert pos_max <= len(target_seq), f"Maximum mutant position ({pos_max}) is greater than the length of the target sequence ({len(target_seq)})."
    if (DMS_data["pos_max"] > len(target_seq)).any():
        print(f"Warning: Some mutations have positions that are greater than target sequence length. Max mutation position: {pos_max.max()}, target seq length: {len(target_seq)}")
        print("Filtering mutations beyond target seq length") 
    DMS_data["valid_pos"] = (DMS_data["pos_max"] <= len(target_seq))
    
    # Dropping WT from dataframe 
    DMS_data.loc[DMS_data["mutant_format"] & DMS_data["mutant_valid_aa"] & DMS_data["valid_pos"], "match_wt"] = DMS_data.loc[DMS_data["mutant_format"] & DMS_data["mutant_valid_aa"] & DMS_data["valid_pos"], "mutant"].apply(lambda x: all([y[0]==target_seq[int(y[1:-1])-start_idx] for y in x.split(":")]))
    # Add synonymous filtering
    DMS_data["synonymous"] = DMS_data["mutant"].apply(lambda x: all([y[0]==y[-1] for y in x.split(":")]))
    
    num_wt_mismatch = (DMS_data["mutant_format"] & DMS_data["mutant_valid_aa"] & DMS_data["valid_pos"] & ~DMS_data["match_wt"] & ~DMS_data["synonymous"]).sum()

    if debug:
        print(f"Number of dropped mutant formats: {(~DMS_data['mutant_format']).sum()} / {len(DMS_data)} = {(~DMS_data['mutant_format']).sum()/len(DMS_data):.1%}")
        print(f"Number of dropped invalid amino acids: {(~DMS_data['mutant_valid_aa']).sum()} / {len(DMS_data)} = {(~DMS_data['mutant_valid_aa']).sum()/len(DMS_data):.1%}")
        print(f"Number of dropped synonymous mutants: {(DMS_data['synonymous']).sum()} / {len(DMS_data)} = {(DMS_data['synonymous']).sum()/len(DMS_data):.1%}")
        print(f"Number of dropped mutants not matching WT: {num_wt_mismatch} / {len(DMS_data)} = {num_wt_mismatch/len(DMS_data):.1%}")
        # If more than 5 WT check mutants are dropped, print warning
        if num_wt_mismatch > 5:
            print(f"Warning: More than 5 mutants ({num_wt_mismatch}) don't match WT target sequence. Do the positions index correctly into the target sequence?")
    
    if strict_wt_check:
        assert num_wt_mismatch == 0, f"Some {num_wt_mismatch} mutants don't match WT target sequence. Do the positions index correctly into the target sequence?. Examples: {DMS_data[(DMS_data['mutant_format'] & DMS_data['mutant_valid_aa'] & ~DMS_data['match_wt'])]['mutant'].head()}"
    
    DMS_data = DMS_data[DMS_data["mutant_format"] & DMS_data["mutant_valid_aa"] & DMS_data["match_wt"] & ~DMS_data["synonymous"] & DMS_data["valid_pos"]].copy()
    if len(DMS_data) != len_before:
        print(f"Dropped mutants: Length before: {len_before}, length after: {len(DMS_data)}: {1 - (len(DMS_data) / len_before):.1%} dropped")
        if 1 - (len(DMS_data) / len_before) > 0.1:
            print(f"Warning: Dropped more than 10% of mutants. This may indicate a problem with the DMS data.")
        
    assert len(DMS_data) > 0, f"All mutants have been filtered out, 0 length: {DMS_filename}"  # This might not always pick up...
    
    # Filter out synonymous mutants in multiples
    def remove_synon_multiple(muts):
        if ":" not in muts:
            return muts
        muts_split = muts.split(":")
        muts_missense = [m for m in muts_split if m[0] != m[-1]]
        # Don't filter out all, leave at least one, otherwise "mutant" is empty and will throw an error
        if len(muts_missense) == 0:
            muts_missense = muts_split[0]
        return ":".join(muts_missense)

    DMS_data["mutant"] = DMS_data["mutant"].apply(remove_synon_multiple)
    
    DMS_data[DMS_phenotype_name]=pd.to_numeric(DMS_data[DMS_phenotype_name],errors='coerce')
    DMS_data=DMS_data[np.isfinite(DMS_data[DMS_phenotype_name])]
    DMS_data.dropna(subset = [DMS_phenotype_name], inplace=True)
    DMS_directionality = float(DMS_directionality)
    if pd.isna(DMS_directionality):
        # TODO should this be a failure if not there?
        print("No DMS directionality found, using 1 by default.")
        DMS_directionality = 1
    DMS_data['DMS_score'] = DMS_data[DMS_phenotype_name] * DMS_directionality
    DMS_data=DMS_data[['mutant','DMS_score']]
    
    num_duplicate_mutants = DMS_data['mutant'].duplicated().sum()
    print(f"Debug: Number of duplicate mutants: {num_duplicate_mutants} ({num_duplicate_mutants / len(DMS_data):.2%})")
    
    # Average out mutations
    DMS_data=DMS_data.groupby('mutant').mean().reset_index()
    
    # Add DMS_binarization data
    if pd.isna(DMS_binarization_threshold):
        print("No binarization threshold given, will outputs NaNs in that column for now.")
        DMS_data["DMS_score_bin"] = np.nan
    else:
        DMS_data["DMS_score_bin"] = DMS_data["DMS_score"].apply(lambda x: 1 if x > (DMS_directionality * DMS_binarization_threshold) else 0)

    
    DMS_data['mutated_sequence'] = DMS_data['mutant'].apply(lambda x: get_mutated_sequence(target_seq, x))
    DMS_data=DMS_data[['mutant','mutated_sequence','DMS_score', "DMS_score_bin"]]
    print("Final length:", len(DMS_data))
    
    return DMS_data

## Note: Check up on this missing information in the file

In [15]:
# Some are missing raw DMS mutant column, will need to add in in original reference file processing notebook
necessary_cols = ["target_seq", "raw_DMS_phenotype_name","raw_DMS_directionality", "raw_DMS_mutant_column", "raw_DMS_directionality", "DMS_binarization_cutoff"]
nan_rows = ref_df[ref_df[necessary_cols].isna().any(axis=1)]
display(nan_rows)
nan_rows["reviewed_by"].value_counts()
assert len(nan_rows) == 0

Empty DataFrame
Columns: [DMS_id, DMS_filename, UniProt_ID, taxon, source_organism, target_seq, seq_len, includes_multiple_mutants, DMS_total_number_mutants, DMS_number_single_mutants, DMS_number_multiple_mutants, DMS_binarization_cutoff, DMS_binarization_method, first_author, title, year, jo, region_mutated, molecule_name, selection_assay, selection_type, library_construction, replicates, MSA_filename, MSA_start, MSA_end, MSA_len, MSA_bitscore, MSA_theta, MSA_num_seqs, MSA_perc_cov, MSA_num_cov, MSA_N_eff, MSA_Neff_L, MSA_Neff_L_category, MSA_num_significant, MSA_num_significant_L, raw_DMS_filename, raw_DMS_phenotype_name, raw_DMS_directionality, raw_DMS_mutant_column, weight_file_name, reviewed_by, Comments, Old_DMS_ID, Old_UniProt_ID, Old_target_seq, MSA_comments, ProteinGym_version, Reason excluded, raw_mut_offset]
Index: []

In [16]:
import numpy as np
def flatten(l):
    return [item for sublist in l for item in sublist if sublist != np.NaN]

# Show an example here
dms_filename = "AMFR_HUMAN_Rocklin_2023_4G3O.csv"
orig_file = "AMFR_HUMAN_Rocklin_2023_4G3O.csv"
row = ref_df[ref_df["DMS_filename"] == dms_filename].iloc[0]
filename = dms_preprocessed_folder + "/" + orig_file
dms_bin_threshold = row["DMS_binarization_cutoff"]
tmp_df = pd.read_csv(filename)
target_seq = row["target_seq"]
# tmp_df["mutant_valid_aa"] = tmp_df['mutant'].apply(lambda x: all([(y[0] in AA_vocab) and (y[1:-1].isnumeric()) and (y[-1] in AA_vocab) for y in x.split(":")]))
# display(tmp_df[~tmp_df["mutant_valid_aa"]])

# tmp_df["positions"] = tmp_df[tmp_df["mutant_valid_aa"]]['mutant'].apply(lambda x: [int(y[1:-1]) for y in x.split(":")])
# unzip all the nested lists into a single list
# pos_list = tmp_df["positions"]
# positions_unique = set(flatten(tmp_df["positions"].dropna()))
# print(positions_unique)
# print(tmp_df[tmp_df["positions"].apply(lambda li: ~np.isnan(li) and 0 in li)])
# tmp_wt = "MLDDRARMEAAKKEKVEQILAEFQLQEEDLKKVMRRMQKEMDRGLRLETHEEASVKMLPTYVRSTPEGSEVGDFLSLDLGGTNFRVMLVKVGEGEEGQWSVKTKHQMYSIPEDAMTGTAEMLFDYISECISDFLDKHQMKHKKLPLGFTFSFPVRHEDIDKGILLNWTKGFKASGAEGNNVVGLLRDAIKRRGDFEMDVVAMVNDTVATMISCYYEDHQCEVGMIVGTGCNACYMEEMQNVELVEGDEGRMCVNTEWGAFGDSGELDEFLLEYDRLVDESSANPGQQLYEKLIGGKYMGELVRLVLLRLVDENLLFHGEASEQLRTRGAFETRFVSQVESDTGDRKQIYNILSTLGLRPSTTDCDIVRRACESVSTRAAHMCSAGLAGVINRMRESRSEDVMRITVGVDGSVYKLHPSFKERFHASVRRLTPSCEITFIESEEGSGRGAALVSAVACKKACMLGQ"
tmp_df_clean = DMS_file_cleanup(filename, target_seq=target_seq, DMS_binarization_threshold=dms_bin_threshold, DMS_mutant_column=row["raw_DMS_mutant_column"], DMS_phenotype_name=row["raw_DMS_phenotype_name"], DMS_directionality=row["raw_DMS_directionality"], debug=True, strict_wt_check=True)
def check_synon_multiple(mutant):
    muts = mutant.split(":")
    if len(muts) > 1:
        for mut in muts:
            if mut[0] == mut[-1]:
                return True 
    return False 
display(tmp_df_clean)
# tmp_df_clean.to_csv(f"/n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/substitutions/{dms_filename}",index=False)

Number of dropped mutant formats: 5 / 4039 = 0.1%
Number of dropped invalid amino acids: 5 / 4039 = 0.1%
Number of dropped synonymous mutants: 11 / 4039 = 0.3%
Number of dropped mutants not matching WT: 0 / 4039 = 0.0%
Dropped mutants: Length before: 4039, length after: 4023: 0.4% dropped
HERE
D28Q:T32Q
['D28Q', 'T32Q']
HERE
D28Q:T32E
['D28Q', 'T32E']
HERE
D28Q:T32N
['D28Q', 'T32N']
HERE
D28Q:T32H
['D28Q', 'T32H']
HERE
D28Q:T32D
['D28Q', 'T32D']
HERE
D28Q:T32R
['D28Q', 'T32R']
HERE
D28Q:T32K
['D28Q', 'T32K']
HERE
D28Q:T32T
['D28Q']
HERE
D28Q:T32S
['D28Q', 'T32S']
HERE
D28Q:T32A
['D28Q', 'T32A']
HERE
D28Q:T32G
['D28Q', 'T32G']
HERE
D28Q:T32M
['D28Q', 'T32M']
HERE
D28Q:T32L
['D28Q', 'T32L']
HERE
D28Q:T32V
['D28Q', 'T32V']
HERE
D28Q:T32I
['D28Q', 'T32I']
HERE
D28Q:T32W
['D28Q', 'T32W']
HERE
D28Q:T32Y
['D28Q', 'T32Y']
HERE
D28Q:T32F
['D28Q', 'T32F']
HERE
D28Q:T32P
['D28Q', 'T32P']
HERE
D28E:T32Q
['D28E', 'T32Q']
HERE
D28E:T32E
['D28E', 'T32E']
HERE
D28E:T32N
['D28E', 'T32N']
HERE
D28E:T32H
['D28E', 'T32H']
HERE
D28E:T32D
['D28E', 'T32D']
HERE
D28E:T32R
['D28E', 'T32R']
HERE
D28E:T32K
['D28E', 'T32K']
HERE
D28E:T32T
['D28E']
HERE
D28E:T32S
['D28E', 'T32S']
HERE
D28E:T32A
['D28E', 'T32A']
HERE
D28E:T32G
['D28E', 'T32G']
HERE
D28E:T32M
['D28E', 'T32M']
HERE
D28E:T32L
['D28E', 'T32L']
HERE
D28E:T32V
['D28E', 'T32V']
HERE
D28E:T32I
['D28E', 'T32I']
HERE
D28E:T32W
['D28E', 'T32W']
HERE
D28E:T32Y
['D28E', 'T32Y']
HERE
D28E:T32F
['D28E', 'T32F']
HERE
D28E:T32P
['D28E', 'T32P']
HERE
D28N:T32Q
['D28N', 'T32Q']
HERE
D28N:T32E
['D28N', 'T32E']
HERE
D28N:T32N
['D28N', 'T32N']
HERE
D28N:T32H
['D28N', 'T32H']
HERE
D28N:T32D
['D28N', 'T32D']
HERE
D28N:T32R
['D28N', 'T32R']
HERE
D28N:T32K
['D28N', 'T32K']
HERE
D28N:T32T
['D28N']
HERE
D28N:T32S
['D28N', 'T32S']
HERE
D28N:T32A
['D28N', 'T32A']
HERE
D28N:T32G
['D28N', 'T32G']
HERE
D28N:T32M
['D28N', 'T32M']
HERE
D28N:T32L
['D28N', 'T32L']
HERE
D28N:T32V
['D28N', 'T32V']
HERE
D28N:T32I
['D28N', 'T32I']
HERE
D28N:T32W
['D28N', 'T32W']
HERE
D28N:T32Y
['D28N', 'T32Y']
HERE
D28N:T32F
['D28N', 'T32F']
HERE
D28N:T32P
['D28N', 'T32P']
HERE
D28H:T32Q
['D28H', 'T32Q']
HERE
D28H:T32E
['D28H', 'T32E']
HERE
D28H:T32N
['D28H', 'T32N']
HERE
D28H:T32H
['D28H', 'T32H']
HERE
D28H:T32D
['D28H', 'T32D']
HERE
D28H:T32R
['D28H', 'T32R']
HERE
D28H:T32K
['D28H', 'T32K']
HERE
D28H:T32T
['D28H']
HERE
D28H:T32S
['D28H', 'T32S']
HERE
D28H:T32A
['D28H', 'T32A']
HERE
D28H:T32G
['D28H', 'T32G']
HERE
D28H:T32M
['D28H', 'T32M']
HERE
D28H:T32L
['D28H', 'T32L']
HERE
D28H:T32V
['D28H', 'T32V']
HERE
D28H:T32I
['D28H', 'T32I']
HERE
D28H:T32W
['D28H', 'T32W']
HERE
D28H:T32Y
['D28H', 'T32Y']
HERE
D28H:T32F
['D28H', 'T32F']
HERE
D28H:T32P
['D28H', 'T32P']
HERE
D28D:T32Q
['T32Q']
HERE
D28D:T32E
['T32E']
HERE
D28D:T32N
['T32N']
HERE
D28D:T32H
['T32H']
HERE
D28D:T32D
['T32D']
HERE
D28D:T32R
['T32R']
HERE
D28D:T32K
['T32K']
HERE
D28D:T32S
['T32S']
HERE
D28D:T32A
['T32A']
HERE
D28D:T32G
['T32G']
HERE
D28D:T32M
['T32M']
HERE
D28D:T32L
['T32L']
HERE
D28D:T32V
['T32V']
HERE
D28D:T32I
['T32I']
HERE
D28D:T32W
['T32W']
HERE
D28D:T32Y
['T32Y']
HERE
D28D:T32F
['T32F']
HERE
D28D:T32P
['T32P']
HERE
D28R:T32Q
['D28R', 'T32Q']
HERE
D28R:T32E
['D28R', 'T32E']
HERE
D28R:T32N
['D28R', 'T32N']
HERE
D28R:T32H
['D28R', 'T32H']
HERE
D28R:T32D
['D28R', 'T32D']
HERE
D28R:T32R
['D28R', 'T32R']
HERE
D28R:T32K
['D28R', 'T32K']
HERE
D28R:T32T
['D28R']
HERE
D28R:T32S
['D28R', 'T32S']
HERE
D28R:T32A
['D28R', 'T32A']
HERE
D28R:T32G
['D28R', 'T32G']
HERE
D28R:T32M
['D28R', 'T32M']
HERE
D28R:T32L
['D28R', 'T32L']
HERE
D28R:T32V
['D28R', 'T32V']
HERE
D28R:T32I
['D28R', 'T32I']
HERE
D28R:T32W
['D28R', 'T32W']
HERE
D28R:T32Y
['D28R', 'T32Y']
HERE
D28R:T32F
['D28R', 'T32F']
HERE
D28R:T32P
['D28R', 'T32P']
HERE
D28K:T32Q
['D28K', 'T32Q']
HERE
D28K:T32E
['D28K', 'T32E']
HERE
D28K:T32N
['D28K', 'T32N']
HERE
D28K:T32H
['D28K', 'T32H']
HERE
D28K:T32D
['D28K', 'T32D']
HERE
D28K:T32R
['D28K', 'T32R']
HERE
D28K:T32K
['D28K', 'T32K']
HERE
D28K:T32T
['D28K']
HERE
D28K:T32S
['D28K', 'T32S']
HERE
D28K:T32A
['D28K', 'T32A']
HERE
D28K:T32G
['D28K', 'T32G']
HERE
D28K:T32M
['D28K', 'T32M']
HERE
D28K:T32L
['D28K', 'T32L']
HERE
D28K:T32V
['D28K', 'T32V']
HERE
D28K:T32I
['D28K', 'T32I']
HERE
D28K:T32W
['D28K', 'T32W']
HERE
D28K:T32Y
['D28K', 'T32Y']
HERE
D28K:T32F
['D28K', 'T32F']
HERE
D28K:T32P
['D28K', 'T32P']
HERE
D28T:T32Q
['D28T', 'T32Q']
HERE
D28T:T32E
['D28T', 'T32E']
HERE
D28T:T32N
['D28T', 'T32N']
HERE
D28T:T32H
['D28T', 'T32H']
HERE
D28T:T32D
['D28T', 'T32D']
HERE
D28T:T32R
['D28T', 'T32R']
HERE
D28T:T32K
['D28T', 'T32K']
HERE
D28T:T32T
['D28T']
HERE
D28T:T32S
['D28T', 'T32S']
HERE
D28T:T32A
['D28T', 'T32A']
HERE
D28T:T32G
['D28T', 'T32G']
HERE
D28T:T32M
['D28T', 'T32M']
HERE
D28T:T32L
['D28T', 'T32L']
HERE
D28T:T32V
['D28T', 'T32V']
HERE
D28T:T32I
['D28T', 'T32I']
HERE
D28T:T32W
['D28T', 'T32W']
HERE
D28T:T32Y
['D28T', 'T32Y']
HERE
D28T:T32F
['D28T', 'T32F']
HERE
D28T:T32P
['D28T', 'T32P']
HERE
D28S:T32Q
['D28S', 'T32Q']
HERE
D28S:T32E
['D28S', 'T32E']
HERE
D28S:T32N
['D28S', 'T32N']
HERE
D28S:T32H
['D28S', 'T32H']
HERE
D28S:T32D
['D28S', 'T32D']
HERE
D28S:T32R
['D28S', 'T32R']
HERE
D28S:T32K
['D28S', 'T32K']
HERE
D28S:T32T
['D28S']
HERE
D28S:T32S
['D28S', 'T32S']
HERE
D28S:T32A
['D28S', 'T32A']
HERE
D28S:T32G
['D28S', 'T32G']
HERE
D28S:T32M
['D28S', 'T32M']
HERE
D28S:T32L
['D28S', 'T32L']
HERE
D28S:T32V
['D28S', 'T32V']
HERE
D28S:T32I
['D28S', 'T32I']
HERE
D28S:T32W
['D28S', 'T32W']
HERE
D28S:T32Y
['D28S', 'T32Y']
HERE
D28S:T32F
['D28S', 'T32F']
HERE
D28S:T32P
['D28S', 'T32P']
HERE
D28A:T32Q
['D28A', 'T32Q']
HERE
D28A:T32E
['D28A', 'T32E']
HERE
D28A:T32N
['D28A', 'T32N']
HERE
D28A:T32H
['D28A', 'T32H']
HERE
D28A:T32D
['D28A', 'T32D']
HERE
D28A:T32R
['D28A', 'T32R']
HERE
D28A:T32K
['D28A', 'T32K']
HERE
D28A:T32T
['D28A']
HERE
D28A:T32S
['D28A', 'T32S']
HERE
D28A:T32A
['D28A', 'T32A']
HERE
D28A:T32G
['D28A', 'T32G']
HERE
D28A:T32M
['D28A', 'T32M']
HERE
D28A:T32L
['D28A', 'T32L']
HERE
D28A:T32V
['D28A', 'T32V']
HERE
D28A:T32I
['D28A', 'T32I']
HERE
D28A:T32W
['D28A', 'T32W']
HERE
D28A:T32Y
['D28A', 'T32Y']
HERE
D28A:T32F
['D28A', 'T32F']
HERE
D28A:T32P
['D28A', 'T32P']
HERE
D28G:T32Q
['D28G', 'T32Q']
HERE
D28G:T32E
['D28G', 'T32E']
HERE
D28G:T32N
['D28G', 'T32N']
HERE
D28G:T32H
['D28G', 'T32H']
HERE
D28G:T32D
['D28G', 'T32D']
HERE
D28G:T32R
['D28G', 'T32R']
HERE
D28G:T32K
['D28G', 'T32K']
HERE
D28G:T32T
['D28G']
HERE
D28G:T32S
['D28G', 'T32S']
HERE
D28G:T32A
['D28G', 'T32A']
HERE
D28G:T32G
['D28G', 'T32G']
HERE
D28G:T32M
['D28G', 'T32M']
HERE
D28G:T32L
['D28G', 'T32L']
HERE
D28G:T32V
['D28G', 'T32V']
HERE
D28G:T32I
['D28G', 'T32I']
HERE
D28G:T32W
['D28G', 'T32W']
HERE
D28G:T32Y
['D28G', 'T32Y']
HERE
D28G:T32F
['D28G', 'T32F']
HERE
D28G:T32P
['D28G', 'T32P']
HERE
D28M:T32Q
['D28M', 'T32Q']
HERE
D28M:T32E
['D28M', 'T32E']
HERE
D28M:T32N
['D28M', 'T32N']
HERE
D28M:T32H
['D28M', 'T32H']
HERE
D28M:T32D
['D28M', 'T32D']
HERE
D28M:T32R
['D28M', 'T32R']
HERE
D28M:T32K
['D28M', 'T32K']
HERE
D28M:T32T
['D28M']
HERE
D28M:T32S
['D28M', 'T32S']
HERE
D28M:T32A
['D28M', 'T32A']
HERE
D28M:T32G
['D28M', 'T32G']
HERE
D28M:T32M
['D28M', 'T32M']
HERE
D28M:T32L
['D28M', 'T32L']
HERE
D28M:T32V
['D28M', 'T32V']
HERE
D28M:T32I
['D28M', 'T32I']
HERE
D28M:T32W
['D28M', 'T32W']
HERE
D28M:T32Y
['D28M', 'T32Y']
HERE
D28M:T32F
['D28M', 'T32F']
HERE
D28M:T32P
['D28M', 'T32P']
HERE
D28L:T32Q
['D28L', 'T32Q']
HERE
D28L:T32E
['D28L', 'T32E']
HERE
D28L:T32N
['D28L', 'T32N']
HERE
D28L:T32H
['D28L', 'T32H']
HERE
D28L:T32D
['D28L', 'T32D']
HERE
D28L:T32R
['D28L', 'T32R']
HERE
D28L:T32K
['D28L', 'T32K']
HERE
D28L:T32T
['D28L']
HERE
D28L:T32S
['D28L', 'T32S']
HERE
D28L:T32A
['D28L', 'T32A']
HERE
D28L:T32G
['D28L', 'T32G']
HERE
D28L:T32M
['D28L', 'T32M']
HERE
D28L:T32L
['D28L', 'T32L']
HERE
D28L:T32V
['D28L', 'T32V']
HERE
D28L:T32I
['D28L', 'T32I']
HERE
D28L:T32W
['D28L', 'T32W']
HERE
D28L:T32Y
['D28L', 'T32Y']
HERE
D28L:T32F
['D28L', 'T32F']
HERE
D28L:T32P
['D28L', 'T32P']
HERE
D28V:T32Q
['D28V', 'T32Q']
HERE
D28V:T32E
['D28V', 'T32E']
HERE
D28V:T32N
['D28V', 'T32N']
HERE
D28V:T32H
['D28V', 'T32H']
HERE
D28V:T32D
['D28V', 'T32D']
HERE
D28V:T32R
['D28V', 'T32R']
HERE
D28V:T32K
['D28V', 'T32K']
HERE
D28V:T32T
['D28V']
HERE
D28V:T32S
['D28V', 'T32S']
HERE
D28V:T32A
['D28V', 'T32A']
HERE
D28V:T32G
['D28V', 'T32G']
HERE
D28V:T32M
['D28V', 'T32M']
HERE
D28V:T32L
['D28V', 'T32L']
HERE
D28V:T32V
['D28V', 'T32V']
HERE
D28V:T32I
['D28V', 'T32I']
HERE
D28V:T32W
['D28V', 'T32W']
HERE
D28V:T32Y
['D28V', 'T32Y']
HERE
D28V:T32F
['D28V', 'T32F']
HERE
D28V:T32P
['D28V', 'T32P']
HERE
D28I:T32Q
['D28I', 'T32Q']
HERE
D28I:T32E
['D28I', 'T32E']
HERE
D28I:T32N
['D28I', 'T32N']
HERE
D28I:T32H
['D28I', 'T32H']
HERE
D28I:T32D
['D28I', 'T32D']
HERE
D28I:T32R
['D28I', 'T32R']
HERE
D28I:T32K
['D28I', 'T32K']
HERE
D28I:T32T
['D28I']
HERE
D28I:T32S
['D28I', 'T32S']
HERE
D28I:T32A
['D28I', 'T32A']
HERE
D28I:T32G
['D28I', 'T32G']
HERE
D28I:T32M
['D28I', 'T32M']
HERE
D28I:T32L
['D28I', 'T32L']
HERE
D28I:T32V
['D28I', 'T32V']
HERE
D28I:T32I
['D28I', 'T32I']
HERE
D28I:T32W
['D28I', 'T32W']
HERE
D28I:T32Y
['D28I', 'T32Y']
HERE
D28I:T32F
['D28I', 'T32F']
HERE
D28I:T32P
['D28I', 'T32P']
HERE
D28W:T32Q
['D28W', 'T32Q']
HERE
D28W:T32E
['D28W', 'T32E']
HERE
D28W:T32N
['D28W', 'T32N']
HERE
D28W:T32H
['D28W', 'T32H']
HERE
D28W:T32D
['D28W', 'T32D']
HERE
D28W:T32R
['D28W', 'T32R']
HERE
D28W:T32K
['D28W', 'T32K']
HERE
D28W:T32T
['D28W']
HERE
D28W:T32S
['D28W', 'T32S']
HERE
D28W:T32A
['D28W', 'T32A']
HERE
D28W:T32G
['D28W', 'T32G']
HERE
D28W:T32M
['D28W', 'T32M']
HERE
D28W:T32L
['D28W', 'T32L']
HERE
D28W:T32V
['D28W', 'T32V']
HERE
D28W:T32I
['D28W', 'T32I']
HERE
D28W:T32W
['D28W', 'T32W']
HERE
D28W:T32Y
['D28W', 'T32Y']
HERE
D28W:T32F
['D28W', 'T32F']
HERE
D28W:T32P
['D28W', 'T32P']
HERE
D28Y:T32Q
['D28Y', 'T32Q']
HERE
D28Y:T32E
['D28Y', 'T32E']
HERE
D28Y:T32N
['D28Y', 'T32N']
HERE
D28Y:T32H
['D28Y', 'T32H']
HERE
D28Y:T32D
['D28Y', 'T32D']
HERE
D28Y:T32R
['D28Y', 'T32R']
HERE
D28Y:T32K
['D28Y', 'T32K']
HERE
D28Y:T32T
['D28Y']
HERE
D28Y:T32S
['D28Y', 'T32S']
HERE
D28Y:T32A
['D28Y', 'T32A']
HERE
D28Y:T32G
['D28Y', 'T32G']
HERE
D28Y:T32M
['D28Y', 'T32M']
HERE
D28Y:T32L
['D28Y', 'T32L']
HERE
D28Y:T32V
['D28Y', 'T32V']
HERE
D28Y:T32I
['D28Y', 'T32I']
HERE
D28Y:T32W
['D28Y', 'T32W']
HERE
D28Y:T32Y
['D28Y', 'T32Y']
HERE
D28Y:T32F
['D28Y', 'T32F']
HERE
D28Y:T32P
['D28Y', 'T32P']
HERE
D28F:T32Q
['D28F', 'T32Q']
HERE
D28F:T32E
['D28F', 'T32E']
HERE
D28F:T32N
['D28F', 'T32N']
HERE
D28F:T32H
['D28F', 'T32H']
HERE
D28F:T32D
['D28F', 'T32D']
HERE
D28F:T32R
['D28F', 'T32R']
HERE
D28F:T32K
['D28F', 'T32K']
HERE
D28F:T32T
['D28F']
HERE
D28F:T32S
['D28F', 'T32S']
HERE
D28F:T32A
['D28F', 'T32A']
HERE
D28F:T32G
['D28F', 'T32G']
HERE
D28F:T32M
['D28F', 'T32M']
HERE
D28F:T32L
['D28F', 'T32L']
HERE
D28F:T32V
['D28F', 'T32V']
HERE
D28F:T32I
['D28F', 'T32I']
HERE
D28F:T32W
['D28F', 'T32W']
HERE
D28F:T32Y
['D28F', 'T32Y']
HERE
D28F:T32F
['D28F', 'T32F']
HERE
D28F:T32P
['D28F', 'T32P']
HERE
D28P:T32E
['D28P', 'T32E']
HERE
D28P:T32N
['D28P', 'T32N']
HERE
D28P:T32H
['D28P', 'T32H']
HERE
D28P:T32D
['D28P', 'T32D']
HERE
D28P:T32T
['D28P']
HERE
D28P:T32A
['D28P', 'T32A']
HERE
D28P:T32M
['D28P', 'T32M']
HERE
D28P:T32L
['D28P', 'T32L']
HERE
D28P:T32V
['D28P', 'T32V']
HERE
D28P:T32I
['D28P', 'T32I']
HERE
D28P:T32W
['D28P', 'T32W']
HERE
D28P:T32Y
['D28P', 'T32Y']
HERE
D28P:T32F
['D28P', 'T32F']
HERE
D28P:T32P
['D28P', 'T32P']
HERE
D28Q:T38Q
['D28Q', 'T38Q']
HERE
D28Q:T38E
['D28Q', 'T38E']
HERE
D28Q:T38N
['D28Q', 'T38N']
HERE
D28Q:T38H
['D28Q', 'T38H']
HERE
D28Q:T38D
['D28Q', 'T38D']
HERE
D28Q:T38R
['D28Q', 'T38R']
HERE
D28Q:T38K
['D28Q', 'T38K']
HERE
D28Q:T38T
['D28Q']
HERE
D28Q:T38S
['D28Q', 'T38S']
HERE
D28Q:T38A
['D28Q', 'T38A']
HERE
D28Q:T38G
['D28Q', 'T38G']
HERE
D28Q:T38M
['D28Q', 'T38M']
HERE
D28Q:T38L
['D28Q', 'T38L']
HERE
D28Q:T38V
['D28Q', 'T38V']
HERE
D28Q:T38I
['D28Q', 'T38I']
HERE
D28Q:T38W
['D28Q', 'T38W']
HERE
D28Q:T38Y
['D28Q', 'T38Y']
HERE
D28Q:T38F
['D28Q', 'T38F']
HERE
D28Q:T38P
['D28Q', 'T38P']
HERE
D28E:T38Q
['D28E', 'T38Q']
HERE
D28E:T38E
['D28E', 'T38E']
HERE
D28E:T38N
['D28E', 'T38N']
HERE
D28E:T38H
['D28E', 'T38H']
HERE
D28E:T38D
['D28E', 'T38D']
HERE
D28E:T38R
['D28E', 'T38R']
HERE
D28E:T38K
['D28E', 'T38K']
HERE
D28E:T38T
['D28E']
HERE
D28E:T38S
['D28E', 'T38S']
HERE
D28E:T38A
['D28E', 'T38A']
HERE
D28E:T38G
['D28E', 'T38G']
HERE
D28E:T38M
['D28E', 'T38M']
HERE
D28E:T38L
['D28E', 'T38L']
HERE
D28E:T38V
['D28E', 'T38V']
HERE
D28E:T38I
['D28E', 'T38I']
HERE
D28E:T38W
['D28E', 'T38W']
HERE
D28E:T38Y
['D28E', 'T38Y']
HERE
D28E:T38F
['D28E', 'T38F']
HERE
D28E:T38P
['D28E', 'T38P']
HERE
D28N:T38Q
['D28N', 'T38Q']
HERE
D28N:T38E
['D28N', 'T38E']
HERE
D28N:T38N
['D28N', 'T38N']
HERE
D28N:T38H
['D28N', 'T38H']
HERE
D28N:T38D
['D28N', 'T38D']
HERE
D28N:T38R
['D28N', 'T38R']
HERE
D28N:T38K
['D28N', 'T38K']
HERE
D28N:T38T
['D28N']
HERE
D28N:T38S
['D28N', 'T38S']
HERE
D28N:T38A
['D28N', 'T38A']
HERE
D28N:T38G
['D28N', 'T38G']
HERE
D28N:T38M
['D28N', 'T38M']
HERE
D28N:T38L
['D28N', 'T38L']
HERE
D28N:T38V
['D28N', 'T38V']
HERE
D28N:T38I
['D28N', 'T38I']
HERE
D28N:T38W
['D28N', 'T38W']
HERE
D28N:T38Y
['D28N', 'T38Y']
HERE
D28N:T38F
['D28N', 'T38F']
HERE
D28H:T38Q
['D28H', 'T38Q']
HERE
D28H:T38E
['D28H', 'T38E']
HERE
D28H:T38N
['D28H', 'T38N']
HERE
D28H:T38H
['D28H', 'T38H']
HERE
D28H:T38D
['D28H', 'T38D']
HERE
D28H:T38R
['D28H', 'T38R']
HERE
D28H:T38K
['D28H', 'T38K']
HERE
D28H:T38T
['D28H']
HERE
D28H:T38S
['D28H', 'T38S']
HERE
D28H:T38A
['D28H', 'T38A']
HERE
D28H:T38G
['D28H', 'T38G']
HERE
D28H:T38M
['D28H', 'T38M']
HERE
D28H:T38L
['D28H', 'T38L']
HERE
D28H:T38V
['D28H', 'T38V']
HERE
D28H:T38I
['D28H', 'T38I']
HERE
D28H:T38W
['D28H', 'T38W']
HERE
D28H:T38Y
['D28H', 'T38Y']
HERE
D28H:T38F
['D28H', 'T38F']
HERE
D28H:T38P
['D28H', 'T38P']
HERE
D28D:T38Q
['T38Q']
HERE
D28D:T38E
['T38E']
HERE
D28D:T38N
['T38N']
HERE
D28D:T38H
['T38H']
HERE
D28D:T38D
['T38D']
HERE
D28D:T38K
['T38K']
HERE
D28D:T38S
['T38S']
HERE
D28D:T38A
['T38A']
HERE
D28D:T38L
['T38L']
HERE
D28D:T38V
['T38V']
HERE
D28D:T38I
['T38I']
HERE
D28D:T38W
['T38W']
HERE
D28D:T38Y
['T38Y']
HERE
D28D:T38F
['T38F']
HERE
D28R:T38Q
['D28R', 'T38Q']
HERE
D28R:T38E
['D28R', 'T38E']
HERE
D28R:T38N
['D28R', 'T38N']
HERE
D28R:T38H
['D28R', 'T38H']
HERE
D28R:T38D
['D28R', 'T38D']
HERE
D28R:T38R
['D28R', 'T38R']
HERE
D28R:T38K
['D28R', 'T38K']
HERE
D28R:T38T
['D28R']
HERE
D28R:T38S
['D28R', 'T38S']
HERE
D28R:T38A
['D28R', 'T38A']
HERE
D28R:T38G
['D28R', 'T38G']
HERE
D28R:T38M
['D28R', 'T38M']
HERE
D28R:T38L
['D28R', 'T38L']
HERE
D28R:T38V
['D28R', 'T38V']
HERE
D28R:T38I
['D28R', 'T38I']
HERE
D28R:T38W
['D28R', 'T38W']
HERE
D28R:T38Y
['D28R', 'T38Y']
HERE
D28R:T38F
['D28R', 'T38F']
HERE
D28R:T38P
['D28R', 'T38P']
HERE
D28K:T38Q
['D28K', 'T38Q']
HERE
D28K:T38E
['D28K', 'T38E']
HERE
D28K:T38N
['D28K', 'T38N']
HERE
D28K:T38H
['D28K', 'T38H']
HERE
D28K:T38D
['D28K', 'T38D']
HERE
D28K:T38R
['D28K', 'T38R']
HERE
D28K:T38K
['D28K', 'T38K']
HERE
D28K:T38T
['D28K']
HERE
D28K:T38S
['D28K', 'T38S']
HERE
D28K:T38A
['D28K', 'T38A']
HERE
D28K:T38G
['D28K', 'T38G']
HERE
D28K:T38M
['D28K', 'T38M']
HERE
D28K:T38L
['D28K', 'T38L']
HERE
D28K:T38V
['D28K', 'T38V']
HERE
D28K:T38I
['D28K', 'T38I']
HERE
D28K:T38W
['D28K', 'T38W']
HERE
D28K:T38Y
['D28K', 'T38Y']
HERE
D28K:T38F
['D28K', 'T38F']
HERE
D28K:T38P
['D28K', 'T38P']
HERE
D28T:T38Q
['D28T', 'T38Q']
HERE
D28T:T38E
['D28T', 'T38E']
HERE
D28T:T38N
['D28T', 'T38N']
HERE
D28T:T38H
['D28T', 'T38H']
HERE
D28T:T38D
['D28T', 'T38D']
HERE
D28T:T38R
['D28T', 'T38R']
HERE
D28T:T38K
['D28T', 'T38K']
HERE
D28T:T38T
['D28T']
HERE
D28T:T38S
['D28T', 'T38S']
HERE
D28T:T38A
['D28T', 'T38A']
HERE
D28T:T38G
['D28T', 'T38G']
HERE
D28T:T38M
['D28T', 'T38M']
HERE
D28T:T38L
['D28T', 'T38L']
HERE
D28T:T38V
['D28T', 'T38V']
HERE
D28T:T38I
['D28T', 'T38I']
HERE
D28T:T38W
['D28T', 'T38W']
HERE
D28T:T38Y
['D28T', 'T38Y']
HERE
D28T:T38F
['D28T', 'T38F']
HERE
D28T:T38P
['D28T', 'T38P']
HERE
D28S:T38Q
['D28S', 'T38Q']
HERE
D28S:T38E
['D28S', 'T38E']
HERE
D28S:T38N
['D28S', 'T38N']
HERE
D28S:T38H
['D28S', 'T38H']
HERE
D28S:T38D
['D28S', 'T38D']
HERE
D28S:T38R
['D28S', 'T38R']
HERE
D28S:T38K
['D28S', 'T38K']
HERE
D28S:T38T
['D28S']
HERE
D28S:T38S
['D28S', 'T38S']
HERE
D28S:T38A
['D28S', 'T38A']
HERE
D28S:T38G
['D28S', 'T38G']
HERE
D28S:T38M
['D28S', 'T38M']
HERE
D28S:T38L
['D28S', 'T38L']
HERE
D28S:T38V
['D28S', 'T38V']
HERE
D28S:T38I
['D28S', 'T38I']
HERE
D28S:T38W
['D28S', 'T38W']
HERE
D28S:T38Y
['D28S', 'T38Y']
HERE
D28S:T38F
['D28S', 'T38F']
HERE
D28S:T38P
['D28S', 'T38P']
HERE
D28A:T38Q
['D28A', 'T38Q']
HERE
D28A:T38E
['D28A', 'T38E']
HERE
D28A:T38N
['D28A', 'T38N']
HERE
D28A:T38H
['D28A', 'T38H']
HERE
D28A:T38D
['D28A', 'T38D']
HERE
D28A:T38R
['D28A', 'T38R']
HERE
D28A:T38K
['D28A', 'T38K']
HERE
D28A:T38T
['D28A']
HERE
D28A:T38S
['D28A', 'T38S']
HERE
D28A:T38A
['D28A', 'T38A']
HERE
D28A:T38G
['D28A', 'T38G']
HERE
D28A:T38M
['D28A', 'T38M']
HERE
D28A:T38L
['D28A', 'T38L']
HERE
D28A:T38V
['D28A', 'T38V']
HERE
D28A:T38I
['D28A', 'T38I']
HERE
D28A:T38W
['D28A', 'T38W']
HERE
D28A:T38Y
['D28A', 'T38Y']
HERE
D28A:T38F
['D28A', 'T38F']
HERE
D28A:T38P
['D28A', 'T38P']
HERE
D28G:T38Q
['D28G', 'T38Q']
HERE
D28G:T38E
['D28G', 'T38E']
HERE
D28G:T38N
['D28G', 'T38N']
HERE
D28G:T38H
['D28G', 'T38H']
HERE
D28G:T38D
['D28G', 'T38D']
HERE
D28G:T38R
['D28G', 'T38R']
HERE
D28G:T38K
['D28G', 'T38K']
HERE
D28G:T38T
['D28G']
HERE
D28G:T38S
['D28G', 'T38S']
HERE
D28G:T38A
['D28G', 'T38A']
HERE
D28G:T38G
['D28G', 'T38G']
HERE
D28G:T38M
['D28G', 'T38M']
HERE
D28G:T38L
['D28G', 'T38L']
HERE
D28G:T38V
['D28G', 'T38V']
HERE
D28G:T38I
['D28G', 'T38I']
HERE
D28G:T38W
['D28G', 'T38W']
HERE
D28G:T38Y
['D28G', 'T38Y']
HERE
D28G:T38F
['D28G', 'T38F']
HERE
D28G:T38P
['D28G', 'T38P']
HERE
D28M:T38Q
['D28M', 'T38Q']
HERE
D28M:T38E
['D28M', 'T38E']
HERE
D28M:T38N
['D28M', 'T38N']
HERE
D28M:T38H
['D28M', 'T38H']
HERE
D28M:T38D
['D28M', 'T38D']
HERE
D28M:T38R
['D28M', 'T38R']
HERE
D28M:T38K
['D28M', 'T38K']
HERE
D28M:T38T
['D28M']
HERE
D28M:T38S
['D28M', 'T38S']
HERE
D28M:T38A
['D28M', 'T38A']
HERE
D28M:T38G
['D28M', 'T38G']
HERE
D28M:T38M
['D28M', 'T38M']
HERE
D28M:T38L
['D28M', 'T38L']
HERE
D28M:T38V
['D28M', 'T38V']
HERE
D28M:T38I
['D28M', 'T38I']
HERE
D28M:T38W
['D28M', 'T38W']
HERE
D28M:T38Y
['D28M', 'T38Y']
HERE
D28M:T38F
['D28M', 'T38F']
HERE
D28M:T38P
['D28M', 'T38P']
HERE
D28L:T38Q
['D28L', 'T38Q']
HERE
D28L:T38E
['D28L', 'T38E']
HERE
D28L:T38N
['D28L', 'T38N']
HERE
D28L:T38H
['D28L', 'T38H']
HERE
D28L:T38D
['D28L', 'T38D']
HERE
D28L:T38R
['D28L', 'T38R']
HERE
D28L:T38K
['D28L', 'T38K']
HERE
D28L:T38T
['D28L']
HERE
D28L:T38S
['D28L', 'T38S']
HERE
D28L:T38A
['D28L', 'T38A']
HERE
D28L:T38G
['D28L', 'T38G']
HERE
D28L:T38M
['D28L', 'T38M']
HERE
D28L:T38L
['D28L', 'T38L']
HERE
D28L:T38V
['D28L', 'T38V']
HERE
D28L:T38I
['D28L', 'T38I']
HERE
D28L:T38W
['D28L', 'T38W']
HERE
D28L:T38Y
['D28L', 'T38Y']
HERE
D28L:T38F
['D28L', 'T38F']
HERE
D28L:T38P
['D28L', 'T38P']
HERE
D28V:T38Q
['D28V', 'T38Q']
HERE
D28V:T38E
['D28V', 'T38E']
HERE
D28V:T38N
['D28V', 'T38N']
HERE
D28V:T38H
['D28V', 'T38H']
HERE
D28V:T38D
['D28V', 'T38D']
HERE
D28V:T38R
['D28V', 'T38R']
HERE
D28V:T38K
['D28V', 'T38K']
HERE
D28V:T38T
['D28V']
HERE
D28V:T38S
['D28V', 'T38S']
HERE
D28V:T38A
['D28V', 'T38A']
HERE
D28V:T38G
['D28V', 'T38G']
HERE
D28V:T38M
['D28V', 'T38M']
HERE
D28V:T38L
['D28V', 'T38L']
HERE
D28V:T38V
['D28V', 'T38V']
HERE
D28V:T38I
['D28V', 'T38I']
HERE
D28V:T38W
['D28V', 'T38W']
HERE
D28V:T38Y
['D28V', 'T38Y']
HERE
D28V:T38F
['D28V', 'T38F']
HERE
D28V:T38P
['D28V', 'T38P']
HERE
D28I:T38Q
['D28I', 'T38Q']
HERE
D28I:T38E
['D28I', 'T38E']
HERE
D28I:T38N
['D28I', 'T38N']
HERE
D28I:T38H
['D28I', 'T38H']
HERE
D28I:T38D
['D28I', 'T38D']
HERE
D28I:T38R
['D28I', 'T38R']
HERE
D28I:T38K
['D28I', 'T38K']
HERE
D28I:T38T
['D28I']
HERE
D28I:T38S
['D28I', 'T38S']
HERE
D28I:T38A
['D28I', 'T38A']
HERE
D28I:T38G
['D28I', 'T38G']
HERE
D28I:T38M
['D28I', 'T38M']
HERE
D28I:T38L
['D28I', 'T38L']
HERE
D28I:T38V
['D28I', 'T38V']
HERE
D28I:T38I
['D28I', 'T38I']
HERE
D28I:T38W
['D28I', 'T38W']
HERE
D28I:T38Y

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A10C,YFQGQLNAMCHQIQEMFPQVPYHLVLQDLQLTRSVEITTDNILEGRI,-1.299780,1
1,A10F,YFQGQLNAMFHQIQEMFPQVPYHLVLQDLQLTRSVEITTDNILEGRI,-1.066926,1
2,A10G,YFQGQLNAMGHQIQEMFPQVPYHLVLQDLQLTRSVEITTDNILEGRI,-1.843024,0
3,A10H,YFQGQLNAMHHQIQEMFPQVPYHLVLQDLQLTRSVEITTDNILEGRI,-2.299680,0
4,A10I,YFQGQLNAMIHQIQEMFPQVPYHLVLQDLQLTRSVEITTDNILEGRI,-0.387281,1
...,...,...,...,...
2967,Y22R,YFQGQLNAMAHQIQEMFPQVPRHLVLQDLQLTRSVEITTDNILEGRI,-0.747871,1
2968,Y22S,YFQGQLNAMAHQIQEMFPQVPSHLVLQDLQLTRSVEITTDNILEGRI,-1.266067,1
2969,Y22T,YFQGQLNAMAHQIQEMFPQVPTHLVLQDLQLTRSVEITTDNILEGRI,-1.103759,1
2970,Y22V,YFQGQLNAMAHQIQEMFPQVPVHLVLQDLQLTRSVEITTDNILEGRI,-0.908841,1
2971,Y22W,YFQGQLNAMAHQIQEMFPQVPWHLVLQDLQLTRSVEITTDNILEGRI,-0.147079,1

In [11]:
overwrite = True
overwrite = input("Are you sure you want to overwrite the directory? (y/n)").upper() == "Y"

Are you sure you want to overwrite the directory? (y/n) Y

In [13]:
# Process each DMS and drop in folder
# TODO skip_existing of same length file?
# TODO some files with multiple phenotypes might just be DMS_id.csv, should be able to use them too ideally
# assert overwrite, "Not overwriting"
keep_versions = ["1"]
processed_list = os.listdir(dms_processed_folder_out)
# to_reprocess = """
# F7YBW7_MESOW_Ding_2023
# AMFR_HUMAN_Rocklin_2023_4G3O
# BBC1_YEAST_Rocklin_2023_1TG0
# BCHB_CHLTE_Rocklin_2023_2KRU
# CATR_CHLRE_Rocklin_2023_2AMI
# CBPA2_HUMAN_Rocklin_2023_1O6X
# CBX4_HUMAN_Rocklin_2023_2K28
# CSN4_MOUSE_Rocklin_2023_1UFM
# CUE1_YEAST_Rocklin_2023_2MYX
# DNJA1_HUMAN_Rocklin_2023_2LO1
# DOCK1_MOUSE_Rocklin_2023_2M0Y
# EPHB2_HUMAN_Rocklin_2023_1F0M
# FECA_ECOLI_Rocklin_2023_2D1U
# HECD1_HUMAN_Rocklin_2023_3DKM
# ISDH_STAAW_Rocklin_2023_2LHR
# MAFG_MOUSE_Rocklin_2023_1K1V
# MBD11_ARATH_Rocklin_2023_6ACV
# MYO3_YEAST_Rocklin_2023_2BTT
# NKX31_HUMAN_Rocklin_2023_2L9R
# NUSA_ECOLI_Rocklin_2023_1WCL
# NUSG_MYCTU_Rocklin_2023_2MI6
# OBSCN_HUMAN_Rocklin_2023_1V1C
# ODP2_GEOSE_Rocklin_2023_1W4G
# PIN1_HUMAN_Rocklin_2023_1I6C
# PITX2_HUMAN_Rocklin_2023_2L7M
# POLG_PESV_Rocklin_2023_2MXD
# PR40A_HUMAN_Rocklin_2023_1UZC
# PSAE_SYNP2_Rocklin_2023_1PSE
# RAD_ANTMA_Rocklin_2023_2CJJ
# RBP1_HUMAN_Rocklin_2023_2KWH
# RCD1_ARATH_Rocklin_2023_5OAO
# RCRO_LAMBD_Rocklin_2023_1ORC
# RD23A_HUMAN_Rocklin_2023_1IFY
# RFAH_ECOLI_Rocklin_2023_2LCL
# RL20_AQUAE_Rocklin_2023_1GYZ
# RPC1_BP434_Rocklin_2023_1R69
# SAV1_MOUSE_Rocklin_2023_2YSB
# SDA_BACSU_Rocklin_2023_1PV0
# SPA_STAAU_Rocklin_2023_1LP1
# SPG2_STRSG_Rocklin_2023_5UBS
# SPTN1_CHICK_Rocklin_2023_1TUD
# SR43C_ARATH_Rocklin_2023_2N88
# SRBS1_HUMAN_Rocklin_2023_2O2W
# TCRG1_MOUSE_Rocklin_2023_1E0L
# THO1_YEAST_Rocklin_2023_2WQG
# TNKS2_HUMAN_Rocklin_2023_5JRT
# UBE4B_HUMAN_Rocklin_2023_3L1X
# UBR5_HUMAN_Rocklin_2023_1I2T
# VILI_CHICK_Rocklin_2023_1YU5
# YAIA_ECOLI_Rocklin_2023_2KVT
# YNZC_BACSU_Rocklin_2023_2JVD
# """.split("\n")
pbar = tqdm(ref_df[ref_df["ProteinGym_version"] == 1].dropna(subset=necessary_cols, how='any').iterrows())
# pbar = tqdm(ref_df[ref_df["DMS_id"].isin(to_reprocess)].dropna(subset=necessary_cols,how='any').iterrows())
for i, row in pbar:
    pbar.set_postfix_str(row["DMS_filename"])
    if row["DMS_filename"] in processed_list and not overwrite:
        print(f"{row['DMS_filename']} is already processed. Skipping")
        continue 
    print(row["DMS_filename"])
    # This row was removed
    if row["DMS_id"] in ["HXK4_HUMAN_Gersing_2023_activity"]:
        print(f"Skipping {row['DMS_id']}")
        continue
    filename = dms_preprocessed_folder + "/" + row["DMS_filename"]
    if not os.path.isfile(filename):
        print("Missing file: "+filename)
        continue
    dest = dms_processed_folder_out + "/" + row["DMS_filename"]
    if os.path.isfile(dest) and not overwrite:
        print(f"File already exists: {dest}")
        continue
    tmp_df = pd.read_csv(filename)
    assert not len(tmp_df) == 0

    # Ignoring start and end seq
    tmp_df_clean = DMS_file_cleanup(filename, target_seq=row["target_seq"], DMS_binarization_threshold=row["DMS_binarization_cutoff"], DMS_mutant_column=row["raw_DMS_mutant_column"], DMS_phenotype_name=row["raw_DMS_phenotype_name"], DMS_directionality=row["raw_DMS_directionality"], debug=True, strict_wt_check=True)
    display(tmp_df_clean)
    # Write out to processed folder
    tmp_df_clean.to_csv(dest, index=False)

print("Done")

0it [00:00, ?it/s]

F7YBW7_MESOW_Ding_2023.csv
Number of dropped mutant formats: 0 / 10656 = 0.0%
Number of dropped invalid amino acids: 2620 / 10656 = 24.6%
Number of dropped synonymous mutants: 16 / 10656 = 0.2%
Number of dropped mutants not matching WT: 0 / 10656 = 0.0%
Dropped mutants: Length before: 10656, length after: 8020: 24.7% dropped
Warning: Dropped more than 10% of mutants. This may indicate a problem with the DMS data.
Debug: Number of duplicate mutants: 98 (1.22%)
Final length: 7922

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A81D,MANVEKMSVAVTPQQAAVMREAVEAGEYATASEIVREAVRDWLAKR...,0.883542,1
1,A81D:R82G,MANVEKMSVAVTPQQAAVMREAVEAGEYATASEIVREAVRDWLAKR...,0.107614,0
2,A81F:R82D,MANVEKMSVAVTPQQAAVMREAVEAGEYATASEIVREAVRDWLAKR...,0.715109,1
3,A81G,MANVEKMSVAVTPQQAAVMREAVEAGEYATASEIVREAVRDWLAKR...,0.932408,1
4,A81K:R82K,MANVEKMSVAVTPQQAAVMREAVEAGEYATASEIVREAVRDWLAKR...,0.266513,0
...,...,...,...,...
7917,R82G,MANVEKMSVAVTPQQAAVMREAVEAGEYATASEIVREAVRDWLAKR...,0.954072,1
7918,R82L,MANVEKMSVAVTPQQAAVMREAVEAGEYATASEIVREAVRDWLAKR...,0.980336,1
7919,R82P,MANVEKMSVAVTPQQAAVMREAVEAGEYATASEIVREAVRDWLAKR...,0.868006,1
7920,R82Q,MANVEKMSVAVTPQQAAVMREAVEAGEYATASEIVREAVRDWLAKR...,1.027203,1
7921,R82W,MANVEKMSVAVTPQQAAVMREAVEAGEYATASEIVREAVRDWLAKR...,0.968826,1

AMFR_HUMAN_Rocklin_2023_4G3O.csv
Number of dropped mutant formats: 5 / 4039 = 0.1%
Number of dropped invalid amino acids: 5 / 4039 = 0.1%
Number of dropped synonymous mutants: 11 / 4039 = 0.3%
Number of dropped mutants not matching WT: 0 / 4039 = 0.0%
Dropped mutants: Length before: 4039, length after: 4023: 0.4% dropped
Debug: Number of duplicate mutants: 1051 (26.12%)
Final length: 2972

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A10C,YFQGQLNAMCHQIQEMFPQVPYHLVLQDLQLTRSVEITTDNILEGRI,-1.299780,1
1,A10F,YFQGQLNAMFHQIQEMFPQVPYHLVLQDLQLTRSVEITTDNILEGRI,-1.066926,1
2,A10G,YFQGQLNAMGHQIQEMFPQVPYHLVLQDLQLTRSVEITTDNILEGRI,-1.843024,0
3,A10H,YFQGQLNAMHHQIQEMFPQVPYHLVLQDLQLTRSVEITTDNILEGRI,-2.299680,0
4,A10I,YFQGQLNAMIHQIQEMFPQVPYHLVLQDLQLTRSVEITTDNILEGRI,-0.387281,1
...,...,...,...,...
2967,Y22R,YFQGQLNAMAHQIQEMFPQVPRHLVLQDLQLTRSVEITTDNILEGRI,-0.747871,1
2968,Y22S,YFQGQLNAMAHQIQEMFPQVPSHLVLQDLQLTRSVEITTDNILEGRI,-1.266067,1
2969,Y22T,YFQGQLNAMAHQIQEMFPQVPTHLVLQDLQLTRSVEITTDNILEGRI,-1.103759,1
2970,Y22V,YFQGQLNAMAHQIQEMFPQVPVHLVLQDLQLTRSVEITTDNILEGRI,-0.908841,1
2971,Y22W,YFQGQLNAMAHQIQEMFPQVPWHLVLQDLQLTRSVEITTDNILEGRI,-0.147079,1

BBC1_YEAST_Rocklin_2023_1TG0.csv
Number of dropped mutant formats: 5 / 2174 = 0.2%
Number of dropped invalid amino acids: 5 / 2174 = 0.2%
Number of dropped synonymous mutants: 3 / 2174 = 0.1%
Number of dropped mutants not matching WT: 0 / 2174 = 0.0%
Dropped mutants: Length before: 2174, length after: 2166: 0.4% dropped
Debug: Number of duplicate mutants: 97 (4.48%)
Final length: 2069

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A36C,EVPFKVVAQFPYKSDYEDDLNFEKDQEIIVTSVEDCEWYFGEYQDS...,0.295732,1
1,A36D,EVPFKVVAQFPYKSDYEDDLNFEKDQEIIVTSVEDDEWYFGEYQDS...,0.429921,1
2,A36E,EVPFKVVAQFPYKSDYEDDLNFEKDQEIIVTSVEDEEWYFGEYQDS...,0.200627,1
3,A36F,EVPFKVVAQFPYKSDYEDDLNFEKDQEIIVTSVEDFEWYFGEYQDS...,-0.446416,1
4,A36G,EVPFKVVAQFPYKSDYEDDLNFEKDQEIIVTSVEDGEWYFGEYQDS...,0.104998,1
...,...,...,...,...
2064,Y43M,EVPFKVVAQFPYKSDYEDDLNFEKDQEIIVTSVEDAEWYFGEMQDS...,-1.482282,0
2065,Y43R,EVPFKVVAQFPYKSDYEDDLNFEKDQEIIVTSVEDAEWYFGERQDS...,-2.591019,0
2066,Y43T,EVPFKVVAQFPYKSDYEDDLNFEKDQEIIVTSVEDAEWYFGETQDS...,-1.931685,0
2067,Y43V,EVPFKVVAQFPYKSDYEDDLNFEKDQEIIVTSVEDAEWYFGEVQDS...,-2.706480,0
2068,Y43W,EVPFKVVAQFPYKSDYEDDLNFEKDQEIIVTSVEDAEWYFGEWQDS...,-1.735565,0

BCHB_CHLTE_Rocklin_2023_2KRU.csv
Number of dropped mutant formats: 5 / 1653 = 0.3%
Number of dropped invalid amino acids: 5 / 1653 = 0.3%
Number of dropped synonymous mutants: 2 / 1653 = 0.1%
Number of dropped mutants not matching WT: 0 / 1653 = 0.0%
Dropped mutants: Length before: 1653, length after: 1646: 0.4% dropped
Debug: Number of duplicate mutants: 74 (4.50%)
Final length: 1572

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A31C,ELSWTAEAEKMLGKVPFFVRKKVRKNTDNYCREIGEPVVTADVFRK...,-0.597831,1
1,A31G,ELSWTAEAEKMLGKVPFFVRKKVRKNTDNYGREIGEPVVTADVFRK...,-2.377507,0
2,A31I,ELSWTAEAEKMLGKVPFFVRKKVRKNTDNYIREIGEPVVTADVFRK...,-3.791894,0
3,A31K,ELSWTAEAEKMLGKVPFFVRKKVRKNTDNYKREIGEPVVTADVFRK...,-4.527159,0
4,A31L,ELSWTAEAEKMLGKVPFFVRKKVRKNTDNYLREIGEPVVTADVFRK...,-3.112637,0
...,...,...,...,...
1567,Y30R,ELSWTAEAEKMLGKVPFFVRKKVRKNTDNRAREIGEPVVTADVFRK...,-3.133056,0
1568,Y30S,ELSWTAEAEKMLGKVPFFVRKKVRKNTDNSAREIGEPVVTADVFRK...,-4.564073,0
1569,Y30T,ELSWTAEAEKMLGKVPFFVRKKVRKNTDNTAREIGEPVVTADVFRK...,-3.489600,0
1570,Y30V,ELSWTAEAEKMLGKVPFFVRKKVRKNTDNVAREIGEPVVTADVFRK...,-2.475352,0
1571,Y30W,ELSWTAEAEKMLGKVPFFVRKKVRKNTDNWAREIGEPVVTADVFRK...,-0.784718,1

CATR_CHLRE_Rocklin_2023_2AMI.csv
Number of dropped mutant formats: 5 / 2007 = 0.2%
Number of dropped invalid amino acids: 5 / 2007 = 0.2%
Number of dropped synonymous mutants: 3 / 2007 = 0.1%
Number of dropped mutants not matching WT: 0 / 2007 = 0.0%
Dropped mutants: Length before: 2007, length after: 1999: 0.4% dropped
Debug: Number of duplicate mutants: 96 (4.80%)
Final length: 1903

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A13C,GLTEEQKQEIRECFDLFDTDGSGTIDAKELKVAMRALGFEPKKEEI...,0.608587,1
1,A13D,GLTEEQKQEIREDFDLFDTDGSGTIDAKELKVAMRALGFEPKKEEI...,-1.471957,0
2,A13E,GLTEEQKQEIREEFDLFDTDGSGTIDAKELKVAMRALGFEPKKEEI...,-1.299734,0
3,A13F,GLTEEQKQEIREFFDLFDTDGSGTIDAKELKVAMRALGFEPKKEEI...,0.369891,1
4,A13G,GLTEEQKQEIREGFDLFDTDGSGTIDAKELKVAMRALGFEPKKEEI...,-1.255964,0
...,...,...,...,...
1898,V32R,GLTEEQKQEIREAFDLFDTDGSGTIDAKELKRAMRALGFEPKKEEI...,1.005817,1
1899,V32S,GLTEEQKQEIREAFDLFDTDGSGTIDAKELKSAMRALGFEPKKEEI...,0.600417,1
1900,V32T,GLTEEQKQEIREAFDLFDTDGSGTIDAKELKTAMRALGFEPKKEEI...,0.232747,1
1901,V32W,GLTEEQKQEIREAFDLFDTDGSGTIDAKELKWAMRALGFEPKKEEI...,1.103095,1
1902,V32Y,GLTEEQKQEIREAFDLFDTDGSGTIDAKELKYAMRALGFEPKKEEI...,0.823249,1

CBPA2_HUMAN_Rocklin_2023_1O6X.csv
Number of dropped mutant formats: 5 / 2151 = 0.2%
Number of dropped invalid amino acids: 5 / 2151 = 0.2%
Number of dropped synonymous mutants: 2 / 2151 = 0.1%
Number of dropped mutants not matching WT: 0 / 2151 = 0.0%
Dropped mutants: Length before: 2151, length after: 2144: 0.3% dropped
Debug: Number of duplicate mutants: 76 (3.54%)
Final length: 2068

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A24C,VGDQVLEIVPSNEEQIKNLLQLECQEHLQLDFWKSPTTPGETAHVR...,-0.286885,1
1,A24D,VGDQVLEIVPSNEEQIKNLLQLEDQEHLQLDFWKSPTTPGETAHVR...,-0.414358,1
2,A24E,VGDQVLEIVPSNEEQIKNLLQLEEQEHLQLDFWKSPTTPGETAHVR...,-0.253950,1
3,A24F,VGDQVLEIVPSNEEQIKNLLQLEFQEHLQLDFWKSPTTPGETAHVR...,-0.255869,1
4,A24G,VGDQVLEIVPSNEEQIKNLLQLEGQEHLQLDFWKSPTTPGETAHVR...,-0.245867,1
...,...,...,...,...
2063,Y66R,VGDQVLEIVPSNEEQIKNLLQLEAQEHLQLDFWKSPTTPGETAHVR...,-4.386651,0
2064,Y66S,VGDQVLEIVPSNEEQIKNLLQLEAQEHLQLDFWKSPTTPGETAHVR...,-3.049550,0
2065,Y66T,VGDQVLEIVPSNEEQIKNLLQLEAQEHLQLDFWKSPTTPGETAHVR...,-3.092975,0
2066,Y66V,VGDQVLEIVPSNEEQIKNLLQLEAQEHLQLDFWKSPTTPGETAHVR...,-2.216336,0
2067,Y66W,VGDQVLEIVPSNEEQIKNLLQLEAQEHLQLDFWKSPTTPGETAHVR...,-0.346591,1

CBX4_HUMAN_Rocklin_2023_2K28.csv
Number of dropped mutant formats: 5 / 2464 = 0.2%
Number of dropped invalid amino acids: 5 / 2464 = 0.2%
Number of dropped synonymous mutants: 5 / 2464 = 0.2%
Number of dropped mutants not matching WT: 0 / 2464 = 0.0%
Dropped mutants: Length before: 2464, length after: 2454: 0.4% dropped
Debug: Number of duplicate mutants: 172 (7.01%)
Final length: 2282

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A1C,CVESIEKKRIRKGRVEYLVKWRGWSPKYNTWEPEENILDPRLLIAF...,0.649621,1
1,A1D,DVESIEKKRIRKGRVEYLVKWRGWSPKYNTWEPEENILDPRLLIAF...,0.019735,1
2,A1E,EVESIEKKRIRKGRVEYLVKWRGWSPKYNTWEPEENILDPRLLIAF...,0.505077,1
3,A1F,FVESIEKKRIRKGRVEYLVKWRGWSPKYNTWEPEENILDPRLLIAF...,0.211319,1
4,A1G,GVESIEKKRIRKGRVEYLVKWRGWSPKYNTWEPEENILDPRLLIAF...,-0.006505,1
...,...,...,...,...
2277,Y28R,AVESIEKKRIRKGRVEYLVKWRGWSPKRNTWEPEENILDPRLLIAF...,-0.914350,1
2278,Y28S,AVESIEKKRIRKGRVEYLVKWRGWSPKSNTWEPEENILDPRLLIAF...,-1.233442,1
2279,Y28T,AVESIEKKRIRKGRVEYLVKWRGWSPKTNTWEPEENILDPRLLIAF...,-1.984448,0
2280,Y28V,AVESIEKKRIRKGRVEYLVKWRGWSPKVNTWEPEENILDPRLLIAF...,-1.657117,0
2281,Y28W,AVESIEKKRIRKGRVEYLVKWRGWSPKWNTWEPEENILDPRLLIAF...,-0.103185,1

CSN4_MOUSE_Rocklin_2023_1UFM.csv
Number of dropped mutant formats: 5 / 3524 = 0.1%
Number of dropped invalid amino acids: 5 / 3524 = 0.1%
Number of dropped synonymous mutants: 6 / 3524 = 0.2%
Number of dropped mutants not matching WT: 0 / 3524 = 0.0%
Dropped mutants: Length before: 3524, length after: 3513: 0.3% dropped
Debug: Number of duplicate mutants: 218 (6.21%)
Final length: 3295

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A11C,SSGGSSILDRCVIEHNLLSASKLYNNITFEELGALLEIPAAKAEKI...,0.004061,1
1,A11D,SSGGSSILDRDVIEHNLLSASKLYNNITFEELGALLEIPAAKAEKI...,-0.023454,1
2,A11E,SSGGSSILDREVIEHNLLSASKLYNNITFEELGALLEIPAAKAEKI...,0.111864,1
3,A11F,SSGGSSILDRFVIEHNLLSASKLYNNITFEELGALLEIPAAKAEKI...,-0.153650,1
4,A11G,SSGGSSILDRGVIEHNLLSASKLYNNITFEELGALLEIPAAKAEKI...,-0.393182,1
...,...,...,...,...
3290,Y24R,SSGGSSILDRAVIEHNLLSASKLRNNITFEELGALLEIPAAKAEKI...,-0.923061,0
3291,Y24S,SSGGSSILDRAVIEHNLLSASKLSNNITFEELGALLEIPAAKAEKI...,-1.811645,0
3292,Y24T,SSGGSSILDRAVIEHNLLSASKLTNNITFEELGALLEIPAAKAEKI...,-1.659020,0
3293,Y24V,SSGGSSILDRAVIEHNLLSASKLVNNITFEELGALLEIPAAKAEKI...,-1.085656,0
3294,Y24W,SSGGSSILDRAVIEHNLLSASKLWNNITFEELGALLEIPAAKAEKI...,-0.662566,1

CUE1_YEAST_Rocklin_2023_2MYX.csv
Number of dropped mutant formats: 5 / 1654 = 0.3%
Number of dropped invalid amino acids: 5 / 1654 = 0.3%
Number of dropped synonymous mutants: 2 / 1654 = 0.1%
Number of dropped mutants not matching WT: 0 / 1654 = 0.0%
Dropped mutants: Length before: 1654, length after: 1647: 0.4% dropped
Debug: Number of duplicate mutants: 67 (4.07%)
Final length: 1580

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A17C,GGHPVTTQMVETVQNLCPNLHPEQIRYSLENTGSVEETVERYLRGD...,0.934686,1
1,A17D,GGHPVTTQMVETVQNLDPNLHPEQIRYSLENTGSVEETVERYLRGD...,-2.760615,0
2,A17E,GGHPVTTQMVETVQNLEPNLHPEQIRYSLENTGSVEETVERYLRGD...,-2.963430,0
3,A17F,GGHPVTTQMVETVQNLFPNLHPEQIRYSLENTGSVEETVERYLRGD...,0.479633,1
4,A17G,GGHPVTTQMVETVQNLGPNLHPEQIRYSLENTGSVEETVERYLRGD...,-2.427011,0
...,...,...,...,...
1575,Y42Q,GGHPVTTQMVETVQNLAPNLHPEQIRYSLENTGSVEETVERQLRGD...,-2.774751,0
1576,Y42S,GGHPVTTQMVETVQNLAPNLHPEQIRYSLENTGSVEETVERSLRGD...,-3.038618,0
1577,Y42T,GGHPVTTQMVETVQNLAPNLHPEQIRYSLENTGSVEETVERTLRGD...,-3.259067,0
1578,Y42V,GGHPVTTQMVETVQNLAPNLHPEQIRYSLENTGSVEETVERVLRGD...,-2.008299,0
1579,Y42W,GGHPVTTQMVETVQNLAPNLHPEQIRYSLENTGSVEETVERWLRGD...,-0.378493,1

DNJA1_HUMAN_Rocklin_2023_2LO1.csv
Number of dropped mutant formats: 5 / 2383 = 0.2%
Number of dropped invalid amino acids: 5 / 2383 = 0.2%
Number of dropped synonymous mutants: 3 / 2383 = 0.1%
Number of dropped mutants not matching WT: 0 / 2383 = 0.0%
Dropped mutants: Length before: 2383, length after: 2375: 0.3% dropped
Debug: Number of duplicate mutants: 111 (4.67%)
Final length: 2264

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A13C,TTYYDVLGVKPNCTQEELKKAYRKLALKYHPDKNPNEGEKFKQISQ...,0.213311,1
1,A13D,TTYYDVLGVKPNDTQEELKKAYRKLALKYHPDKNPNEGEKFKQISQ...,-2.116559,1
2,A13E,TTYYDVLGVKPNETQEELKKAYRKLALKYHPDKNPNEGEKFKQISQ...,-2.537448,0
3,A13F,TTYYDVLGVKPNFTQEELKKAYRKLALKYHPDKNPNEGEKFKQISQ...,-0.887385,1
4,A13G,TTYYDVLGVKPNGTQEELKKAYRKLALKYHPDKNPNEGEKFKQISQ...,-2.314025,0
...,...,...,...,...
2259,Y60R,TTYYDVLGVKPNATQEELKKAYRKLALKYHPDKNPNEGEKFKQISQ...,-2.261716,0
2260,Y60S,TTYYDVLGVKPNATQEELKKAYRKLALKYHPDKNPNEGEKFKQISQ...,-2.050046,1
2261,Y60T,TTYYDVLGVKPNATQEELKKAYRKLALKYHPDKNPNEGEKFKQISQ...,-1.948707,1
2262,Y60V,TTYYDVLGVKPNATQEELKKAYRKLALKYHPDKNPNEGEKFKQISQ...,-1.888184,1
2263,Y60W,TTYYDVLGVKPNATQEELKKAYRKLALKYHPDKNPNEGEKFKQISQ...,-1.850289,1

DOCK1_MOUSE_Rocklin_2023_2M0Y.csv
Number of dropped mutant formats: 5 / 3100 = 0.2%
Number of dropped invalid amino acids: 5 / 3100 = 0.2%
Number of dropped synonymous mutants: 5 / 3100 = 0.2%
Number of dropped mutants not matching WT: 0 / 3100 = 0.0%
Dropped mutants: Length before: 3100, length after: 3090: 0.3% dropped
Debug: Number of duplicate mutants: 175 (5.66%)
Final length: 2915

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A13C,WVPTKREEKYGVCFYNYDARGADELSLQIGDTVHILETYEGWYRGY...,0.159992,1
1,A13D,WVPTKREEKYGVDFYNYDARGADELSLQIGDTVHILETYEGWYRGY...,-2.104244,0
2,A13E,WVPTKREEKYGVEFYNYDARGADELSLQIGDTVHILETYEGWYRGY...,-2.153877,0
3,A13F,WVPTKREEKYGVFFYNYDARGADELSLQIGDTVHILETYEGWYRGY...,-1.499803,0
4,A13G,WVPTKREEKYGVGFYNYDARGADELSLQIGDTVHILETYEGWYRGY...,-2.008590,0
...,...,...,...,...
2910,Y61R,WVPTKREEKYGVAFYNYDARGADELSLQIGDTVHILETYEGWYRGY...,-1.194976,0
2911,Y61S,WVPTKREEKYGVAFYNYDARGADELSLQIGDTVHILETYEGWYRGY...,-0.385778,1
2912,Y61T,WVPTKREEKYGVAFYNYDARGADELSLQIGDTVHILETYEGWYRGY...,-0.188980,1
2913,Y61V,WVPTKREEKYGVAFYNYDARGADELSLQIGDTVHILETYEGWYRGY...,1.473381,1
2914,Y61W,WVPTKREEKYGVAFYNYDARGADELSLQIGDTVHILETYEGWYRGY...,-1.505176,0

EPHB2_HUMAN_Rocklin_2023_1F0M.csv
Number of dropped mutant formats: 5 / 2042 = 0.2%
Number of dropped invalid amino acids: 5 / 2042 = 0.2%
Number of dropped synonymous mutants: 2 / 2042 = 0.1%
Number of dropped mutants not matching WT: 0 / 2042 = 0.0%
Dropped mutants: Length before: 2042, length after: 2035: 0.3% dropped
Debug: Number of duplicate mutants: 75 (3.69%)
Final length: 1960

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A11C,SFNTVDEWLECIKMGQYKESFANAGFTSFDVVSQMMMEDILRVGVT...,-0.128864,1
1,A11D,SFNTVDEWLEDIKMGQYKESFANAGFTSFDVVSQMMMEDILRVGVT...,-0.089099,1
2,A11E,SFNTVDEWLEEIKMGQYKESFANAGFTSFDVVSQMMMEDILRVGVT...,-0.081115,1
3,A11F,SFNTVDEWLEFIKMGQYKESFANAGFTSFDVVSQMMMEDILRVGVT...,0.237753,1
4,A11G,SFNTVDEWLEGIKMGQYKESFANAGFTSFDVVSQMMMEDILRVGVT...,0.085135,1
...,...,...,...,...
1955,Y17W:H50S,SFNTVDEWLEAIKMGQWKESFANAGFTSFDVVSQMMMEDILRVGVT...,-2.321345,0
1956,Y17W:H50T,SFNTVDEWLEAIKMGQWKESFANAGFTSFDVVSQMMMEDILRVGVT...,-2.813672,0
1957,Y17W:H50V,SFNTVDEWLEAIKMGQWKESFANAGFTSFDVVSQMMMEDILRVGVT...,-2.596270,0
1958,Y17W:H50W,SFNTVDEWLEAIKMGQWKESFANAGFTSFDVVSQMMMEDILRVGVT...,-2.077060,0
1959,Y17W:H50Y,SFNTVDEWLEAIKMGQWKESFANAGFTSFDVVSQMMMEDILRVGVT...,-2.453295,0

FECA_ECOLI_Rocklin_2023_2D1U.csv
Number of dropped mutant formats: 5 / 1961 = 0.3%
Number of dropped invalid amino acids: 5 / 1961 = 0.3%
Number of dropped synonymous mutants: 2 / 1961 = 0.1%
Number of dropped mutants not matching WT: 0 / 1961 = 0.0%
Dropped mutants: Length before: 1961, length after: 1954: 0.4% dropped
Debug: Number of duplicate mutants: 68 (3.48%)
Final length: 1886

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A12D,QVNIAPGSLDKDLNQYAAHSGFTLSVDASLTRGKQSNGLHGDYDVE...,-1.952953,0
1,A12E,QVNIAPGSLDKELNQYAAHSGFTLSVDASLTRGKQSNGLHGDYDVE...,-2.031356,0
2,A12F,QVNIAPGSLDKFLNQYAAHSGFTLSVDASLTRGKQSNGLHGDYDVE...,-1.172823,0
3,A12G,QVNIAPGSLDKGLNQYAAHSGFTLSVDASLTRGKQSNGLHGDYDVE...,-1.980739,0
4,A12H,QVNIAPGSLDKHLNQYAAHSGFTLSVDASLTRGKQSNGLHGDYDVE...,-1.770548,0
...,...,...,...,...
1881,Y43R,QVNIAPGSLDKALNQYAAHSGFTLSVDASLTRGKQSNGLHGDRDVE...,-1.962388,0
1882,Y43S,QVNIAPGSLDKALNQYAAHSGFTLSVDASLTRGKQSNGLHGDSDVE...,-1.882192,0
1883,Y43T,QVNIAPGSLDKALNQYAAHSGFTLSVDASLTRGKQSNGLHGDTDVE...,-1.463979,0
1884,Y43V,QVNIAPGSLDKALNQYAAHSGFTLSVDASLTRGKQSNGLHGDVDVE...,-0.981083,0
1885,Y43W,QVNIAPGSLDKALNQYAAHSGFTLSVDASLTRGKQSNGLHGDWDVE...,0.207467,1

HECD1_HUMAN_Rocklin_2023_3DKM.csv
Number of dropped mutant formats: 5 / 6836 = 0.1%
Number of dropped invalid amino acids: 5 / 6836 = 0.1%
Number of dropped synonymous mutants: 20 / 6836 = 0.3%
Number of dropped mutants not matching WT: 0 / 6836 = 0.0%
Dropped mutants: Length before: 6836, length after: 6811: 0.4% dropped
Debug: Number of duplicate mutants: 1225 (17.99%)
Final length: 5586

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A14C,NLYFQGLKYMVPGCRVTRGLDWKWRDQDGSPQGEGTVTGELHNGWI...,0.286352,1
1,A14D,NLYFQGLKYMVPGDRVTRGLDWKWRDQDGSPQGEGTVTGELHNGWI...,-1.043903,0
2,A14E,NLYFQGLKYMVPGERVTRGLDWKWRDQDGSPQGEGTVTGELHNGWI...,-1.542356,0
3,A14F,NLYFQGLKYMVPGFRVTRGLDWKWRDQDGSPQGEGTVTGELHNGWI...,-1.740192,0
4,A14G,NLYFQGLKYMVPGGRVTRGLDWKWRDQDGSPQGEGTVTGELHNGWI...,-1.860183,0
...,...,...,...,...
5581,Y9R,NLYFQGLKRMVPGARVTRGLDWKWRDQDGSPQGEGTVTGELHNGWI...,-0.609078,1
5582,Y9S,NLYFQGLKSMVPGARVTRGLDWKWRDQDGSPQGEGTVTGELHNGWI...,-0.523842,1
5583,Y9T,NLYFQGLKTMVPGARVTRGLDWKWRDQDGSPQGEGTVTGELHNGWI...,-0.742542,0
5584,Y9V,NLYFQGLKVMVPGARVTRGLDWKWRDQDGSPQGEGTVTGELHNGWI...,-0.811542,0
5585,Y9W,NLYFQGLKWMVPGARVTRGLDWKWRDQDGSPQGEGTVTGELHNGWI...,-0.105330,1

ISDH_STAAW_Rocklin_2023_2LHR.csv
Number of dropped mutant formats: 5 / 2060 = 0.2%
Number of dropped invalid amino acids: 5 / 2060 = 0.2%
Number of dropped synonymous mutants: 3 / 2060 = 0.1%
Number of dropped mutants not matching WT: 0 / 2060 = 0.0%
Dropped mutants: Length before: 2060, length after: 2052: 0.4% dropped
Debug: Number of duplicate mutants: 108 (5.26%)
Final length: 1944

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A13C,YNLQKLLAPYHKCKTLERQVYELEKLQEKLPEKYKAEYKKKLDQTR...,-1.499238,0
1,A13E,YNLQKLLAPYHKEKTLERQVYELEKLQEKLPEKYKAEYKKKLDQTR...,-2.641021,0
2,A13G,YNLQKLLAPYHKGKTLERQVYELEKLQEKLPEKYKAEYKKKLDQTR...,-2.875267,0
3,A13I,YNLQKLLAPYHKIKTLERQVYELEKLQEKLPEKYKAEYKKKLDQTR...,-2.050171,0
4,A13L,YNLQKLLAPYHKLKTLERQVYELEKLQEKLPEKYKAEYKKKLDQTR...,-2.073565,0
...,...,...,...,...
1939,Y38P,YNLQKLLAPYHKAKTLERQVYELEKLQEKLPEKYKAEPKKKLDQTR...,-2.758969,0
1940,Y38S,YNLQKLLAPYHKAKTLERQVYELEKLQEKLPEKYKAESKKKLDQTR...,-1.892864,0
1941,Y38T,YNLQKLLAPYHKAKTLERQVYELEKLQEKLPEKYKAETKKKLDQTR...,-2.136941,0
1942,Y38V,YNLQKLLAPYHKAKTLERQVYELEKLQEKLPEKYKAEVKKKLDQTR...,-0.720316,1
1943,Y38W,YNLQKLLAPYHKAKTLERQVYELEKLQEKLPEKYKAEWKKKLDQTR...,-0.014547,1

MAFG_MOUSE_Rocklin_2023_1K1V.csv
Number of dropped mutant formats: 5 / 1509 = 0.3%
Number of dropped invalid amino acids: 5 / 1509 = 0.3%
Number of dropped synonymous mutants: 2 / 1509 = 0.1%
Number of dropped mutants not matching WT: 0 / 1509 = 0.0%
Dropped mutants: Length before: 1509, length after: 1502: 0.5% dropped
Debug: Number of duplicate mutants: 73 (4.86%)
Final length: 1429

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,D3A,LTAEELVTMSVRELNQHLRGLSKEEIIQLKQRRRTLKNRGY,-1.274690,0
1,D3A:R32A,LTAEELVTMSVRELNQHLRGLSKEEIIQLKQARRTLKNRGY,-1.637233,0
2,D3A:R32C,LTAEELVTMSVRELNQHLRGLSKEEIIQLKQCRRTLKNRGY,-1.081258,0
3,D3A:R32D,LTAEELVTMSVRELNQHLRGLSKEEIIQLKQDRRTLKNRGY,-1.938164,0
4,D3A:R32E,LTAEELVTMSVRELNQHLRGLSKEEIIQLKQERRTLKNRGY,-1.893906,0
...,...,...,...,...
1424,Y41R,LTDEELVTMSVRELNQHLRGLSKEEIIQLKQRRRTLKNRGR,-0.184325,1
1425,Y41S,LTDEELVTMSVRELNQHLRGLSKEEIIQLKQRRRTLKNRGS,0.064654,1
1426,Y41T,LTDEELVTMSVRELNQHLRGLSKEEIIQLKQRRRTLKNRGT,0.104944,1
1427,Y41V,LTDEELVTMSVRELNQHLRGLSKEEIIQLKQRRRTLKNRGV,0.139744,1
1428,Y41W,LTDEELVTMSVRELNQHLRGLSKEEIIQLKQRRRTLKNRGW,0.024645,1

MBD11_ARATH_Rocklin_2023_6ACV.csv
Number of dropped mutant formats: 5 / 2230 = 0.2%
Number of dropped invalid amino acids: 5 / 2230 = 0.2%
Number of dropped synonymous mutants: 3 / 2230 = 0.1%
Number of dropped mutants not matching WT: 0 / 2230 = 0.0%
Dropped mutants: Length before: 2230, length after: 2222: 0.4% dropped
Debug: Number of duplicate mutants: 106 (4.77%)
Final length: 2116

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A32C,VSVELPAPSSWKKLFYPNKVGSVKKTEVVFVCPTGEEISNRKQLEQ...,-2.383466,0
1,A32F,VSVELPAPSSWKKLFYPNKVGSVKKTEVVFVFPTGEEISNRKQLEQ...,-2.609272,0
2,A32G,VSVELPAPSSWKKLFYPNKVGSVKKTEVVFVGPTGEEISNRKQLEQ...,-2.439210,0
3,A32I,VSVELPAPSSWKKLFYPNKVGSVKKTEVVFVIPTGEEISNRKQLEQ...,-3.607797,0
4,A32L,VSVELPAPSSWKKLFYPNKVGSVKKTEVVFVLPTGEEISNRKQLEQ...,-3.012900,0
...,...,...,...,...
2111,Y16W,VSVELPAPSSWKKLFWPNKVGSVKKTEVVFVAPTGEEISNRKQLEQ...,-0.365772,1
2112,Y47C,VSVELPAPSSWKKLFYPNKVGSVKKTEVVFVAPTGEEISNRKQLEQ...,-3.683888,0
2113,Y47F,VSVELPAPSSWKKLFYPNKVGSVKKTEVVFVAPTGEEISNRKQLEQ...,-1.159364,1
2114,Y47H,VSVELPAPSSWKKLFYPNKVGSVKKTEVVFVAPTGEEISNRKQLEQ...,-2.383398,0
2115,Y47W,VSVELPAPSSWKKLFYPNKVGSVKKTEVVFVAPTGEEISNRKQLEQ...,-1.266022,1

MYO3_YEAST_Rocklin_2023_2BTT.csv
Number of dropped mutant formats: 5 / 3589 = 0.1%
Number of dropped invalid amino acids: 5 / 3589 = 0.1%
Number of dropped synonymous mutants: 8 / 3589 = 0.2%
Number of dropped mutants not matching WT: 0 / 3589 = 0.0%
Dropped mutants: Length before: 3589, length after: 3576: 0.4% dropped
Debug: Number of duplicate mutants: 279 (7.80%)
Final length: 3297

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A41C,KDPKFEAAYDFPGSGSSSELPLKKGDIVFISRDEPSGWSLCKLLDG...,-0.351063,1
1,A41F,KDPKFEAAYDFPGSGSSSELPLKKGDIVFISRDEPSGWSLFKLLDG...,-2.868691,0
2,A41G,KDPKFEAAYDFPGSGSSSELPLKKGDIVFISRDEPSGWSLGKLLDG...,-1.792629,0
3,A41I,KDPKFEAAYDFPGSGSSSELPLKKGDIVFISRDEPSGWSLIKLLDG...,-2.686451,0
4,A41L,KDPKFEAAYDFPGSGSSSELPLKKGDIVFISRDEPSGWSLLKLLDG...,-2.345302,0
...,...,...,...,...
3292,Y9W:K24S,KDPKFEAAWDFPGSGSSSELPLKSGDIVFISRDEPSGWSLAKLLDG...,-1.691685,0
3293,Y9W:K24T,KDPKFEAAWDFPGSGSSSELPLKTGDIVFISRDEPSGWSLAKLLDG...,-1.692586,0
3294,Y9W:K24V,KDPKFEAAWDFPGSGSSSELPLKVGDIVFISRDEPSGWSLAKLLDG...,-1.485215,0
3295,Y9W:K24W,KDPKFEAAWDFPGSGSSSELPLKWGDIVFISRDEPSGWSLAKLLDG...,-2.037594,0
3296,Y9W:K24Y,KDPKFEAAWDFPGSGSSSELPLKYGDIVFISRDEPSGWSLAKLLDG...,-2.257552,0

NKX31_HUMAN_Rocklin_2023_2L9R.csv
Number of dropped mutant formats: 5 / 2639 = 0.2%
Number of dropped invalid amino acids: 5 / 2639 = 0.2%
Number of dropped synonymous mutants: 4 / 2639 = 0.2%
Number of dropped mutants not matching WT: 0 / 2639 = 0.0%
Dropped mutants: Length before: 2639, length after: 2630: 0.3% dropped
Debug: Number of duplicate mutants: 148 (5.63%)
Final length: 2482

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A24C,HSHMSHTQVIELERKFSHQKYLSCPERAHLAKNLKLTETQVKIWFQ...,-0.154309,1
1,A24D,HSHMSHTQVIELERKFSHQKYLSDPERAHLAKNLKLTETQVKIWFQ...,-0.395160,0
2,A24E,HSHMSHTQVIELERKFSHQKYLSEPERAHLAKNLKLTETQVKIWFQ...,-0.200149,1
3,A24F,HSHMSHTQVIELERKFSHQKYLSFPERAHLAKNLKLTETQVKIWFQ...,0.113826,1
4,A24G,HSHMSHTQVIELERKFSHQKYLSGPERAHLAKNLKLTETQVKIWFQ...,-0.078626,1
...,...,...,...,...
2477,Y50R,HSHMSHTQVIELERKFSHQKYLSAPERAHLAKNLKLTETQVKIWFQ...,0.447124,1
2478,Y50S,HSHMSHTQVIELERKFSHQKYLSAPERAHLAKNLKLTETQVKIWFQ...,0.139272,1
2479,Y50T,HSHMSHTQVIELERKFSHQKYLSAPERAHLAKNLKLTETQVKIWFQ...,0.001398,1
2480,Y50V,HSHMSHTQVIELERKFSHQKYLSAPERAHLAKNLKLTETQVKIWFQ...,-0.123227,1
2481,Y50W,HSHMSHTQVIELERKFSHQKYLSAPERAHLAKNLKLTETQVKIWFQ...,0.082828,1

NUSA_ECOLI_Rocklin_2023_1WCL.csv
Number of dropped mutant formats: 5 / 2111 = 0.2%
Number of dropped invalid amino acids: 5 / 2111 = 0.2%
Number of dropped synonymous mutants: 2 / 2111 = 0.1%
Number of dropped mutants not matching WT: 0 / 2111 = 0.0%
Dropped mutants: Length before: 2111, length after: 2104: 0.3% dropped
Debug: Number of duplicate mutants: 76 (3.61%)
Final length: 2028

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A20C,EAHAAIDTFTKYLDIDEDFCTVLVEEGFSTLEELAYVPMKELLEIE...,-2.231942,0
1,A20D,EAHAAIDTFTKYLDIDEDFDTVLVEEGFSTLEELAYVPMKELLEIE...,-2.918981,0
2,A20E,EAHAAIDTFTKYLDIDEDFETVLVEEGFSTLEELAYVPMKELLEIE...,-3.069284,0
3,A20F,EAHAAIDTFTKYLDIDEDFFTVLVEEGFSTLEELAYVPMKELLEIE...,-2.374904,0
4,A20G,EAHAAIDTFTKYLDIDEDFGTVLVEEGFSTLEELAYVPMKELLEIE...,-2.075861,0
...,...,...,...,...
2023,Y36R,EAHAAIDTFTKYLDIDEDFATVLVEEGFSTLEELARVPMKELLEIE...,-0.262403,1
2024,Y36S,EAHAAIDTFTKYLDIDEDFATVLVEEGFSTLEELASVPMKELLEIE...,0.128361,1
2025,Y36T,EAHAAIDTFTKYLDIDEDFATVLVEEGFSTLEELATVPMKELLEIE...,0.130476,1
2026,Y36V,EAHAAIDTFTKYLDIDEDFATVLVEEGFSTLEELAVVPMKELLEIE...,-0.316919,1
2027,Y36W,EAHAAIDTFTKYLDIDEDFATVLVEEGFSTLEELAWVPMKELLEIE...,-0.209890,1

NUSG_MYCTU_Rocklin_2023_2MI6.csv
Number of dropped mutant formats: 5 / 1424 = 0.4%
Number of dropped invalid amino acids: 5 / 1424 = 0.4%
Number of dropped synonymous mutants: 1 / 1424 = 0.1%
Number of dropped mutants not matching WT: 0 / 1424 = 0.0%
Dropped mutants: Length before: 1424, length after: 1418: 0.4% dropped
Debug: Number of duplicate mutants: 38 (2.68%)
Final length: 1380

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A16C,DYEVGESVTVMDGPFCTLPATISEVNAEQQKLKVLVSIFGRETPVE...,-0.601046,0
1,A16D,DYEVGESVTVMDGPFDTLPATISEVNAEQQKLKVLVSIFGRETPVE...,-1.839601,0
2,A16E,DYEVGESVTVMDGPFETLPATISEVNAEQQKLKVLVSIFGRETPVE...,-1.223488,0
3,A16F,DYEVGESVTVMDGPFFTLPATISEVNAEQQKLKVLVSIFGRETPVE...,-1.405073,0
4,A16G,DYEVGESVTVMDGPFGTLPATISEVNAEQQKLKVLVSIFGRETPVE...,-1.664366,0
...,...,...,...,...
1375,Y2R,DREVGESVTVMDGPFATLPATISEVNAEQQKLKVLVSIFGRETPVE...,-3.382254,0
1376,Y2S,DSEVGESVTVMDGPFATLPATISEVNAEQQKLKVLVSIFGRETPVE...,-3.854430,0
1377,Y2T,DTEVGESVTVMDGPFATLPATISEVNAEQQKLKVLVSIFGRETPVE...,-3.955787,0
1378,Y2V,DVEVGESVTVMDGPFATLPATISEVNAEQQKLKVLVSIFGRETPVE...,-2.772868,0
1379,Y2W,DWEVGESVTVMDGPFATLPATISEVNAEQQKLKVLVSIFGRETPVE...,0.226928,1

OBSCN_HUMAN_Rocklin_2023_1V1C.csv
Number of dropped mutant formats: 5 / 3422 = 0.1%
Number of dropped invalid amino acids: 5 / 3422 = 0.1%
Number of dropped synonymous mutants: 6 / 3422 = 0.2%
Number of dropped mutants not matching WT: 0 / 3422 = 0.0%
Dropped mutants: Length before: 3422, length after: 3411: 0.3% dropped
Debug: Number of duplicate mutants: 214 (6.27%)
Final length: 3197

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A15C,FDIYVVTADYLPLGCEQDAITLREGQYVEVLDAAHPLRWLVRTKPT...,0.211419,1
1,A15D,FDIYVVTADYLPLGDEQDAITLREGQYVEVLDAAHPLRWLVRTKPT...,0.635936,1
2,A15E,FDIYVVTADYLPLGEEQDAITLREGQYVEVLDAAHPLRWLVRTKPT...,0.277172,1
3,A15F,FDIYVVTADYLPLGFEQDAITLREGQYVEVLDAAHPLRWLVRTKPT...,0.099342,1
4,A15G,FDIYVVTADYLPLGGEQDAITLREGQYVEVLDAAHPLRWLVRTKPT...,0.309341,1
...,...,...,...,...
3192,Y60R,FDIYVVTADYLPLGAEQDAITLREGQYVEVLDAAHPLRWLVRTKPT...,-2.356770,0
3193,Y60S,FDIYVVTADYLPLGAEQDAITLREGQYVEVLDAAHPLRWLVRTKPT...,-1.406827,0
3194,Y60T,FDIYVVTADYLPLGAEQDAITLREGQYVEVLDAAHPLRWLVRTKPT...,-1.738598,0
3195,Y60V,FDIYVVTADYLPLGAEQDAITLREGQYVEVLDAAHPLRWLVRTKPT...,-0.212530,1
3196,Y60W,FDIYVVTADYLPLGAEQDAITLREGQYVEVLDAAHPLRWLVRTKPT...,-1.094698,0

ODP2_GEOSE_Rocklin_2023_1W4G.csv
Number of dropped mutant formats: 5 / 1202 = 0.4%
Number of dropped invalid amino acids: 5 / 1202 = 0.4%
Number of dropped synonymous mutants: 3 / 1202 = 0.2%
Number of dropped mutants not matching WT: 0 / 1202 = 0.0%
Dropped mutants: Length before: 1202, length after: 1194: 0.7% dropped
Debug: Number of duplicate mutants: 60 (5.03%)
Final length: 1134

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A14C,NRRVIAMPSVRKWCREKGVDIRLVQGTGKNGRVLKEDIDAFLAG,-0.878116,0
1,A14F,NRRVIAMPSVRKWFREKGVDIRLVQGTGKNGRVLKEDIDAFLAG,-2.399461,0
2,A14G,NRRVIAMPSVRKWGREKGVDIRLVQGTGKNGRVLKEDIDAFLAG,-2.570950,0
3,A14L,NRRVIAMPSVRKWLREKGVDIRLVQGTGKNGRVLKEDIDAFLAG,-2.106319,0
4,A14P,NRRVIAMPSVRKWPREKGVDIRLVQGTGKNGRVLKEDIDAFLAG,-2.040105,0
...,...,...,...,...
1129,W13Q,NRRVIAMPSVRKQAREKGVDIRLVQGTGKNGRVLKEDIDAFLAG,-0.770307,0
1130,W13R,NRRVIAMPSVRKRAREKGVDIRLVQGTGKNGRVLKEDIDAFLAG,-0.435545,0
1131,W13S,NRRVIAMPSVRKSAREKGVDIRLVQGTGKNGRVLKEDIDAFLAG,-1.043697,0
1132,W13T,NRRVIAMPSVRKTAREKGVDIRLVQGTGKNGRVLKEDIDAFLAG,-0.960650,0
1133,W13V,NRRVIAMPSVRKVAREKGVDIRLVQGTGKNGRVLKEDIDAFLAG,-0.554792,0

PIN1_HUMAN_Rocklin_2023_1I6C.csv
Number of dropped mutant formats: 5 / 819 = 0.6%
Number of dropped invalid amino acids: 5 / 819 = 0.6%
Number of dropped synonymous mutants: 0 / 819 = 0.0%
Number of dropped mutants not matching WT: 0 / 819 = 0.0%
Dropped mutants: Length before: 819, length after: 814: 0.6% dropped
Debug: Number of duplicate mutants: 12 (1.47%)
Final length: 802

    mutant                         mutated_sequence  DMS_score  DMS_score_bin
0     A26D  KLPPGWEKRMSRSSGRVYYFNHITNDSQWERPSGNSSSG  -0.488145              1
1     A26E  KLPPGWEKRMSRSSGRVYYFNHITNESQWERPSGNSSSG   0.170364              1
2     A26F  KLPPGWEKRMSRSSGRVYYFNHITNFSQWERPSGNSSSG  -0.299441              1
3     A26G  KLPPGWEKRMSRSSGRVYYFNHITNGSQWERPSGNSSSG  -0.745520              0
4     A26H  KLPPGWEKRMSRSSGRVYYFNHITNHSQWERPSGNSSSG   0.147642              1
..     ...                                      ...        ...            ...
797   Y19H  KLPPGWEKRMSRSSGRVYHFNHITNASQWERPSGNSSSG  -2.647869              0
798   Y19L  KLPPGWEKRMSRSSGRVYLFNHITNASQWERPSGNSSSG  -2.389692              0
799   Y19M  KLPPGWEKRMSRSSGRVYMFNHITNASQWERPSGNSSSG  -2.924134              0
800   Y19P  KLPPGWEKRMSRSSGRVYPFNHITNASQWERPSGNSSSG  -1.868900              0
801   Y19W  KLPPGWEKRMSRSSGRVYWFNHITNASQWERPSGNSSSG  -0.714482              0

[802 rows x 4 columns]

PITX2_HUMAN_Rocklin_2023_2L7M.csv
Number of dropped mutant formats: 5 / 1935 = 0.3%
Number of dropped invalid amino acids: 5 / 1935 = 0.3%
Number of dropped synonymous mutants: 3 / 1935 = 0.2%
Number of dropped mutants not matching WT: 0 / 1935 = 0.0%
Dropped mutants: Length before: 1935, length after: 1927: 0.4% dropped
Debug: Number of duplicate mutants: 103 (5.35%)
Final length: 1824

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A13C,THFTSQQLQELECTFQRNHYPDMSTREEIAVWTNLTEARVRVWFKN...,0.259561,1
1,A13D,THFTSQQLQELEDTFQRNHYPDMSTREEIAVWTNLTEARVRVWFKN...,-0.328763,1
2,A13E,THFTSQQLQELEETFQRNHYPDMSTREEIAVWTNLTEARVRVWFKN...,-0.153199,1
3,A13F,THFTSQQLQELEFTFQRNHYPDMSTREEIAVWTNLTEARVRVWFKN...,-0.122043,1
4,A13G,THFTSQQLQELEGTFQRNHYPDMSTREEIAVWTNLTEARVRVWFKN...,-0.808713,1
...,...,...,...,...
1819,Y20R,THFTSQQLQELEATFQRNHRPDMSTREEIAVWTNLTEARVRVWFKN...,-1.397203,0
1820,Y20S,THFTSQQLQELEATFQRNHSPDMSTREEIAVWTNLTEARVRVWFKN...,-1.258967,0
1821,Y20T,THFTSQQLQELEATFQRNHTPDMSTREEIAVWTNLTEARVRVWFKN...,-1.169834,1
1822,Y20V,THFTSQQLQELEATFQRNHVPDMSTREEIAVWTNLTEARVRVWFKN...,-1.701371,0
1823,Y20W,THFTSQQLQELEATFQRNHWPDMSTREEIAVWTNLTEARVRVWFKN...,0.160759,1

POLG_PESV_Rocklin_2023_2MXD.csv
Number of dropped mutant formats: 5 / 6288 = 0.1%
Number of dropped invalid amino acids: 5 / 6288 = 0.1%
Number of dropped synonymous mutants: 15 / 6288 = 0.2%
Number of dropped mutants not matching WT: 0 / 6288 = 0.0%
Dropped mutants: Length before: 6288, length after: 6268: 0.3% dropped
Debug: Number of duplicate mutants: 1138 (18.16%)
Final length: 5130

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A1C,CLRDDEYDEWQDIIRDWRKEMTVQQFLDLKERALSGASDPDSQRYN...,-0.315709,1
1,A1D,DLRDDEYDEWQDIIRDWRKEMTVQQFLDLKERALSGASDPDSQRYN...,-0.100795,1
2,A1E,ELRDDEYDEWQDIIRDWRKEMTVQQFLDLKERALSGASDPDSQRYN...,-0.005752,1
3,A1F,FLRDDEYDEWQDIIRDWRKEMTVQQFLDLKERALSGASDPDSQRYN...,0.171090,1
4,A1G,GLRDDEYDEWQDIIRDWRKEMTVQQFLDLKERALSGASDPDSQRYN...,0.203474,1
...,...,...,...,...
5125,Y7R,ALRDDERDEWQDIIRDWRKEMTVQQFLDLKERALSGASDPDSQRYN...,-0.556729,1
5126,Y7S,ALRDDESDEWQDIIRDWRKEMTVQQFLDLKERALSGASDPDSQRYN...,-1.510053,1
5127,Y7T,ALRDDETDEWQDIIRDWRKEMTVQQFLDLKERALSGASDPDSQRYN...,-1.367047,1
5128,Y7V,ALRDDEVDEWQDIIRDWRKEMTVQQFLDLKERALSGASDPDSQRYN...,-0.680630,1
5129,Y7W,ALRDDEWDEWQDIIRDWRKEMTVQQFLDLKERALSGASDPDSQRYN...,-0.234516,1

PR40A_HUMAN_Rocklin_2023_1UZC.csv
Number of dropped mutant formats: 5 / 2147 = 0.2%
Number of dropped invalid amino acids: 5 / 2147 = 0.2%
Number of dropped synonymous mutants: 3 / 2147 = 0.1%
Number of dropped mutants not matching WT: 0 / 2147 = 0.0%
Dropped mutants: Length before: 2147, length after: 2139: 0.4% dropped
Debug: Number of duplicate mutants: 106 (4.96%)
Final length: 2033

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A10C,TYTWNTKEECKQAFKELLKEKRVPSNASWEQAMKMIINDPRYSALA...,-0.112784,1
1,A10D,TYTWNTKEEDKQAFKELLKEKRVPSNASWEQAMKMIINDPRYSALA...,-1.219861,1
2,A10E,TYTWNTKEEEKQAFKELLKEKRVPSNASWEQAMKMIINDPRYSALA...,-0.396846,1
3,A10F,TYTWNTKEEFKQAFKELLKEKRVPSNASWEQAMKMIINDPRYSALA...,-1.277052,1
4,A10G,TYTWNTKEEGKQAFKELLKEKRVPSNASWEQAMKMIINDPRYSALA...,-0.217503,1
...,...,...,...,...
2028,Y58R,TYTWNTKEEAKQAFKELLKEKRVPSNASWEQAMKMIINDPRYSALA...,-2.244071,0
2029,Y58S,TYTWNTKEEAKQAFKELLKEKRVPSNASWEQAMKMIINDPRYSALA...,-1.476018,0
2030,Y58T,TYTWNTKEEAKQAFKELLKEKRVPSNASWEQAMKMIINDPRYSALA...,-1.633756,0
2031,Y58V,TYTWNTKEEAKQAFKELLKEKRVPSNASWEQAMKMIINDPRYSALA...,-1.587709,0
2032,Y58W,TYTWNTKEEAKQAFKELLKEKRVPSNASWEQAMKMIINDPRYSALA...,0.029864,1

PSAE_SYNP2_Rocklin_2023_1PSE.csv
Number of dropped mutant formats: 5 / 1617 = 0.3%
Number of dropped invalid amino acids: 5 / 1617 = 0.3%
Number of dropped synonymous mutants: 1 / 1617 = 0.1%
Number of dropped mutants not matching WT: 0 / 1617 = 0.0%
Dropped mutants: Length before: 1617, length after: 1611: 0.4% dropped
Debug: Number of duplicate mutants: 32 (1.99%)
Final length: 1579

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A1D,DIERGSKVKILRKESYWYGDVGTVASIDKSGIIYPVIVRFNKVNYN...,-0.191423,1
1,A1E,EIERGSKVKILRKESYWYGDVGTVASIDKSGIIYPVIVRFNKVNYN...,-0.021574,1
2,A1F,FIERGSKVKILRKESYWYGDVGTVASIDKSGIIYPVIVRFNKVNYN...,0.067171,1
3,A1G,GIERGSKVKILRKESYWYGDVGTVASIDKSGIIYPVIVRFNKVNYN...,0.195264,1
4,A1H,HIERGSKVKILRKESYWYGDVGTVASIDKSGIIYPVIVRFNKVNYN...,0.104687,1
...,...,...,...,...
1574,Y45R,AIERGSKVKILRKESYWYGDVGTVASIDKSGIIYPVIVRFNKVNRN...,0.276797,1
1575,Y45S,AIERGSKVKILRKESYWYGDVGTVASIDKSGIIYPVIVRFNKVNSN...,0.646180,1
1576,Y45T,AIERGSKVKILRKESYWYGDVGTVASIDKSGIIYPVIVRFNKVNTN...,0.772102,1
1577,Y45V,AIERGSKVKILRKESYWYGDVGTVASIDKSGIIYPVIVRFNKVNVN...,0.682511,1
1578,Y45W,AIERGSKVKILRKESYWYGDVGTVASIDKSGIIYPVIVRFNKVNWN...,-0.111916,1

RAD_ANTMA_Rocklin_2023_2CJJ.csv
Number of dropped mutant formats: 5 / 984 = 0.5%
Number of dropped invalid amino acids: 5 / 984 = 0.5%
Number of dropped synonymous mutants: 6 / 984 = 0.6%
Number of dropped mutants not matching WT: 0 / 984 = 0.0%
Dropped mutants: Length before: 984, length after: 973: 1.1% dropped
Debug: Number of duplicate mutants: 61 (6.27%)
Final length: 912

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A13C,PWSAKENKAFERCLAVYDKDTPDRWANVARAVEGRTPEEVKKHYEI...,-1.601452,0
1,A13I,PWSAKENKAFERILAVYDKDTPDRWANVARAVEGRTPEEVKKHYEI...,-1.853531,0
2,A13L,PWSAKENKAFERLLAVYDKDTPDRWANVARAVEGRTPEEVKKHYEI...,-1.338409,0
3,A13M,PWSAKENKAFERMLAVYDKDTPDRWANVARAVEGRTPEEVKKHYEI...,-1.982259,0
4,A13W,PWSAKENKAFERWLAVYDKDTPDRWANVARAVEGRTPEEVKKHYEI...,-1.684951,0
...,...,...,...,...
907,Y53R,PWSAKENKAFERALAVYDKDTPDRWANVARAVEGRTPEEVKKHYEI...,0.078223,1
908,Y53S,PWSAKENKAFERALAVYDKDTPDRWANVARAVEGRTPEEVKKHYEI...,0.173053,1
909,Y53T,PWSAKENKAFERALAVYDKDTPDRWANVARAVEGRTPEEVKKHYEI...,0.124233,1
910,Y53V,PWSAKENKAFERALAVYDKDTPDRWANVARAVEGRTPEEVKKHYEI...,0.041295,1
911,Y53W,PWSAKENKAFERALAVYDKDTPDRWANVARAVEGRTPEEVKKHYEI...,0.213302,1

RBP1_HUMAN_Rocklin_2023_2KWH.csv
Number of dropped mutant formats: 5 / 1375 = 0.4%
Number of dropped invalid amino acids: 5 / 1375 = 0.4%
Number of dropped synonymous mutants: 1 / 1375 = 0.1%
Number of dropped mutants not matching WT: 0 / 1375 = 0.0%
Dropped mutants: Length before: 1375, length after: 1369: 0.4% dropped
Debug: Number of duplicate mutants: 37 (2.70%)
Final length: 1332

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A46C,ETQAGIKEEIRRQEFLLNSLHRDLQGGIKDLSKEERLWEVQRILTC...,0.503519,1
1,A46D,ETQAGIKEEIRRQEFLLNSLHRDLQGGIKDLSKEERLWEVQRILTD...,0.162813,1
2,A46E,ETQAGIKEEIRRQEFLLNSLHRDLQGGIKDLSKEERLWEVQRILTE...,0.374461,1
3,A46F,ETQAGIKEEIRRQEFLLNSLHRDLQGGIKDLSKEERLWEVQRILTF...,-0.051768,1
4,A46G,ETQAGIKEEIRRQEFLLNSLHRDLQGGIKDLSKEERLWEVQRILTG...,-0.405567,0
...,...,...,...,...
1327,W38R,ETQAGIKEEIRRQEFLLNSLHRDLQGGIKDLSKEERLREVQRILTA...,0.409986,1
1328,W38S,ETQAGIKEEIRRQEFLLNSLHRDLQGGIKDLSKEERLSEVQRILTA...,-0.026247,1
1329,W38T,ETQAGIKEEIRRQEFLLNSLHRDLQGGIKDLSKEERLTEVQRILTA...,-0.047858,1
1330,W38V,ETQAGIKEEIRRQEFLLNSLHRDLQGGIKDLSKEERLVEVQRILTA...,0.207099,1
1331,W38Y,ETQAGIKEEIRRQEFLLNSLHRDLQGGIKDLSKEERLYEVQRILTA...,0.085070,1

RCD1_ARATH_Rocklin_2023_5OAO.csv
Number of dropped mutant formats: 5 / 1318 = 0.4%
Number of dropped invalid amino acids: 5 / 1318 = 0.4%
Number of dropped synonymous mutants: 2 / 1318 = 0.2%
Number of dropped mutants not matching WT: 0 / 1318 = 0.0%
Dropped mutants: Length before: 1318, length after: 1311: 0.5% dropped
Debug: Number of duplicate mutants: 50 (3.81%)
Final length: 1261

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A12C,PTLFAAISHKVCENDMLLINADYQQLRDKKMTRAEFVRKLRVIVGD...,-0.055102,1
1,A12D,PTLFAAISHKVDENDMLLINADYQQLRDKKMTRAEFVRKLRVIVGD...,0.033589,1
2,A12E,PTLFAAISHKVEENDMLLINADYQQLRDKKMTRAEFVRKLRVIVGD...,-0.125133,1
3,A12F,PTLFAAISHKVFENDMLLINADYQQLRDKKMTRAEFVRKLRVIVGD...,-0.346065,1
4,A12G,PTLFAAISHKVGENDMLLINADYQQLRDKKMTRAEFVRKLRVIVGD...,0.261256,1
...,...,...,...,...
1256,Y23R,PTLFAAISHKVAENDMLLINADRQQLRDKKMTRAEFVRKLRVIVGD...,-1.198557,0
1257,Y23S,PTLFAAISHKVAENDMLLINADSQQLRDKKMTRAEFVRKLRVIVGD...,-1.729108,0
1258,Y23T,PTLFAAISHKVAENDMLLINADTQQLRDKKMTRAEFVRKLRVIVGD...,-1.748630,0
1259,Y23V,PTLFAAISHKVAENDMLLINADVQQLRDKKMTRAEFVRKLRVIVGD...,-0.964028,0
1260,Y23W,PTLFAAISHKVAENDMLLINADWQQLRDKKMTRAEFVRKLRVIVGD...,0.196689,1

RCRO_LAMBD_Rocklin_2023_1ORC.csv
Number of dropped mutant formats: 5 / 2402 = 0.2%
Number of dropped invalid amino acids: 5 / 2402 = 0.2%
Number of dropped synonymous mutants: 3 / 2402 = 0.1%
Number of dropped mutants not matching WT: 0 / 2402 = 0.0%
Dropped mutants: Length before: 2402, length after: 2394: 0.3% dropped
Debug: Number of duplicate mutants: 116 (4.85%)
Final length: 2278

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A18C,QRITLKDYAMRFGQTKTCKDLGVYQSAINKAIHAGRKIFLTINADG...,-1.477334,0
1,A18D,QRITLKDYAMRFGQTKTDKDLGVYQSAINKAIHAGRKIFLTINADG...,-3.254591,0
2,A18E,QRITLKDYAMRFGQTKTEKDLGVYQSAINKAIHAGRKIFLTINADG...,-2.144791,0
3,A18F,QRITLKDYAMRFGQTKTFKDLGVYQSAINKAIHAGRKIFLTINADG...,-2.714949,0
4,A18G,QRITLKDYAMRFGQTKTGKDLGVYQSAINKAIHAGRKIFLTINADG...,-1.211476,1
...,...,...,...,...
2273,Y8W:K16S,QRITLKDWAMRFGQTSTAKDLGVYQSAINKAIHAGRKIFLTINADG...,-2.852619,0
2274,Y8W:K16T,QRITLKDWAMRFGQTTTAKDLGVYQSAINKAIHAGRKIFLTINADG...,-2.697032,0
2275,Y8W:K16V,QRITLKDWAMRFGQTVTAKDLGVYQSAINKAIHAGRKIFLTINADG...,-2.714647,0
2276,Y8W:K16W,QRITLKDWAMRFGQTWTAKDLGVYQSAINKAIHAGRKIFLTINADG...,-3.223169,0
2277,Y8W:K16Y,QRITLKDWAMRFGQTYTAKDLGVYQSAINKAIHAGRKIFLTINADG...,-3.305626,0

RD23A_HUMAN_Rocklin_2023_1IFY.csv
Number of dropped mutant formats: 4 / 1050 = 0.4%
Number of dropped invalid amino acids: 4 / 1050 = 0.4%
Number of dropped synonymous mutants: 1 / 1050 = 0.1%
Number of dropped mutants not matching WT: 0 / 1050 = 0.0%
Dropped mutants: Length before: 1050, length after: 1045: 0.5% dropped
Debug: Number of duplicate mutants: 26 (2.49%)
Final length: 1019

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A22D,SEYETMLTEIMSMGYERERVVDALRASYNNPHRAVEYLLTGIPG,-0.501897,1
1,A22E,SEYETMLTEIMSMGYERERVVEALRASYNNPHRAVEYLLTGIPG,-0.005736,1
2,A22F,SEYETMLTEIMSMGYERERVVFALRASYNNPHRAVEYLLTGIPG,-1.221962,0
3,A22G,SEYETMLTEIMSMGYERERVVGALRASYNNPHRAVEYLLTGIPG,-1.364288,0
4,A22H,SEYETMLTEIMSMGYERERVVHALRASYNNPHRAVEYLLTGIPG,-0.699608,1
...,...,...,...,...
1014,Y3R,SERETMLTEIMSMGYERERVVAALRASYNNPHRAVEYLLTGIPG,-1.612732,0
1015,Y3S,SESETMLTEIMSMGYERERVVAALRASYNNPHRAVEYLLTGIPG,-1.610958,0
1016,Y3T,SETETMLTEIMSMGYERERVVAALRASYNNPHRAVEYLLTGIPG,-1.518703,0
1017,Y3V,SEVETMLTEIMSMGYERERVVAALRASYNNPHRAVEYLLTGIPG,-1.263340,0
1018,Y3W,SEWETMLTEIMSMGYERERVVAALRASYNNPHRAVEYLLTGIPG,-0.167562,1

RFAH_ECOLI_Rocklin_2023_2LCL.csv
Number of dropped mutant formats: 5 / 1369 = 0.4%
Number of dropped invalid amino acids: 5 / 1369 = 0.4%
Number of dropped synonymous mutants: 1 / 1369 = 0.1%
Number of dropped mutants not matching WT: 0 / 1369 = 0.0%
Dropped mutants: Length before: 1369, length after: 1363: 0.4% dropped
Debug: Number of duplicate mutants: 37 (2.71%)
Final length: 1326

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A15D,ATPYPGDKVIITEGDFEGFQAIFTEPDGEARSMLLLNLINKEIKHS...,-0.135476,1
1,A15E,ATPYPGDKVIITEGEFEGFQAIFTEPDGEARSMLLLNLINKEIKHS...,0.512185,1
2,A15F,ATPYPGDKVIITEGFFEGFQAIFTEPDGEARSMLLLNLINKEIKHS...,0.281838,1
3,A15G,ATPYPGDKVIITEGGFEGFQAIFTEPDGEARSMLLLNLINKEIKHS...,-0.615203,0
4,A15H,ATPYPGDKVIITEGHFEGFQAIFTEPDGEARSMLLLNLINKEIKHS...,-0.096641,1
...,...,...,...,...
1321,Y4R,ATPRPGDKVIITEGAFEGFQAIFTEPDGEARSMLLLNLINKEIKHS...,0.345515,1
1322,Y4S,ATPSPGDKVIITEGAFEGFQAIFTEPDGEARSMLLLNLINKEIKHS...,-0.005810,1
1323,Y4T,ATPTPGDKVIITEGAFEGFQAIFTEPDGEARSMLLLNLINKEIKHS...,-0.117560,1
1324,Y4V,ATPVPGDKVIITEGAFEGFQAIFTEPDGEARSMLLLNLINKEIKHS...,0.189592,1
1325,Y4W,ATPWPGDKVIITEGAFEGFQAIFTEPDGEARSMLLLNLINKEIKHS...,-0.167877,1

RL20_AQUAE_Rocklin_2023_1GYZ.csv
Number of dropped mutant formats: 5 / 1505 = 0.3%
Number of dropped invalid amino acids: 5 / 1505 = 0.3%
Number of dropped synonymous mutants: 1 / 1505 = 0.1%
Number of dropped mutants not matching WT: 0 / 1505 = 0.0%
Dropped mutants: Length before: 1505, length after: 1499: 0.4% dropped
Debug: Number of duplicate mutants: 38 (2.54%)
Final length: 1461

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A11C,WIARINAAVRCYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,-0.173241,1
1,A11D,WIARINAAVRDYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,-0.129564,1
2,A11E,WIARINAAVREYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,-0.109732,1
3,A11F,WIARINAAVRFYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,-0.222140,1
4,A11G,WIARINAAVRGYGLNYSTFINGLKKAGIELDRKILADMAVRDPQAF...,-0.107041,1
...,...,...,...,...
1456,Y16R,WIARINAAVRAYGLNRSTFINGLKKAGIELDRKILADMAVRDPQAF...,-1.329974,0
1457,Y16S,WIARINAAVRAYGLNSSTFINGLKKAGIELDRKILADMAVRDPQAF...,-0.590578,1
1458,Y16T,WIARINAAVRAYGLNTSTFINGLKKAGIELDRKILADMAVRDPQAF...,-0.733234,0
1459,Y16V,WIARINAAVRAYGLNVSTFINGLKKAGIELDRKILADMAVRDPQAF...,-0.389561,1
1460,Y16W,WIARINAAVRAYGLNWSTFINGLKKAGIELDRKILADMAVRDPQAF...,-0.667196,1

RPC1_BP434_Rocklin_2023_1R69.csv
Number of dropped mutant formats: 5 / 1495 = 0.3%
Number of dropped invalid amino acids: 5 / 1495 = 0.3%
Number of dropped synonymous mutants: 1 / 1495 = 0.1%
Number of dropped mutants not matching WT: 0 / 1495 = 0.0%
Dropped mutants: Length before: 1495, length after: 1489: 0.4% dropped
Debug: Number of duplicate mutants: 30 (2.01%)
Final length: 1459

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A18C,SISSRVKSKRIQLGLNQCELAQKVGTTQQSIEQLENGKTKRPRFLP...,-0.167281,1
1,A18D,SISSRVKSKRIQLGLNQDELAQKVGTTQQSIEQLENGKTKRPRFLP...,-0.238248,1
2,A18E,SISSRVKSKRIQLGLNQEELAQKVGTTQQSIEQLENGKTKRPRFLP...,-0.034313,1
3,A18F,SISSRVKSKRIQLGLNQFELAQKVGTTQQSIEQLENGKTKRPRFLP...,0.121522,1
4,A18G,SISSRVKSKRIQLGLNQGELAQKVGTTQQSIEQLENGKTKRPRFLP...,-0.490995,1
...,...,...,...,...
1454,W58R,SISSRVKSKRIQLGLNQAELAQKVGTTQQSIEQLENGKTKRPRFLP...,-3.041730,0
1455,W58S,SISSRVKSKRIQLGLNQAELAQKVGTTQQSIEQLENGKTKRPRFLP...,-2.247879,0
1456,W58T,SISSRVKSKRIQLGLNQAELAQKVGTTQQSIEQLENGKTKRPRFLP...,-2.544818,0
1457,W58V,SISSRVKSKRIQLGLNQAELAQKVGTTQQSIEQLENGKTKRPRFLP...,-2.341668,0
1458,W58Y,SISSRVKSKRIQLGLNQAELAQKVGTTQQSIEQLENGKTKRPRFLP...,-0.791849,1

SAV1_MOUSE_Rocklin_2023_2YSB.csv
Number of dropped mutant formats: 4 / 1004 = 0.4%
Number of dropped invalid amino acids: 4 / 1004 = 0.4%
Number of dropped synonymous mutants: 1 / 1004 = 0.1%
Number of dropped mutants not matching WT: 0 / 1004 = 0.0%
Dropped mutants: Length before: 1004, length after: 999: 0.5% dropped
Debug: Number of duplicate mutants: 34 (3.40%)
Final length: 965

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,D13A,GEDLPLPPGWSVAWTMRGRKYYIDHNTNTTHWSHPLESGPSSG,1.054366,1
1,D13C,GEDLPLPPGWSVCWTMRGRKYYIDHNTNTTHWSHPLESGPSSG,1.404363,1
2,D13E,GEDLPLPPGWSVEWTMRGRKYYIDHNTNTTHWSHPLESGPSSG,0.466943,1
3,D13F,GEDLPLPPGWSVFWTMRGRKYYIDHNTNTTHWSHPLESGPSSG,0.013240,1
4,D13G,GEDLPLPPGWSVGWTMRGRKYYIDHNTNTTHWSHPLESGPSSG,0.803262,1
...,...,...,...,...
960,Y21R,GEDLPLPPGWSVDWTMRGRKRYIDHNTNTTHWSHPLESGPSSG,-1.456297,0
961,Y21V,GEDLPLPPGWSVDWTMRGRKVYIDHNTNTTHWSHPLESGPSSG,-0.805862,0
962,Y21W,GEDLPLPPGWSVDWTMRGRKWYIDHNTNTTHWSHPLESGPSSG,-1.730437,0
963,Y22F,GEDLPLPPGWSVDWTMRGRKYFIDHNTNTTHWSHPLESGPSSG,-0.531063,1
964,Y22W,GEDLPLPPGWSVDWTMRGRKYWIDHNTNTTHWSHPLESGPSSG,-0.502923,1

SDA_BACSU_Rocklin_2023_1PV0.csv
Number of dropped mutant formats: 5 / 2998 = 0.2%
Number of dropped invalid amino acids: 5 / 2998 = 0.2%
Number of dropped synonymous mutants: 6 / 2998 = 0.2%
Number of dropped mutants not matching WT: 0 / 2998 = 0.0%
Dropped mutants: Length before: 2998, length after: 2987: 0.4% dropped
Debug: Number of duplicate mutants: 217 (7.26%)
Final length: 2770

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A16C,MRKLSDELLIESYFKCTEMNLNRDFIELIENEIKRRSLGHIISV,-0.533935,1
1,A16D,MRKLSDELLIESYFKDTEMNLNRDFIELIENEIKRRSLGHIISV,-2.151397,0
2,A16E,MRKLSDELLIESYFKETEMNLNRDFIELIENEIKRRSLGHIISV,-0.870078,1
3,A16F,MRKLSDELLIESYFKFTEMNLNRDFIELIENEIKRRSLGHIISV,-0.328954,1
4,A16G,MRKLSDELLIESYFKGTEMNLNRDFIELIENEIKRRSLGHIISV,-0.961885,1
...,...,...,...,...
2765,Y13R,MRKLSDELLIESRFKATEMNLNRDFIELIENEIKRRSLGHIISV,-2.104423,0
2766,Y13S,MRKLSDELLIESSFKATEMNLNRDFIELIENEIKRRSLGHIISV,-2.647349,0
2767,Y13T,MRKLSDELLIESTFKATEMNLNRDFIELIENEIKRRSLGHIISV,-2.989533,0
2768,Y13V,MRKLSDELLIESVFKATEMNLNRDFIELIENEIKRRSLGHIISV,-2.057565,0
2769,Y13W,MRKLSDELLIESWFKATEMNLNRDFIELIENEIKRRSLGHIISV,0.334262,1

SPA_STAAU_Rocklin_2023_1LP1.csv
Number of dropped mutant formats: 5 / 2228 = 0.2%
Number of dropped invalid amino acids: 5 / 2228 = 0.2%
Number of dropped synonymous mutants: 3 / 2228 = 0.1%
Number of dropped mutants not matching WT: 0 / 2228 = 0.0%
Dropped mutants: Length before: 2228, length after: 2220: 0.4% dropped
Debug: Number of duplicate mutants: 115 (5.18%)
Final length: 2105

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A26C,KFNKELSVAGREIVTLPNLNDPQKKCFIFSLWDDPSQSANLLAEAK...,0.552203,1
1,A26D,KFNKELSVAGREIVTLPNLNDPQKKDFIFSLWDDPSQSANLLAEAK...,-0.682771,1
2,A26E,KFNKELSVAGREIVTLPNLNDPQKKEFIFSLWDDPSQSANLLAEAK...,-0.465967,1
3,A26F,KFNKELSVAGREIVTLPNLNDPQKKFFIFSLWDDPSQSANLLAEAK...,0.513970,1
4,A26G,KFNKELSVAGREIVTLPNLNDPQKKGFIFSLWDDPSQSANLLAEAK...,-0.228084,1
...,...,...,...,...
2100,W32R,KFNKELSVAGREIVTLPNLNDPQKKAFIFSLRDDPSQSANLLAEAK...,-1.514936,0
2101,W32S,KFNKELSVAGREIVTLPNLNDPQKKAFIFSLSDDPSQSANLLAEAK...,-0.692116,1
2102,W32T,KFNKELSVAGREIVTLPNLNDPQKKAFIFSLTDDPSQSANLLAEAK...,-0.515412,1
2103,W32V,KFNKELSVAGREIVTLPNLNDPQKKAFIFSLVDDPSQSANLLAEAK...,-0.601892,1
2104,W32Y,KFNKELSVAGREIVTLPNLNDPQKKAFIFSLYDDPSQSANLLAEAK...,0.118803,1

SPG2_STRSG_Rocklin_2023_5UBS.csv
Number of dropped mutant formats: 5 / 1514 = 0.3%
Number of dropped invalid amino acids: 5 / 1514 = 0.3%
Number of dropped synonymous mutants: 2 / 1514 = 0.1%
Number of dropped mutants not matching WT: 0 / 1514 = 0.0%
Dropped mutants: Length before: 1514, length after: 1507: 0.5% dropped
Debug: Number of duplicate mutants: 56 (3.72%)
Final length: 1451

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A20C,MTFKLIINGKTLKGETTTECVDAATAEKVFKQYFNDNGIDGEWTYD...,-0.475562,1
1,A20D,MTFKLIINGKTLKGETTTEDVDAATAEKVFKQYFNDNGIDGEWTYD...,-2.218316,0
2,A20E,MTFKLIINGKTLKGETTTEEVDAATAEKVFKQYFNDNGIDGEWTYD...,-1.510585,0
3,A20F,MTFKLIINGKTLKGETTTEFVDAATAEKVFKQYFNDNGIDGEWTYD...,-1.023148,0
4,A20G,MTFKLIINGKTLKGETTTEGVDAATAEKVFKQYFNDNGIDGEWTYD...,-1.695847,0
...,...,...,...,...
1446,Y45W:F52L,MTFKLIINGKTLKGETTTEAVDAATAEKVFKQYFNDNGIDGEWTWD...,-1.719492,0
1447,Y45W:F52M,MTFKLIINGKTLKGETTTEAVDAATAEKVFKQYFNDNGIDGEWTWD...,-1.978754,0
1448,Y45W:F52V,MTFKLIINGKTLKGETTTEAVDAATAEKVFKQYFNDNGIDGEWTWD...,-2.707315,0
1449,Y45W:F52W,MTFKLIINGKTLKGETTTEAVDAATAEKVFKQYFNDNGIDGEWTWD...,-2.121256,0
1450,Y45W:F52Y,MTFKLIINGKTLKGETTTEAVDAATAEKVFKQYFNDNGIDGEWTWD...,-2.617829,0

SPTN1_CHICK_Rocklin_2023_1TUD.csv
Number of dropped mutant formats: 5 / 3486 = 0.1%
Number of dropped invalid amino acids: 5 / 3486 = 0.1%
Number of dropped synonymous mutants: 8 / 3486 = 0.2%
Number of dropped mutants not matching WT: 0 / 3486 = 0.0%
Dropped mutants: Length before: 3486, length after: 3473: 0.4% dropped
Debug: Number of duplicate mutants: 272 (7.83%)
Final length: 3201

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A24C,RQGFVPAAYVKKLDSGTGKELVLCLYDYQEKSPREVTMKKGDILTL...,-0.270375,1
1,A24F,RQGFVPAAYVKKLDSGTGKELVLFLYDYQEKSPREVTMKKGDILTL...,-3.959452,0
2,A24G,RQGFVPAAYVKKLDSGTGKELVLGLYDYQEKSPREVTMKKGDILTL...,-3.049759,0
3,A24I,RQGFVPAAYVKKLDSGTGKELVLILYDYQEKSPREVTMKKGDILTL...,-3.423371,0
4,A24K,RQGFVPAAYVKKLDSGTGKELVLKLYDYQEKSPREVTMKKGDILTL...,-4.974819,0
...,...,...,...,...
3196,Y9R,RQGFVPAARVKKLDSGTGKELVLALYDYQEKSPREVTMKKGDILTL...,-1.894346,1
3197,Y9S,RQGFVPAASVKKLDSGTGKELVLALYDYQEKSPREVTMKKGDILTL...,-1.026292,1
3198,Y9T,RQGFVPAATVKKLDSGTGKELVLALYDYQEKSPREVTMKKGDILTL...,-1.847720,1
3199,Y9V,RQGFVPAAVVKKLDSGTGKELVLALYDYQEKSPREVTMKKGDILTL...,-1.986756,1
3200,Y9W,RQGFVPAAWVKKLDSGTGKELVLALYDYQEKSPREVTMKKGDILTL...,-1.362075,1

SR43C_ARATH_Rocklin_2023_2N88.csv
Number of dropped mutant formats: 5 / 1664 = 0.3%
Number of dropped invalid amino acids: 5 / 1664 = 0.3%
Number of dropped synonymous mutants: 2 / 1664 = 0.1%
Number of dropped mutants not matching WT: 0 / 1664 = 0.0%
Dropped mutants: Length before: 1664, length after: 1657: 0.4% dropped
Debug: Number of duplicate mutants: 74 (4.47%)
Final length: 1583

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A1C,CVAESVIGKRVGDDGKTIEYLVKWTDMSDATWEPQDNVDSTLVLLYQQ,-0.084522,1
1,A1D,DVAESVIGKRVGDDGKTIEYLVKWTDMSDATWEPQDNVDSTLVLLYQQ,-0.951945,1
2,A1E,EVAESVIGKRVGDDGKTIEYLVKWTDMSDATWEPQDNVDSTLVLLYQQ,-0.927790,1
3,A1F,FVAESVIGKRVGDDGKTIEYLVKWTDMSDATWEPQDNVDSTLVLLYQQ,-0.031125,1
4,A1G,GVAESVIGKRVGDDGKTIEYLVKWTDMSDATWEPQDNVDSTLVLLYQQ,-0.144374,1
...,...,...,...,...
1578,Y46R,AVAESVIGKRVGDDGKTIEYLVKWTDMSDATWEPQDNVDSTLVLLRQQ,-2.535479,0
1579,Y46S,AVAESVIGKRVGDDGKTIEYLVKWTDMSDATWEPQDNVDSTLVLLSQQ,-2.206939,0
1580,Y46T,AVAESVIGKRVGDDGKTIEYLVKWTDMSDATWEPQDNVDSTLVLLTQQ,-2.663162,0
1581,Y46V,AVAESVIGKRVGDDGKTIEYLVKWTDMSDATWEPQDNVDSTLVLLVQQ,-2.436197,0
1582,Y46W,AVAESVIGKRVGDDGKTIEYLVKWTDMSDATWEPQDNVDSTLVLLWQQ,0.509043,1

SRBS1_HUMAN_Rocklin_2023_2O2W.csv
Number of dropped mutant formats: 5 / 1599 = 0.3%
Number of dropped invalid amino acids: 5 / 1599 = 0.3%
Number of dropped synonymous mutants: 1 / 1599 = 0.1%
Number of dropped mutants not matching WT: 0 / 1599 = 0.0%
Dropped mutants: Length before: 1599, length after: 1593: 0.4% dropped
Debug: Number of duplicate mutants: 37 (2.32%)
Final length: 1556

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A11C,GIDPFTGEAICKFNFNGDTQVEMSFRKGERITLLRQVDENWYEGRI...,-1.671435,0
1,A11F,GIDPFTGEAIFKFNFNGDTQVEMSFRKGERITLLRQVDENWYEGRI...,-1.850414,0
2,A11G,GIDPFTGEAIGKFNFNGDTQVEMSFRKGERITLLRQVDENWYEGRI...,-0.563607,1
3,A11I,GIDPFTGEAIIKFNFNGDTQVEMSFRKGERITLLRQVDENWYEGRI...,-3.202739,0
4,A11L,GIDPFTGEAILKFNFNGDTQVEMSFRKGERITLLRQVDENWYEGRI...,-3.276436,0
...,...,...,...,...
1551,Y59R,GIDPFTGEAIAKFNFNGDTQVEMSFRKGERITLLRQVDENWYEGRI...,-1.285413,0
1552,Y59S,GIDPFTGEAIAKFNFNGDTQVEMSFRKGERITLLRQVDENWYEGRI...,-0.431188,1
1553,Y59T,GIDPFTGEAIAKFNFNGDTQVEMSFRKGERITLLRQVDENWYEGRI...,-0.645784,1
1554,Y59V,GIDPFTGEAIAKFNFNGDTQVEMSFRKGERITLLRQVDENWYEGRI...,-0.646076,1
1555,Y59W,GIDPFTGEAIAKFNFNGDTQVEMSFRKGERITLLRQVDENWYEGRI...,-0.943837,1

TCRG1_MOUSE_Rocklin_2023_1E0L.csv
Number of dropped mutant formats: 4 / 1107 = 0.4%
Number of dropped invalid amino acids: 4 / 1107 = 0.4%
Number of dropped synonymous mutants: 1 / 1107 = 0.1%
Number of dropped mutants not matching WT: 0 / 1107 = 0.0%
Dropped mutants: Length before: 1107, length after: 1102: 0.5% dropped
Debug: Number of duplicate mutants: 44 (3.99%)
Final length: 1058

     mutant                       mutated_sequence  DMS_score  DMS_score_bin
0      A14D  GATAVSEWTEYKTDDGKTYYYNNRTLESTWEKPQELK  -0.507220              1
1      A14E  GATAVSEWTEYKTEDGKTYYYNNRTLESTWEKPQELK  -0.279639              1
2      A14F  GATAVSEWTEYKTFDGKTYYYNNRTLESTWEKPQELK  -0.993912              1
3      A14G  GATAVSEWTEYKTGDGKTYYYNNRTLESTWEKPQELK  -0.654058              1
4      A14H  GATAVSEWTEYKTHDGKTYYYNNRTLESTWEKPQELK  -0.355978              1
...     ...                                    ...        ...            ...
1053   Y21R  GATAVSEWTEYKTADGKTYYRNNRTLESTWEKPQELK  -0.661001              1
1054   Y21S  GATAVSEWTEYKTADGKTYYSNNRTLESTWEKPQELK  -1.451504              0
1055   Y21T  GATAVSEWTEYKTADGKTYYTNNRTLESTWEKPQELK  -0.717201              1
1056   Y21V  GATAVSEWTEYKTADGKTYYVNNRTLESTWEKPQELK   0.034118              1
1057   Y21W  GATAVSEWTEYKTADGKTYYWNNRTLESTWEKPQELK  -0.401248              1

[1058 rows x 4 columns]

THO1_YEAST_Rocklin_2023_2WQG.csv
Number of dropped mutant formats: 5 / 1355 = 0.4%
Number of dropped invalid amino acids: 5 / 1355 = 0.4%
Number of dropped synonymous mutants: 2 / 1355 = 0.1%
Number of dropped mutants not matching WT: 0 / 1355 = 0.0%
Dropped mutants: Length before: 1355, length after: 1348: 0.5% dropped
Debug: Number of duplicate mutants: 69 (5.12%)
Final length: 1279

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A2C,SCDYSSLTVVQLKDLLTKRNLSVGGLKNEWVQRLIKDDEES,0.250309,1
1,A2D,SDDYSSLTVVQLKDLLTKRNLSVGGLKNEWVQRLIKDDEES,-0.223613,1
2,A2E,SEDYSSLTVVQLKDLLTKRNLSVGGLKNEWVQRLIKDDEES,-0.118965,1
3,A2F,SFDYSSLTVVQLKDLLTKRNLSVGGLKNEWVQRLIKDDEES,0.577004,1
4,A2G,SGDYSSLTVVQLKDLLTKRNLSVGGLKNEWVQRLIKDDEES,-0.293965,1
...,...,...,...,...
1274,W30Y,SADYSSLTVVQLKDLLTKRNLSVGGLKNEYVQRLIKDDEES,-1.355450,0
1275,Y4F,SADFSSLTVVQLKDLLTKRNLSVGGLKNEWVQRLIKDDEES,-2.565264,0
1276,Y4L,SADLSSLTVVQLKDLLTKRNLSVGGLKNEWVQRLIKDDEES,-2.676204,0
1277,Y4M,SADMSSLTVVQLKDLLTKRNLSVGGLKNEWVQRLIKDDEES,-2.132232,0
1278,Y4W,SADWSSLTVVQLKDLLTKRNLSVGGLKNEWVQRLIKDDEES,-1.980903,0

TNKS2_HUMAN_Rocklin_2023_5JRT.csv
Number of dropped mutant formats: 5 / 1523 = 0.3%
Number of dropped invalid amino acids: 5 / 1523 = 0.3%
Number of dropped synonymous mutants: 1 / 1523 = 0.1%
Number of dropped mutants not matching WT: 0 / 1523 = 0.0%
Dropped mutants: Length before: 1523, length after: 1517: 0.4% dropped
Debug: Number of duplicate mutants: 38 (2.50%)
Final length: 1479

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A44C,FSITQFVRNLGLEHLMDIFEREQITLRVLVEMGHKELKEIGINCYG...,0.468331,1
1,A44D,FSITQFVRNLGLEHLMDIFEREQITLRVLVEMGHKELKEIGINDYG...,0.437987,1
2,A44E,FSITQFVRNLGLEHLMDIFEREQITLRVLVEMGHKELKEIGINEYG...,0.332071,1
3,A44F,FSITQFVRNLGLEHLMDIFEREQITLRVLVEMGHKELKEIGINFYG...,-0.109920,1
4,A44G,FSITQFVRNLGLEHLMDIFEREQITLRVLVEMGHKELKEIGINGYG...,-0.245488,1
...,...,...,...,...
1474,Y45R,FSITQFVRNLGLEHLMDIFEREQITLRVLVEMGHKELKEIGINARG...,-0.207712,1
1475,Y45S,FSITQFVRNLGLEHLMDIFEREQITLRVLVEMGHKELKEIGINASG...,-0.772733,1
1476,Y45T,FSITQFVRNLGLEHLMDIFEREQITLRVLVEMGHKELKEIGINATG...,-0.773220,1
1477,Y45V,FSITQFVRNLGLEHLMDIFEREQITLRVLVEMGHKELKEIGINAVG...,-0.295739,1
1478,Y45W,FSITQFVRNLGLEHLMDIFEREQITLRVLVEMGHKELKEIGINAWG...,0.113565,1

UBE4B_HUMAN_Rocklin_2023_3L1X.csv
Number of dropped mutant formats: 5 / 4208 = 0.1%
Number of dropped invalid amino acids: 5 / 4208 = 0.1%
Number of dropped synonymous mutants: 10 / 4208 = 0.2%
Number of dropped mutants not matching WT: 0 / 4208 = 0.0%
Dropped mutants: Length before: 4208, length after: 4193: 0.4% dropped
Debug: Number of duplicate mutants: 571 (13.62%)
Final length: 3622

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A2C,DCPDEFRDPLMDTLMTDPVRLPSGTIMDRSIILRHLLNSPTDPFNR...,0.335651,1
1,A2D,DDPDEFRDPLMDTLMTDPVRLPSGTIMDRSIILRHLLNSPTDPFNR...,-2.011003,0
2,A2E,DEPDEFRDPLMDTLMTDPVRLPSGTIMDRSIILRHLLNSPTDPFNR...,-1.444741,0
3,A2F,DFPDEFRDPLMDTLMTDPVRLPSGTIMDRSIILRHLLNSPTDPFNR...,0.598484,1
4,A2G,DGPDEFRDPLMDTLMTDPVRLPSGTIMDRSIILRHLLNSPTDPFNR...,-1.321776,0
...,...,...,...,...
3617,W67Q,DAPDEFRDPLMDTLMTDPVRLPSGTIMDRSIILRHLLNSPTDPFNR...,-2.745901,0
3618,W67R,DAPDEFRDPLMDTLMTDPVRLPSGTIMDRSIILRHLLNSPTDPFNR...,-2.582125,0
3619,W67S,DAPDEFRDPLMDTLMTDPVRLPSGTIMDRSIILRHLLNSPTDPFNR...,-2.807835,0
3620,W67T,DAPDEFRDPLMDTLMTDPVRLPSGTIMDRSIILRHLLNSPTDPFNR...,-3.016122,0
3621,W67Y,DAPDEFRDPLMDTLMTDPVRLPSGTIMDRSIILRHLLNSPTDPFNR...,-0.602631,1

UBR5_HUMAN_Rocklin_2023_1I2T.csv
Number of dropped mutant formats: 5 / 1496 = 0.3%
Number of dropped invalid amino acids: 5 / 1496 = 0.3%
Number of dropped synonymous mutants: 1 / 1496 = 0.1%
Number of dropped mutants not matching WT: 0 / 1496 = 0.0%
Dropped mutants: Length before: 1496, length after: 1490: 0.4% dropped
Debug: Number of duplicate mutants: 37 (2.48%)
Final length: 1453

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A15C,HRQALGERLYPRVQCMQPAFASKITGMLLELSPAQLLLLLASEDSL...,-0.334773,1
1,A15D,HRQALGERLYPRVQDMQPAFASKITGMLLELSPAQLLLLLASEDSL...,-0.018542,1
2,A15E,HRQALGERLYPRVQEMQPAFASKITGMLLELSPAQLLLLLASEDSL...,0.073671,1
3,A15F,HRQALGERLYPRVQFMQPAFASKITGMLLELSPAQLLLLLASEDSL...,-0.121948,1
4,A15G,HRQALGERLYPRVQGMQPAFASKITGMLLELSPAQLLLLLASEDSL...,-0.370219,1
...,...,...,...,...
1448,Y10R,HRQALGERLRPRVQAMQPAFASKITGMLLELSPAQLLLLLASEDSL...,-0.277541,1
1449,Y10S,HRQALGERLSPRVQAMQPAFASKITGMLLELSPAQLLLLLASEDSL...,-1.083674,0
1450,Y10T,HRQALGERLTPRVQAMQPAFASKITGMLLELSPAQLLLLLASEDSL...,-1.009316,0
1451,Y10V,HRQALGERLVPRVQAMQPAFASKITGMLLELSPAQLLLLLASEDSL...,-1.129454,0
1452,Y10W,HRQALGERLWPRVQAMQPAFASKITGMLLELSPAQLLLLLASEDSL...,-0.020788,1

VILI_CHICK_Rocklin_2023_1YU5.csv
Number of dropped mutant formats: 5 / 2720 = 0.2%
Number of dropped invalid amino acids: 5 / 2720 = 0.2%
Number of dropped synonymous mutants: 4 / 2720 = 0.1%
Number of dropped mutants not matching WT: 0 / 2720 = 0.0%
Dropped mutants: Length before: 2720, length after: 2711: 0.3% dropped
Debug: Number of duplicate mutants: 143 (5.27%)
Final length: 2568

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A14C,KLETFPLDVLVNTCAEDLPRGVDPSRKENHLSDEDFKAVFGMTRSA...,0.237036,1
1,A14D,KLETFPLDVLVNTDAEDLPRGVDPSRKENHLSDEDFKAVFGMTRSA...,-0.153855,1
2,A14E,KLETFPLDVLVNTEAEDLPRGVDPSRKENHLSDEDFKAVFGMTRSA...,-0.268832,1
3,A14F,KLETFPLDVLVNTFAEDLPRGVDPSRKENHLSDEDFKAVFGMTRSA...,-0.553024,1
4,A14G,KLETFPLDVLVNTGAEDLPRGVDPSRKENHLSDEDFKAVFGMTRSA...,-0.472383,1
...,...,...,...,...
2563,W53R,KLETFPLDVLVNTAAEDLPRGVDPSRKENHLSDEDFKAVFGMTRSA...,-0.512859,1
2564,W53S,KLETFPLDVLVNTAAEDLPRGVDPSRKENHLSDEDFKAVFGMTRSA...,-0.283231,1
2565,W53T,KLETFPLDVLVNTAAEDLPRGVDPSRKENHLSDEDFKAVFGMTRSA...,-0.372937,1
2566,W53V,KLETFPLDVLVNTAAEDLPRGVDPSRKENHLSDEDFKAVFGMTRSA...,-0.313414,1
2567,W53Y,KLETFPLDVLVNTAAEDLPRGVDPSRKENHLSDEDFKAVFGMTRSA...,-0.240517,1

YAIA_ECOLI_Rocklin_2023_2KVT.csv
Number of dropped mutant formats: 5 / 2018 = 0.2%
Number of dropped invalid amino acids: 5 / 2018 = 0.2%
Number of dropped synonymous mutants: 4 / 2018 = 0.2%
Number of dropped mutants not matching WT: 0 / 2018 = 0.0%
Dropped mutants: Length before: 2018, length after: 2009: 0.4% dropped
Debug: Number of duplicate mutants: 119 (5.92%)
Final length: 1890

,mutant,mutated_sequence,DMS_score,DMS_score_bin
0,A25C,PREAYIVTIEKGKPGQTVTWYQLRCDHPKPDSLISEHPTAQEAMDA...,-0.071576,1
1,A25D,PREAYIVTIEKGKPGQTVTWYQLRDDHPKPDSLISEHPTAQEAMDA...,-2.026212,0
2,A25E,PREAYIVTIEKGKPGQTVTWYQLREDHPKPDSLISEHPTAQEAMDA...,-2.098785,0
3,A25F,PREAYIVTIEKGKPGQTVTWYQLRFDHPKPDSLISEHPTAQEAMDA...,-1.759015,1
4,A25G,PREAYIVTIEKGKPGQTVTWYQLRGDHPKPDSLISEHPTAQEAMDA...,-0.869425,1
...,...,...,...,...
1885,Y5R,PREARIVTIEKGKPGQTVTWYQLRADHPKPDSLISEHPTAQEAMDA...,-0.076517,1
1886,Y5S,PREASIVTIEKGKPGQTVTWYQLRADHPKPDSLISEHPTAQEAMDA...,-2.002802,0
1887,Y5T,PREATIVTIEKGKPGQTVTWYQLRADHPKPDSLISEHPTAQEAMDA...,-1.653230,1
1888,Y5V,PREAVIVTIEKGKPGQTVTWYQLRADHPKPDSLISEHPTAQEAMDA...,-1.562712,1
1889,Y5W,PREAWIVTIEKGKPGQTVTWYQLRADHPKPDSLISEHPTAQEAMDA...,0.700502,1

YNZC_BACSU_Rocklin_2023_2JVD.csv
Number of dropped mutant formats: 5 / 2479 = 0.2%
Number of dropped invalid amino acids: 5 / 2479 = 0.2%
Number of dropped synonymous mutants: 5 / 2479 = 0.2%
Number of dropped mutants not matching WT: 0 / 2479 = 0.0%
Dropped mutants: Length before: 2479, length after: 2469: 0.4% dropped
Debug: Number of duplicate mutants: 169 (6.84%)
Final length: 2300

     mutant                         mutated_sequence  DMS_score  DMS_score_bin
0      A14D  MISNAKIARINELDAKAKAGVITEEEKAEQQKLRQEYLK  -0.044412              1
1      A14E  MISNAKIARINELEAKAKAGVITEEEKAEQQKLRQEYLK   0.069826              1
2      A14F  MISNAKIARINELFAKAKAGVITEEEKAEQQKLRQEYLK  -0.033247              1
3      A14G  MISNAKIARINELGAKAKAGVITEEEKAEQQKLRQEYLK  -0.756903              1
4      A14H  MISNAKIARINELHAKAKAGVITEEEKAEQQKLRQEYLK  -0.441117              1
...     ...                                      ...        ...            ...
2295   Y37R  MISNAKIARINELAAKAKAGVITEEEKAEQQKLRQERLK  -0.453744              1
2296   Y37S  MISNAKIARINELAAKAKAGVITEEEKAEQQKLRQESLK  -0.602686              1
2297   Y37T  MISNAKIARINELAAKAKAGVITEEEKAEQQKLRQETLK  -0.570633              1
2298   Y37V  MISNAKIARINELAAKAKAGVITEEEKAEQQKLRQEVLK  -0.283027              1
2299   Y37W  MISNAKIARINELAAKAKAGVITEEEKAEQQKLRQEWLK   0.226024              1

[2300 rows x 4 columns]

Done

## Quickly compare singles counts with reference file

In [27]:
keep_versions = ["1"]
processed_list = os.listdir(dms_processed_folder_out)
filenames = []
single_lengths = []
multiple_lengths = []
pbar = tqdm(ref_df[ref_df["ProteinGym_version"] == 1].dropna(subset=necessary_cols, how='any').iterrows())
for i, row in pbar:
    pbar.set_postfix_str(row["DMS_filename"])
    assert row["DMS_filename"] in processed_list, f"{row['DMS_filename']} is not in {dms_processed_folder_out}"
    df = pd.read_csv(dms_processed_folder_out + "/" + row["DMS_filename"])
    num_multiple = df["mutant"].str.contains(":").sum()
    num_single = len(df["mutant"]) - num_multiple  # wt has been filtered out by this point
    filenames.append(row["DMS_filename"])
    single_lengths.append(num_single)
    multiple_lengths.append(num_multiple)
    

print("Done")

0it [00:00, ?it/s]

Done

In [28]:
df_lens = pd.DataFrame({"DMS_filename": filenames, "DMS_number_single_mutants": single_lengths, "DMS_number_multiple_mutants": multiple_lengths})
df_lens.head()

,DMS_filename,DMS_number_single_mutants,DMS_number_multiple_mutants
0,PAI1_HUMAN_Huttinger_2021.csv,5345,0
1,HXK4_HUMAN_Gersing_2023_abundance.csv,8396,0
2,PHOT_CHLRE_Chen_2023_singles.csv,2121,0
3,PHOT_CHLRE_Chen_2023_multiples.csv,20,165407
4,S22A1_HUMAN_Yee_2023_abundance.csv,9803,0

In [35]:
# There are a lot of differences here - interesting 
df_merged = ref_df.merge(df_lens, on="DMS_filename", how="outer")
def gentle_int_float(i):
    try :
        return float(i)
    except ValueError:
        # e.g. "6,289"
        return int(i.split(",")[0]) * 1000.0 + float(i.split(",")[1])
df_merged["DMS_number_single_mutants_x"] = df_merged["DMS_number_single_mutants_x"].apply(gentle_int_float)
# Singles
df_merged[(df_merged["ProteinGym_version"] == 1) & (df_merged["DMS_number_single_mutants_x"].astype(float) != df_merged["DMS_number_single_mutants_y"])][["DMS_filename", "DMS_number_single_mutants_x", "DMS_number_single_mutants_y"]]

,DMS_filename,DMS_number_single_mutants_x,DMS_number_single_mutants_y
95,PAI1_HUMAN_Huttinger_2021.csv,1963.0,5345.0
96,HXK4_HUMAN_Gersing_2023_abundance.csv,8395.0,8396.0
97,PHOT_CHLRE_Chen_2023_singles.csv,2184.0,2121.0
98,PHOT_CHLRE_Chen_2023_multiples.csv,0.0,20.0
99,S22A1_HUMAN_Yee_2023_abundance.csv,11029.0,9803.0
...,...,...,...
210,OPSD_HUMAN_Wan_2019.csv,168.0,165.0
211,CAR11_HUMAN_Meitlis_2020_lof.csv,2630.0,2395.0
212,CAR11_HUMAN_Meitlis_2020_gof.csv,NaN,2374.0
214,GLPA_HUMAN_Elazar_2016.csv,285.0,245.0
215,LYAM1_HUMAN_Elazar_2016.csv,245.0,359.0

## Process held assays separately

In [19]:
# Process only the Nathan ones on their own
failures_skip_manually = []
count = 0
pbar = tqdm(ref_df[ref_df["reviewed_by"] == "Nathan"].iterrows())
overwrite = True
if overwrite:
    print("Overwriting files")
for i, row in pbar:
    pbar.set_postfix_str(row["DMS_filename"])
    print(row["DMS_filename"])
    filename = dms_preprocessed_folder_nathan + "/" + row["DMS_filename"]
    # if "escape" in filename:
    #     print("tmp: Skipping escape assays")
    #     continue
    if row["DMS_filename"] in failures_skip_manually:
        print(f"Skipping {row['DMS_filename']} manually - tmp")
        continue
    if not os.path.isfile(filename):
        print("Missing file: "+filename)
        continue
    tmp_df = pd.read_csv(filename)
    assert not len(tmp_df) == 0

    # Check phenotype column in DMS
    # Ignoring start and end seq
    if pd.isna(row["raw_DMS_phenotype_name"]):
        print("No phenotype given, will use score")
        score_col = "score"
    else:
        score_col = row["raw_DMS_phenotype_name"]
    tmp_df_clean = DMS_file_cleanup(filename, target_seq=row["target_seq"], DMS_mutant_column="mut_proteingym", DMS_binarization_threshold=None, DMS_phenotype_name=score_col, DMS_directionality=row["raw_DMS_directionality"], debug=True, strict_wt_check=True)
    
    count += 1
    # Write out to processed folder
    if overwrite:
        tmp_df_clean.to_csv(dms_processed_folder_out + "/" + row["DMS_filename"], index=False)

print("Done")
print(count)

0it [00:00, ?it/s]

Overwriting files
HSP82_YEAST_Hietpas_2011.csv
Number of dropped mutant formats: 0 / 518 = 0.0%
Number of dropped invalid amino acids: 0 / 518 = 0.0%
Number of dropped synonymous mutants: 0 / 518 = 0.0%
Number of dropped mutants not matching WT: 0 / 518 = 0.0%
Debug: Number of duplicate mutants: 347 (66.99%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 171
I6TAH8_I68A0_Bloom_2014.csv
Number of dropped mutant formats: 0 / 9462 = 0.0%
Number of dropped invalid amino acids: 0 / 9462 = 0.0%
Number of dropped synonymous mutants: 0 / 9462 = 0.0%
Number of dropped mutants not matching WT: 0 / 9462 = 0.0%
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 9462
ARRS_BOVIN_Ostermaier_2014.csv
Number of dropped mutant formats: 1 / 404 = 0.2%
Number of dropped invalid amino acids: 1 / 404 = 0.2%
Number of dropped synonymous mutants: 0 / 404 = 0.0%
Number of dropped mutants not matching WT: 0 / 404 = 0.0%
Dropped mutants: Length before: 404, length after: 403: 0.2% dropped
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 399
I4EPC4_9INFA_Thyagarajan_2014.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//I4EPC4_9INFA_Thyagarajan_2014.csv
Q2N0S5_9HIV1_Dingens_2018_replication-FP16-02.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//Q2N0S5_9HIV1_Dingens_2018_replication-FP16-02.csv
Q2N0S5_9HIV1_Dingens_2018_replication-FP20-01.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//Q2N0S5_9HIV1_Dingens_2018_replication-FP20-01.csv
Q2N0S5_9HIV1_Dingens_2018_replication-VRC34.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//Q2N0S5_9HIV1_Dingens_2018_replication-VRC34.csv
Q2N0S5_9HIV1_Dingens_2019_escape-3BNC117-101074-pool.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//Q2N0S5_9HIV1_Dingens_2019_escape-3BNC117-101074-pool.csv
SOX17_MOUSE_Veerapandian_2018.csv
Number of dropped mutant formats: 8 / 236 = 3.4%
Number of dropped invalid amino acids: 8 / 236 = 3.4%
Number of dropped synonymous mutants: 0 / 236 = 0.0%
Number of dropped mutants not matching WT: 0 / 236 = 0.0%
Dropped mutants: Length before: 236, length after: 228: 3.4% dropped
Debug: Number of duplicate mutants: 171 (75.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 57
SOX2_MOUSE_Veerapandian_2018.csv
Number of dropped mutant formats: 8 / 236 = 3.4%
Number of dropped invalid amino acids: 8 / 236 = 3.4%
Number of dropped synonymous mutants: 0 / 236 = 0.0%
Number of dropped mutants not matching WT: 0 / 236 = 0.0%
Dropped mutants: Length before: 236, length after: 228: 3.4% dropped
Debug: Number of duplicate mutants: 171 (75.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 57
A4_HUMAN_Gray_2019.csv
Number of dropped mutant formats: 0 / 796 = 0.0%
Number of dropped invalid amino acids: 0 / 796 = 0.0%
Number of dropped synonymous mutants: 0 / 796 = 0.0%
Number of dropped mutants not matching WT: 0 / 796 = 0.0%
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 796
M1_I000X_Hom_2019.csv
Number of dropped mutant formats: 0 / 5040 = 0.0%
Number of dropped invalid amino acids: 0 / 5040 = 0.0%
Number of dropped synonymous mutants: 252 / 5040 = 5.0%
Number of dropped mutants not matching WT: 0 / 5040 = 0.0%
Dropped mutants: Length before: 5040, length after: 4788: 5.0% dropped
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 4788
Q53Z42_HUMAN_McShan_2019_expression.csv
Number of dropped mutant formats: 0 / 3420 = 0.0%
Number of dropped invalid amino acids: 0 / 3420 = 0.0%
Number of dropped synonymous mutants: 0 / 3420 = 0.0%
Number of dropped mutants not matching WT: 0 / 3420 = 0.0%
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 3344
Q53Z42_HUMAN_McShan_2019_binding-TAPBPR.csv
Number of dropped mutant formats: 0 / 3420 = 0.0%
Number of dropped invalid amino acids: 0 / 3420 = 0.0%
Number of dropped synonymous mutants: 0 / 3420 = 0.0%
Number of dropped mutants not matching WT: 0 / 3420 = 0.0%
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 3344
A0A3G4RHW3_ATRBE_Wrenbeck_2019.csv
Number of dropped mutant formats: 0 / 6060 = 0.0%
Number of dropped invalid amino acids: 0 / 6060 = 0.0%
Number of dropped synonymous mutants: 303 / 6060 = 5.0%
Number of dropped mutants not matching WT: 0 / 6060 = 0.0%
Dropped mutants: Length before: 6060, length after: 5757: 5.0% dropped
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 4840
LGK_LIPST_Wrenbeck_2019.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//LGK_LIPST_Wrenbeck_2019.csv
RPC1_LAMBD_Li_2019_low-expression.csv
Number of dropped mutant formats: 1 / 352 = 0.3%
Number of dropped invalid amino acids: 1 / 352 = 0.3%
Number of dropped synonymous mutants: 0 / 352 = 0.0%
Number of dropped mutants not matching WT: 0 / 352 = 0.0%
Dropped mutants: Length before: 352, length after: 351: 0.3% dropped
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 351
RPC1_LAMBD_Li_2019_high-expression.csv
Number of dropped mutant formats: 1 / 352 = 0.3%
Number of dropped invalid amino acids: 1 / 352 = 0.3%
Number of dropped synonymous mutants: 0 / 352 = 0.0%
Number of dropped mutants not matching WT: 0 / 352 = 0.0%
Dropped mutants: Length before: 352, length after: 351: 0.3% dropped
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 351
RASK_HUMAN_Ursu_2020.csv
Number of dropped mutant formats: 1 / 82 = 1.2%
Number of dropped invalid amino acids: 1 / 82 = 1.2%
Number of dropped synonymous mutants: 0 / 82 = 0.0%
Number of dropped mutants not matching WT: 0 / 82 = 0.0%
Dropped mutants: Length before: 82, length after: 81: 1.2% dropped
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 81
P53_HUMAN_Ursu_2020.csv
Number of dropped mutant formats: 1 / 86 = 1.2%
Number of dropped invalid amino acids: 1 / 86 = 1.2%
Number of dropped synonymous mutants: 0 / 86 = 0.0%
Number of dropped mutants not matching WT: 0 / 86 = 0.0%
Dropped mutants: Length before: 86, length after: 85: 1.2% dropped
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 84
SPIKE_SARS2_Greany_2020_escape-COV2-2050.csv
Number of dropped mutant formats: 0 / 2355 = 0.0%
Number of dropped invalid amino acids: 0 / 2355 = 0.0%
Number of dropped synonymous mutants: 0 / 2355 = 0.0%
Number of dropped mutants not matching WT: 0 / 2355 = 0.0%
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 2355
SPIKE_SARS2_Greany_2020_escape-COV2-2082.csv
Number of dropped mutant formats: 0 / 2355 = 0.0%
Number of dropped invalid amino acids: 0 / 2355 = 0.0%
Number of dropped synonymous mutants: 0 / 2355 = 0.0%
Number of dropped mutants not matching WT: 0 / 2355 = 0.0%
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 2355
SPIKE_SARS2_Greany_2020_escape-COV2-2094.csv
Number of dropped mutant formats: 0 / 2355 = 0.0%
Number of dropped invalid amino acids: 0 / 2355 = 0.0%
Number of dropped synonymous mutants: 0 / 2355 = 0.0%
Number of dropped mutants not matching WT: 0 / 2355 = 0.0%
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 2355
SPIKE_SARS2_Greany_2020_escape-COV2-2096.csv
Number of dropped mutant formats: 0 / 2355 = 0.0%
Number of dropped invalid amino acids: 0 / 2355 = 0.0%
Number of dropped synonymous mutants: 0 / 2355 = 0.0%
Number of dropped mutants not matching WT: 0 / 2355 = 0.0%
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 2355
SPIKE_SARS2_Greany_2020_escape-COV2-2165.csv
Number of dropped mutant formats: 0 / 2355 = 0.0%
Number of dropped invalid amino acids: 0 / 2355 = 0.0%
Number of dropped synonymous mutants: 0 / 2355 = 0.0%
Number of dropped mutants not matching WT: 0 / 2355 = 0.0%
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 2355
SPIKE_SARS2_Greany_2020_escape-COV2-2479.csv
Number of dropped mutant formats: 0 / 2355 = 0.0%
Number of dropped invalid amino acids: 0 / 2355 = 0.0%
Number of dropped synonymous mutants: 0 / 2355 = 0.0%
Number of dropped mutants not matching WT: 0 / 2355 = 0.0%
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 2355
SPIKE_SARS2_Greany_2020_escape-COV2-2499.csv
Number of dropped mutant formats: 0 / 2355 = 0.0%
Number of dropped invalid amino acids: 0 / 2355 = 0.0%
Number of dropped synonymous mutants: 0 / 2355 = 0.0%
Number of dropped mutants not matching WT: 0 / 2355 = 0.0%
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 2355
SPIKE_SARS2_Greany_2020_escape-COV2-2677.csv
Number of dropped mutant formats: 0 / 2355 = 0.0%
Number of dropped invalid amino acids: 0 / 2355 = 0.0%
Number of dropped synonymous mutants: 0 / 2355 = 0.0%
Number of dropped mutants not matching WT: 0 / 2355 = 0.0%
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 2355
SPIKE_SARS2_Greany_2020_escape-COV2-2832.csv
Number of dropped mutant formats: 0 / 2355 = 0.0%
Number of dropped invalid amino acids: 0 / 2355 = 0.0%
Number of dropped synonymous mutants: 0 / 2355 = 0.0%
Number of dropped mutants not matching WT: 0 / 2355 = 0.0%
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 2355
SPIKE_SARS2_Greany_2020_escape-rCR3022.csv
Number of dropped mutant formats: 0 / 2355 = 0.0%
Number of dropped invalid amino acids: 0 / 2355 = 0.0%
Number of dropped synonymous mutants: 0 / 2355 = 0.0%
Number of dropped mutants not matching WT: 0 / 2355 = 0.0%
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 2355
B2L11_HUMAN_Dutta_2010_binding-Mcl-1.csv
Number of dropped mutant formats: 20 / 200 = 10.0%
Number of dropped invalid amino acids: 20 / 200 = 10.0%
Number of dropped synonymous mutants: 0 / 200 = 0.0%
Number of dropped mutants not matching WT: 0 / 200 = 0.0%
Dropped mutants: Length before: 200, length after: 180: 10.0% dropped
Debug: Number of duplicate mutants: 10 (5.56%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 170
B2L11_HUMAN_Dutta_2010_binding-Bcl-xL.csv
Number of dropped mutant formats: 20 / 200 = 10.0%
Number of dropped invalid amino acids: 20 / 200 = 10.0%
Number of dropped synonymous mutants: 0 / 200 = 0.0%
Number of dropped mutants not matching WT: 0 / 200 = 0.0%
Dropped mutants: Length before: 200, length after: 180: 10.0% dropped
Debug: Number of duplicate mutants: 10 (5.56%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 170
BRCA1_HUMAN_Starita_2015_enzyme-function.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//BRCA1_HUMAN_Starita_2015_enzyme-function.csv
BRCA1_HUMAN_Starita_2015_binding.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//BRCA1_HUMAN_Starita_2015_binding.csv
I4EPC4_9INFA_Doud_2017_escape-mAb-1ugml-H17-L19.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//I4EPC4_9INFA_Doud_2017_escape-mAb-1ugml-H17-L19.csv
I4EPC4_9INFA_Doud_2017_escape-mAb-10ugml-H17-L19.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//I4EPC4_9INFA_Doud_2017_escape-mAb-10ugml-H17-L19.csv
I4EPC4_9INFA_Doud_2017_escape-mAb-05ugml-H17-L19.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//I4EPC4_9INFA_Doud_2017_escape-mAb-05ugml-H17-L19.csv
I4EPC4_9INFA_Doud_2017_escape-mAb-H17-L7.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//I4EPC4_9INFA_Doud_2017_escape-mAb-H17-L7.csv
I4EPC4_9INFA_Doud_2017_escape-mAb-H18-S415.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//I4EPC4_9INFA_Doud_2017_escape-mAb-H18-S415.csv
I4EPC4_9INFA_Doud_2017_escape-mAb-H18-S415.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//I4EPC4_9INFA_Doud_2017_escape-mAb-H18-S415.csv
F1PDQ3_CANLF_Medina-Cucurella_2018_binding.csv
Number of dropped mutant formats: 0 / 1957 = 0.0%
Number of dropped invalid amino acids: 0 / 1957 = 0.0%
Number of dropped synonymous mutants: 0 / 1957 = 0.0%
Number of dropped mutants not matching WT: 0 / 1957 = 0.0%
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 1646
F1PDQ3_CANLF_Medina-Cucurella_2018_binding.csv
Number of dropped mutant formats: 0 / 1957 = 0.0%
Number of dropped invalid amino acids: 0 / 1957 = 0.0%
Number of dropped synonymous mutants: 0 / 1957 = 0.0%
Number of dropped mutants not matching WT: 0 / 1957 = 0.0%
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 1646
F1PDQ3_CANLF_Medina-Cucurella_2018_binding-conformation-specific.csv
Number of dropped mutant formats: 0 / 1957 = 0.0%
Number of dropped invalid amino acids: 0 / 1957 = 0.0%
Number of dropped synonymous mutants: 0 / 1957 = 0.0%
Number of dropped mutants not matching WT: 0 / 1957 = 0.0%
Debug: Number of duplicate mutants: 0 (0.00%)
No binarization threshold given, will outputs NaNs in that column for now.
Final length: 1646
Q2N0S5_9HIV1_Dingens_2019_escape-VRC01.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//Q2N0S5_9HIV1_Dingens_2019_escape-VRC01.csv
Q2N0S5_9HIV1_Dingens_2019_escape-3BNC117.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//Q2N0S5_9HIV1_Dingens_2019_escape-3BNC117.csv
Q2N0S5_9HIV1_Dingens_2019_escape-PGT121.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//Q2N0S5_9HIV1_Dingens_2019_escape-PGT121.csv
Q2N0S5_9HIV1_Dingens_2019_escape-101074.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//Q2N0S5_9HIV1_Dingens_2019_escape-101074.csv
Q2N0S5_9HIV1_Dingens_2019_escape-PG9.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//Q2N0S5_9HIV1_Dingens_2019_escape-PG9.csv
Q2N0S5_9HIV1_Dingens_2019_escape-PGT145.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//Q2N0S5_9HIV1_Dingens_2019_escape-PGT145.csv
Q2N0S5_9HIV1_Dingens_2019_escape-PGT151.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//Q2N0S5_9HIV1_Dingens_2019_escape-PGT151.csv
Q2N0S5_9HIV1_Dingens_2019_escape-VRC34.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//Q2N0S5_9HIV1_Dingens_2019_escape-VRC34.csv
Q2N0S5_9HIV1_Dingens_2019_escape-10E8.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//Q2N0S5_9HIV1_Dingens_2019_escape-10E8.csv
Q2N0S5_9HIV1_Dingens_2019_enfuvirtide.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//Q2N0S5_9HIV1_Dingens_2019_enfuvirtide.csv
W8QFD5_ZIKV_Setoh_2019_replication-insect-Aedes.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//W8QFD5_ZIKV_Setoh_2019_replication-insect-Aedes.csv
W8QFD5_ZIKV_Setoh_2019_replication-mammal-Vero.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//W8QFD5_ZIKV_Setoh_2019_replication-mammal-Vero.csv
B3RDS9_9INFA_Wu_2019_replication.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//B3RDS9_9INFA_Wu_2019_replication.csv
B3RDS9_9INFA_Wu_2019_replication-CR9114-2ugmL.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//B3RDS9_9INFA_Wu_2019_replication-CR9114-2ugmL.csv
B3RDS9_9INFA_Wu_2019_replication-CR9114-10ugmL.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//B3RDS9_9INFA_Wu_2019_replication-CR9114-10ugmL.csv
B3RDS9_9INFA_Wu_2019_replication-FI6v3-0.3ugmL.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//B3RDS9_9INFA_Wu_2019_replication-FI6v3-0.3ugmL.csv
B3RDS9_9INFA_Wu_2019_replication-FI6v3-2.5ugmL.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//B3RDS9_9INFA_Wu_2019_replication-FI6v3-2.5ugmL.csv
Ogden_2019_AAV_dms.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//Ogden_2019_AAV_dms.csv
REP68_AAV2S_Ogden_2019_capsid-formation-55C.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//REP68_AAV2S_Ogden_2019_capsid-formation-55C.csv
REP68_AAV2S_Ogden_2019_capsid-formation-60C.csv
Missing file: /n/groups/marks/projects/marks_lab_and_oatml/ProteinGym/DMS_assays/raw_data/Nathan_2023_staging/assays_offsets_fixed//REP68_AAV2S_Ogden_2019_capsid-formation-60C.csv
REP68_AAV2S_Ogden_2019_capsid-formation-65C.csv

In [79]:
# Tmp get indices of Nathan assays
score_indices = []
for i, row in ref_df[ref_df["reviewed_by"] == "Nathan"].iterrows():
    if os.path.isfile(dms_processed_folder_out + "/" + row["DMS_filename"]):
        print(row["DMS_filename"])
        score_indices.append(i)

def indices_runs(indices):
    # Print consecutive runs together as a range, for sbatch
    runs = []
    for i in indices:
        if i == indices[0]:
            start = i
            current = i
        elif i == current + 1:
            current += 1
        else:
            if start == current:
                runs.append(str(start))
            else:
                runs.append(f"{start}-{current}")
            start = i
            current = i
    return ",".join(runs)
print(score_indices)
indices_runs(score_indices)

HSP82_YEAST_Hietpas_2011.csv
I6TAH8_I68A0_Bloom_2014.csv
ARRS_BOVIN_Ostermaier_2014.csv
SOX17_MOUSE_Veerapandian_2018.csv
SOX2_MOUSE_Veerapandian_2018.csv
A4_HUMAN_Gray_2019.csv
M1_I000X_Hom_2019.csv
Q53Z42_HUMAN_McShan_2019_expression.csv
Q53Z42_HUMAN_McShan_2019_binding-TAPBPR.csv
A0A3G4RHW3_ATRBE_Wrenbeck_2019.csv
B3VI55_LIPST_Wrenbeck_2019.csv
RPC1_LAMBD_Li_2019_low-expression.csv
RPC1_LAMBD_Li_2019_high-expression.csv
RASK_HUMAN_Ursu_2020.csv
P53_HUMAN_Ursu_2020.csv
SPIKE_SARS2_Greany_2020_escape-COV2-2050.csv
SPIKE_SARS2_Greany_2020_escape-COV2-2082.csv
SPIKE_SARS2_Greany_2020_escape-COV2-2094.csv
SPIKE_SARS2_Greany_2020_escape-COV2-2096.csv
SPIKE_SARS2_Greany_2020_escape-COV2-2165.csv
SPIKE_SARS2_Greany_2020_escape-COV2-2479.csv
SPIKE_SARS2_Greany_2020_escape-COV2-2499.csv
SPIKE_SARS2_Greany_2020_escape-COV2-2677.csv
SPIKE_SARS2_Greany_2020_escape-COV2-2832.csv
SPIKE_SARS2_Greany_2020_escape-rCR3022.csv
B2L11_HUMAN_Dutta_2010_binding-Mcl-1.csv
B2L11_HUMAN_Dutta_2010_binding-Bcl-xL.csv
F1PDQ3_CANLF_Medina-Cucurella_2018_binding.csv
F1PDQ3_CANLF_Medina-Cucurella_2018_binding.csv
F1PDQ3_CANLF_Medina-Cucurella_2018_binding-conformation-specific.csv
HSP82_YEAST_Cote-Hammarlof_2020_growth.csv
HSP82_YEAST_Cote-Hammarlof_2020_growth-Diamide.csv
HSP82_YEAST_Cote-Hammarlof_2020_growth-H2O2.csv
HSP82_YEAST_Cote-Hammarlof_2020_growth-Salt.csv
HSP82_YEAST_Cote-Hammarlof_2020_growth-Sorbitol.csv
TRIM5_HUMAN_Tenthorey_2020_resistance-HIV.csv
TRIM5_HUMAN_Tenthorey_2020_resistance-N-MLV.csv
[124, 125, 126, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 164, 165, 166, 203, 204, 205, 206, 207, 208, 209]

'124-126,132-155,164-166'

## Reprocess Flynn from v0.1 with new 37C phenotype

In [21]:
dms_id = "HSP82_YEAST_Flynn_2019"
row = ref_df[ref_df["DMS_id"] == dms_id]
assert len(row) == 1
row = row.iloc[0]
filename = dms_preprocessed_folder + row["DMS_filename"]

tmp_df = pd.read_csv(filename)
assert not len(tmp_df) == 0

# Check phenotype column in DMS
# Ignoring start and end seq
if pd.isna(row["raw_DMS_phenotype_name"]):
    print("No phenotype given, will use score")
    score_col = "score"
else:
    score_col = row["raw_DMS_phenotype_name"]

assert score_col == "s (37°C)"
tmp_df_clean = DMS_file_cleanup(filename, target_seq=row["target_seq"], DMS_mutant_column=row["raw_DMS_mutant_column"], DMS_binarization_threshold=row["DMS_binarization_cutoff"], DMS_phenotype_name=score_col, DMS_directionality=row["raw_DMS_directionality"], debug=True, strict_wt_check=True)

dest = dms_processed_folder_out + "/" + row["DMS_filename"]
assert not os.path.isfile(dest)
tmp_df_clean.to_csv(dest, index=False)

Number of dropped mutant formats: 0 / 14868 = 0.0%
Number of dropped invalid amino acids: 708 / 14868 = 4.8%
Number of dropped synonymous mutants: 708 / 14868 = 4.8%
Number of dropped mutants not matching WT: 0 / 14868 = 0.0%
Dropped mutants: Length before: 14868, length after: 13452: 9.5% dropped
Debug: Number of duplicate mutants: 0 (0.00%)
Final length: 13294